// Every acronym the studio uses, expanded once, searchably. Studio voice:
// one honest sentence each, no fluff. ASCII quotes only.
export const ACRONYM_CATS = {
  traffic: 'Traffic & Protocols',
  data: 'Data & Storage',
  messaging: 'Messaging & Streaming',
  reliability: 'Reliability & Ops',
  security: 'Security & Identity',
  cloud: 'Cloud & Infra',
  business: 'Business & Product',
  ai: 'AI & ML',
}

export const ACRONYMS = [
  { a: 'AYUSH', f: 'Ayurveda, Yoga, Unani, Siddha, Homoeopathy', d: 'India\'s ministry and ecosystem for traditional medicine - the reason ayurvedic teleconsultation has formal practice guidelines and a digital grid to integrate with.', c: 'business' },
  { a: 'ABDM', f: 'Ayushman Bharat Digital Mission', d: 'India\'s national digital-health backbone: health ids, registries, consent-driven record exchange - the rails an AYUSH platform interoperates with rather than rebuilds.', c: 'business' },
  { a: 'NAMASTE', f: 'National AYUSH Morbidity and Standardized Terminologies Electronic portal', d: 'Standardized codes for Ayurveda, Siddha and Unani terms - the vocabulary half of dual coding. See the Ayurveda Gyaan template.', c: 'business' },
  { a: 'TM2', f: 'ICD-11 Traditional Medicine Module 2', d: 'The WHO classification chapter that gave Ayurveda, Siddha and Unani conditions international codes - the other half of dual coding, and the bridge into any modern EHR.', c: 'business' },
  { a: 'EHR', f: 'Electronic Health Record', d: 'The longitudinal clinical record - encounters, vitals, diagnoses. The design inversion: reading one is itself a recorded, consented event. See the Telemedicine template.', c: 'business' },
  { a: 'PHI', f: 'Protected Health Information', d: 'Any health data tied to an identity - the thing consent gates, audits trail, and breaches are counted in. Media-record separation exists so the video plumbing never touches it.', c: 'security' },
  { a: 'HIPAA', f: 'Health Insurance Portability and Accountability Act', d: 'The US healthcare privacy rulebook: access controls, audit trails, breach notification. The engineering translation: audit-on-read, minimum-necessary access, and retention you do not get to choose.', c: 'security' },
  { a: 'DPDP', f: 'Digital Personal Data Protection Act (India)', d: 'India\'s data-protection law: consent as the default basis, purpose limitation, and erasure rights - the reason consent is a first-class service in Indian health and fintech designs, not a checkbox.', c: 'security' },
  { a: 'FHIR', f: 'Fast Healthcare Interoperability Resources', d: 'The HL7 standard that made health records API-shaped: resources like Patient and Encounter over REST. The reason two hospital systems can exchange records without a fax machine.', c: 'business' },
  { a: 'UPI', f: 'Unified Payments Interface', d: 'India\'s real-time account-to-account rail: a phone number or VPA resolves to a bank account, and money moves in seconds, 24x7 - the system that made T+1 look optional. See the BHIM template.', c: 'business' },
  { a: 'NPCI', f: 'National Payments Corporation of India', d: 'The umbrella operator behind UPI, IMPS, RuPay and AePS - the institutional plumbing that turns payment rails into public infrastructure.', c: 'business' },
  { a: 'IMPS', f: 'Immediate Payment Service', d: 'The 24x7 instant-transfer rail that predates UPI - same real-time money movement, bank-account addressing instead of VPAs.', c: 'business' },
  { a: 'PCI DSS', f: 'Payment Card Industry Data Security Standard', d: 'The rulebook for anyone who touches card numbers. The engineering translation: tokenize at the edge so raw PANs stop at the HSM, and your audit scope shrinks from the fleet to the vault.', c: 'security' },
  { a: 'PAN', f: 'Primary Account Number', d: 'The 16 digits on the card - the thing your systems must never store raw. Everything downstream of the HSM carries a token instead.', c: 'security' },
  { a: 'KYC', f: 'Know Your Customer', d: 'Identity verification before an account exists: documents, liveness, sanctions screening. Upstream of every fintech flow in this studio, and the reason onboarding is a pipeline, not a form.', c: 'security' },
  { a: 'AML', f: 'Anti-Money Laundering', d: 'The transaction-monitoring obligation: pattern detection, threshold reports, suspicious-activity filings. Fraud detection\'s sibling with a regulator as the customer.', c: 'security' },
  { a: 'ISO 8583', f: 'ISO 8583 message format', d: 'The wire format of card authorization - the bitmap-and-fields protocol every gateway speaks to every network. Predates JSON by decades and outlives most things built on JSON.', c: 'business' },
  { a: 'T+1', f: 'Trade/Transaction date plus one day', d: 'The settlement clock: money authorized today moves tomorrow, in netted batches through clearing windows. The Card Payments template is built around this gap.', c: 'business' },
  { a: 'DeFi', f: 'Decentralized Finance', d: 'Financial primitives (lending, exchange, derivatives) as smart contracts - settlement in seconds, counterparty risk replaced by code risk. The trade is the whole story.', c: 'business' },

  { a: 'RPS', f: 'Requests Per Second', d: 'The load unit of this whole studio - every capacity number, cost figure and ROI line is denominated in it.', c: 'traffic' },
  { a: 'QPS', f: 'Queries Per Second', d: 'RPS wearing a database hat; interviewers use the two interchangeably.', c: 'traffic' },
  { a: 'P99', f: '99th Percentile latency', d: 'The experience of your unluckiest 1% - tails, not averages, are what users call slow.', c: 'traffic' },
  { a: 'TTL', f: 'Time To Live', d: 'How long a cache entry stays valid; short TTLs chase freshness, long ones chase hit rate.', c: 'traffic' },
  { a: 'LRU', f: 'Least Recently Used', d: 'The classic eviction policy: when the cache is full, drop what nobody touched longest.', c: 'traffic' },
  { a: 'CDN', f: 'Content Delivery Network', d: 'Copies of your static bytes parked near users; the cheapest latency win in the catalog.', c: 'traffic' },
  { a: 'PoP', f: 'Point of Presence', d: 'One physical edge location of a CDN or edge network.', c: 'traffic' },
  { a: 'LB', f: 'Load Balancer', d: 'Spreads traffic across replicas and quietly routes around the dead ones.', c: 'traffic' },
  { a: 'RTT', f: 'Round Trip Time', d: 'One network there-and-back; every synchronous hop stacks at least one RTT onto latency.', c: 'traffic' },
  { a: 'TCP', f: 'Transmission Control Protocol', d: 'Reliable ordered bytes with handshakes - the default transport under HTTP.', c: 'traffic' },
  { a: 'UDP', f: 'User Datagram Protocol', d: 'Fire-and-forget packets; what you build on when you would rather drop than wait.', c: 'traffic' },
  { a: 'QUIC', f: 'Quick UDP Internet Connections', d: 'HTTP/3s transport: TLS and multiplexing over UDP, killing head-of-line blocking.', c: 'traffic' },
  { a: 'WS', f: 'WebSocket', d: 'A held-open two-way connection - chat, presence and live dashboards ride it.', c: 'traffic' },
  { a: 'SSE', f: 'Server-Sent Events', d: 'One-way server push over plain HTTP; simpler than WS when clients only listen.', c: 'traffic' },
  { a: 'gRPC', f: 'Google Remote Procedure Call', d: 'Typed service-to-service calls over HTTP/2 with protobuf - the east-west workhorse.', c: 'traffic' },
  { a: 'REST', f: 'Representational State Transfer', d: 'Resources and verbs over HTTP - the north-south lingua franca of public APIs.', c: 'traffic' },
  { a: 'API', f: 'Application Programming Interface', d: 'The contract between callers and a service; the part of your design users actually touch.', c: 'traffic' },
  { a: 'DNS', f: 'Domain Name System', d: 'Names to addresses; its TTLs and failover behavior quietly shape every outage story.', c: 'traffic' },
  { a: 'CORS', f: 'Cross-Origin Resource Sharing', d: 'Browser rules for which sites may call your API; a config detail until it blocks launch day.', c: 'traffic' },
  { a: 'ACID', f: 'Atomicity, Consistency, Isolation, Durability', d: 'The transactional promise relational databases make - what wallets and orders are built on.', c: 'data' },
  { a: 'BASE', f: 'Basically Available, Soft state, Eventually consistent', d: 'The trade many NoSQL stores make: availability now, agreement shortly after.', c: 'data' },
  { a: 'CAP', f: 'Consistency, Availability, Partition tolerance', d: 'Under a network split you keep two; the studio treats partition tolerance as non-negotiable.', c: 'data' },
  { a: 'OLTP', f: 'Online Transaction Processing', d: 'Many small reads and writes with low latency - the shape of a product database.', c: 'data' },
  { a: 'OLAP', f: 'Online Analytical Processing', d: 'Few huge scans over history - the shape of a warehouse or ClickHouse-class store.', c: 'data' },
  { a: 'ETL', f: 'Extract, Transform, Load', d: 'Batch-moving data from product stores into analytical ones.', c: 'data' },
  { a: 'CDC', f: 'Change Data Capture', d: 'Tailing a databases own log to stream every change - ETL without the nightly batch.', c: 'data' },
  { a: 'WAL', f: 'Write-Ahead Log', d: 'The append-only log a database writes before touching data - the source of durability, replication and CDC.', c: 'data' },
  { a: 'MVCC', f: 'Multi-Version Concurrency Control', d: 'Readers see a snapshot while writers make new versions - why reads do not block writes in Postgres.', c: 'data' },
  { a: 'RDBMS', f: 'Relational Database Management System', d: 'Tables, SQL, transactions - the default until scale or shape argues otherwise.', c: 'data' },
  { a: 'KV', f: 'Key-Value', d: 'The simplest data model: one key, one blob - what caches and Dynamo-class stores speak.', c: 'data' },
  { a: 'GSI', f: 'Global Secondary Index', d: 'A second query path in a partitioned store, with its own capacity and its own hot spots.', c: 'data' },
  { a: 'LSM', f: 'Log-Structured Merge tree', d: 'Write-optimized storage: append to memory, flush sorted runs, compact later - Cassandra and RocksDB territory.', c: 'data' },
  { a: 'CQRS', f: 'Command Query Responsibility Segregation', d: 'Split the write model from read models so each side scales and evolves alone.', c: 'data' },
  { a: '2PC', f: 'Two-Phase Commit', d: 'A coordinator asks everyone to prepare, then commit - atomic across systems, fragile under failure; sagas usually win.', c: 'data' },
  { a: 'CRDT', f: 'Conflict-free Replicated Data Type', d: 'Data structures that merge concurrent edits without coordination - collaborative editing runs on them.', c: 'data' },
  { a: 'PITR', f: 'Point-In-Time Recovery', d: 'Restore a database to any moment, replayed from base backup plus WAL.', c: 'data' },
  { a: 'PII', f: 'Personally Identifiable Information', d: 'Data that names a person; where it lives decides your compliance blast radius.', c: 'data' },
  { a: 'MQ', f: 'Message Queue', d: 'A buffer between producer and consumer - absorbs bursts and survives consumer downtime.', c: 'messaging' },
  { a: 'DLQ', f: 'Dead Letter Queue', d: 'Where messages go after repeated failures - the difference between one poison message and a stuck pipeline.', c: 'messaging' },
  { a: 'FIFO', f: 'First In, First Out', d: 'Strict ordering in a queue; costs throughput because one slow message blocks its group.', c: 'messaging' },
  { a: 'EOS', f: 'Exactly-Once Semantics', d: 'Every event processed once despite retries - built from idempotency keys, not wishes.', c: 'messaging' },
  { a: 'ESB', f: 'Enterprise Service Bus', d: 'The centralized integration hub pattern; mostly replaced by dumb pipes and smart endpoints.', c: 'messaging' },
  { a: 'SLA', f: 'Service Level Agreement', d: 'The external promise with money attached when broken.', c: 'reliability' },
  { a: 'SLO', f: 'Service Level Objective', d: 'The internal target you engineer to - pick it on the SLO tab and see what it buys.', c: 'reliability' },
  { a: 'SLI', f: 'Service Level Indicator', d: 'The measured signal (success rate, p99) an SLO is judged against.', c: 'reliability' },
  { a: 'SRE', f: 'Site Reliability Engineering', d: 'Running production with engineering rigor: SLOs, error budgets, blameless postmortems.', c: 'reliability' },
  { a: 'PRR', f: 'Production Readiness Review', d: 'The gate before launch - the SLO tab runs one against your canvas.', c: 'reliability' },
  { a: 'MTTR', f: 'Mean Time To Recovery', d: 'How fast you heal; the metric chaos drills actually train.', c: 'reliability' },
  { a: 'MTBF', f: 'Mean Time Between Failures', d: 'How often things break; with MTTR it sets your real availability.', c: 'reliability' },
  { a: 'RTO', f: 'Recovery Time Objective', d: 'How long a disaster may keep you down before the plan has failed.', c: 'reliability' },
  { a: 'RPO', f: 'Recovery Point Objective', d: 'How much data a disaster may erase - the replication lag you can live with.', c: 'reliability' },
  { a: 'HA', f: 'High Availability', d: 'Surviving component failure without an outage: replicas, failover, no SPOF.', c: 'reliability' },
  { a: 'DR', f: 'Disaster Recovery', d: 'Surviving region-scale failure: another site, tested restores, honest RTO/RPO.', c: 'reliability' },
  { a: 'SPOF', f: 'Single Point Of Failure', d: 'The one box whose crash is an outage; the readiness review names yours.', c: 'reliability' },
  { a: 'HPA', f: 'Horizontal Pod Autoscaler', d: 'Kubernetes watching load and adding replicas - the +/- buttons, automated.', c: 'reliability' },
  { a: 'GC', f: 'Garbage Collection', d: 'Automatic memory cleanup whose pauses live in your p99 - one reason models and reality differ.', c: 'reliability' },
  { a: 'MTLS', f: 'Mutual TLS', d: 'Both sides prove identity with certificates - service-to-service trust inside the mesh.', c: 'security' },
  { a: 'WAF', f: 'Web Application Firewall', d: 'Pattern-matching shield at the edge for SQLi, XSS and bot floods.', c: 'security' },
  { a: 'IAM', f: 'Identity and Access Management', d: 'Who may do what, expressed as policy - least privilege lives here.', c: 'security' },
  { a: 'RBAC', f: 'Role-Based Access Control', d: 'Permissions attached to roles, roles to people - auditable authorization.', c: 'security' },
  { a: 'JWT', f: 'JSON Web Token', d: 'A signed, self-contained claim of identity; stateless to verify, awkward to revoke.', c: 'security' },
  { a: 'OAuth', f: 'Open Authorization', d: 'Delegated access - sign in with Google without handing over your password.', c: 'security' },
  { a: 'SSO', f: 'Single Sign-On', d: 'One identity provider, many apps; the enterprise checkbox that unlocks B2B deals.', c: 'security' },
  { a: 'AES', f: 'Advanced Encryption Standard', d: 'The symmetric cipher encrypting your data at rest and this studios admin page.', c: 'security' },
  { a: 'KMS', f: 'Key Management Service', d: 'Where encryption keys live, rotate and get audited - never in code.', c: 'security' },
  { a: 'E2EE', f: 'End-to-End Encryption', d: 'Only the endpoints can read; the server relays ciphertext it cannot open.', c: 'security' },
  { a: 'CVE', f: 'Common Vulnerabilities and Exposures', d: 'The public ID a security bug gets; patch cadence is measured against them.', c: 'security' },
  { a: 'XSS', f: 'Cross-Site Scripting', d: 'Injected script running in someone elses browser session.', c: 'security' },
  { a: 'CSRF', f: 'Cross-Site Request Forgery', d: 'Tricking a logged-in browser into an unwanted action - tokens defeat it.', c: 'security' },
  { a: 'DDoS', f: 'Distributed Denial of Service', d: 'A flood from many sources; absorbed at the edge or not at all.', c: 'security' },
  { a: 'K8s', f: 'Kubernetes', d: 'The container orchestrator - eight letters abbreviated because engineers are like that.', c: 'cloud' },
  { a: 'VPC', f: 'Virtual Private Cloud', d: 'Your own software-defined network inside a providers cloud.', c: 'cloud' },
  { a: 'VM', f: 'Virtual Machine', d: 'A whole computer, virtualized; heavier than containers, stronger isolation.', c: 'cloud' },
  { a: 'IaC', f: 'Infrastructure as Code', d: 'Terraform-style declared infrastructure - reviewable, repeatable, revertible.', c: 'cloud' },
  { a: 'CI/CD', f: 'Continuous Integration / Continuous Delivery', d: 'Every change built, tested and shipped by pipeline - this studio deploys through one.', c: 'cloud' },
  { a: 'S3', f: 'Simple Storage Service', d: 'The object store whose API became the industry standard for blobs.', c: 'cloud' },
  { a: 'GPU', f: 'Graphics Processing Unit', d: 'Thousands of small cores; the scarce resource under every LLM token.', c: 'cloud' },
  { a: 'CLI', f: 'Command-Line Interface', d: 'The keyboard-first way to drive a tool; where real operations happen.', c: 'cloud' },
  { a: 'DAU', f: 'Daily Active Users', d: 'People who showed up today - the consumer heartbeat metric.', c: 'business' },
  { a: 'WAU', f: 'Weekly Active Users', d: 'The first number this studio told its own founder to chase.', c: 'business' },
  { a: 'MAU', f: 'Monthly Active Users', d: 'The broadest activity net; easy to inflate, weak on its own.', c: 'business' },
  { a: 'ARPU', f: 'Average Revenue Per User', d: 'Revenue divided by users - how ads businesses are compared.', c: 'business' },
  { a: 'MRR', f: 'Monthly Recurring Revenue', d: 'Subscription revenue normalized to a month - the SaaS pulse.', c: 'business' },
  { a: 'ARR', f: 'Annual Recurring Revenue', d: 'MRR times twelve - the valuation number.', c: 'business' },
  { a: 'COGS', f: 'Cost Of Goods Sold', d: 'What serving the product costs; infra is the COGS line on the ROI tab.', c: 'business' },
  { a: 'ROI', f: 'Return On Investment', d: 'What you got back for what you spent - this studio prices it per million requests.', c: 'business' },
  { a: 'LTV', f: 'Lifetime Value', d: 'Total revenue one customer brings before churning.', c: 'business' },
  { a: 'CAC', f: 'Customer Acquisition Cost', d: 'What buying one customer costs; LTV/CAC decides if growth is a business.', c: 'business' },
  { a: 'GMV', f: 'Gross Merchandise Value', d: 'Everything sold through a marketplace - impressive, and not revenue.', c: 'business' },
  { a: 'LLM', f: 'Large Language Model', d: 'Token-in, token-out inference where latency scales with output length and GPUs set the cost floor.', c: 'ai' },
  { a: 'RAG', f: 'Retrieval-Augmented Generation', d: 'Fetch relevant documents, then let the model answer from them - grounding over guessing.', c: 'ai' },
  { a: 'ANN', f: 'Approximate Nearest Neighbor', d: 'Close-enough vector search at scale - exact is too slow past millions of embeddings.', c: 'ai' },
  { a: 'HNSW', f: 'Hierarchical Navigable Small World', d: 'The graph index behind most ANN search - fast, memory-hungry, recall-tunable.', c: 'ai' },
  { a: 'TTFT', f: 'Time To First Token', d: 'How long an LLM makes you wait before streaming starts - the perceived-speed metric.', c: 'ai' },
]
