import { toDesignJSON } from './integrity.js'
import { toMermaid, toExcalidraw } from './dac.js'
// Turns the live canvas into runnable artifacts — a docker-compose file, a
// Terraform skeleton for the selected cloud, and an OpenAPI contract for the
// service tiers. Everything is derived from nodes and edges on every render,
// which is the point: apply an Improve suggestion or a chaos Quick Fix and
// the code changes with the diagram. The design and the code cannot drift,
// because the code has no life of its own.
import { CATALOG } from './catalog.js'
import { serviceName } from './clouds.js'

const slug = s => String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'svc'

// Component type → how it appears in a compose file. Anything without an
// entry is either not a runnable container (client, cdn, dns) or a managed
// service, and is emitted as a comment instead of silently dropped.
const COMPOSE_IMAGES = {
  web: { image: 'nginx:alpine', ports: ['80:80'] },
  app: { image: 'node:20-alpine', command: 'node server.js', ports: ['3000:3000'] },
  micro: { image: 'node:20-alpine', command: 'node service.js' },
  grpc: { image: 'node:20-alpine', command: 'node grpc-server.js' },
  bff: { image: 'node:20-alpine', command: 'node bff.js', ports: ['4000:4000'] },
  ws: { image: 'node:20-alpine', command: 'node ws-server.js', ports: ['8080:8080'] },
  worker: { image: 'node:20-alpine', command: 'node worker.js' },
  lb: { image: 'haproxy:2.9-alpine', ports: ['443:443'] },
  gateway: { image: 'kong:3.6', ports: ['8000:8000'] },
  cache: { image: 'redis:7-alpine', ports: ['6379:6379'] },
  sql: { image: 'postgres:16-alpine', ports: ['5432:5432'], env: { POSTGRES_PASSWORD: 'change-me' } },
  nosql: { image: 'mongo:7', ports: ['27017:27017'] },
  search: { image: 'elasticsearch:8.13.0', env: { 'discovery.type': 'single-node' } },
  queue: { image: 'rabbitmq:3.13-management', ports: ['5672:5672'] },
  kafka: { image: 'bitnami/kafka:3.7', ports: ['9092:9092'] },
  mq: { image: 'rabbitmq:3.13-management' },
  vector: { image: 'qdrant/qdrant:v1.9.0', ports: ['6333:6333'] },
  monitor: { image: 'prom/prometheus:v2.51.0', ports: ['9090:9090'] },
  otel: { image: 'otel/opentelemetry-collector:0.98.0' },
  logs: { image: 'grafana/loki:2.9.6' },
  tracing: { image: 'jaegertracing/all-in-one:1.56', ports: ['16686:16686'] },
  registry: { image: 'consul:1.15', ports: ['8500:8500'] },
  config: { image: 'consul:1.15' },
  zk: { image: 'zookeeper:3.9' },
  gemmaos: { image: 'ollama/ollama:latest', command: 'ollama run gemma:7b', ports: ['11434:11434'] },
  llmobs: { image: 'langfuse/langfuse:2', ports: ['3001:3000'] },
  agentgraph: { image: 'node:20-alpine', command: 'node agent-graph.js' },
}

export function generateCompose(nodes, edges) {
  const runnable = nodes.filter(n => COMPOSE_IMAGES[n.type])
  const skipped = nodes.filter(n => !COMPOSE_IMAGES[n.type] && !CATALOG[n.type]?.source)
  const deps = {}
  for (const e of edges) (deps[e.from] ||= []).push(e.to)
  const nameOf = Object.fromEntries(nodes.map(n => [n.id, slug(n.label)]))

  const HEALTH = {
    sql: 'pg_isready -U postgres', cache: 'redis-cli ping', nosql: 'mongosh --quiet --eval "db.runCommand({ping:1})"',
    queue: 'rabbitmq-diagnostics -q ping', mq: 'rabbitmq-diagnostics -q ping',
  }
  const L = ['# Generated by ArchSim from the live canvas — edit the diagram, not this file.',
    '# Apply an Improve suggestion or a chaos Quick Fix and regenerate: the code follows the design.',
    'services:']
  for (const n of runnable) {
    const c = COMPOSE_IMAGES[n.type]
    L.push(`  ${nameOf[n.id]}:`)
    L.push(`    image: ${c.image}`)
    L.push(`    restart: unless-stopped`)
    if (c.command) L.push(`    command: ${c.command}`)
    if ((n.replicas || 1) > 1) {
      L.push(`    deploy:`)
      L.push(`      replicas: ${n.replicas}   # from the canvas — the Capacity tab sized this tier`)
    }
    if (c.ports && (n.replicas || 1) === 1) L.push(`    ports: [${c.ports.map(p => `"${p}"`).join(', ')}]`)
    if (c.env) { L.push('    environment:'); for (const [k, v] of Object.entries(c.env)) L.push(`      ${k}: ${v}`) }
    if (HEALTH[n.type]) {
      L.push(`    healthcheck:`)
      L.push(`      test: ["CMD-SHELL", "${HEALTH[n.type]}"]`)
      L.push(`      interval: 5s`)
      L.push(`      retries: 10`)
    }
    const dependsOn = (deps[n.id] || []).map(id => nameOf[id]).filter(m => runnable.some(r => nameOf[r.id] === m))
    if (dependsOn.length) L.push(`    depends_on: [${[...new Set(dependsOn)].join(', ')}]`)
  }
  if (skipped.length) {
    L.push('')
    L.push('# Not containers — these map to managed services (see the Terraform tab):')
    for (const n of skipped) L.push(`#   ${n.label} (${CATALOG[n.type]?.name || n.type})`)
  }
  return L.join('\n') + '\n'
}

// A Terraform skeleton naming the real managed service for each component on
// the selected cloud. Resource bodies are deliberately minimal — this is the
// shape of the deployment, not a copy-paste production stack.
const TF_PROVIDERS = {
  aws: { source: 'hashicorp/aws', block: 'provider "aws" {\n  region = var.region\n}' },
  gcp: { source: 'hashicorp/google', block: 'provider "google" {\n  project = var.project\n  region  = var.region\n}' },
  azure: { source: 'hashicorp/azurerm', block: 'provider "azurerm" {\n  features {}\n}' },
  oci: { source: 'oracle/oci', block: 'provider "oci" {\n  region = var.region\n}' },
}

export function generateTerraform(nodes, cloud) {
  const p = TF_PROVIDERS[cloud]
  if (!p) {
    return '# Pick a specific cloud (AWS, GCP, Azure or OCI) in the toolbar to generate\n# Terraform — "Generic" has no provider to target.\n'
  }
  const L = ['# Generated by ArchSim from the live canvas for ' + cloud.toUpperCase() + '.',
    '# Skeleton, not a production stack: names and counts are real, bodies are minimal.',
    '',
    'terraform {',
    '  required_providers {',
    `    ${cloud === 'gcp' ? 'google' : cloud === 'azure' ? 'azurerm' : cloud} = { source = "${p.source}" }`,
    '  }',
    '}',
    '',
    p.block,
    '']
  for (const n of nodes) {
    if (CATALOG[n.type]?.source) continue
    const svc = serviceName(n.type, cloud)
    const name = slug(n.label).replace(/-/g, '_')
    L.push(`# ${n.label} → ${svc || 'no mapped service'}${(n.replicas || 1) > 1 ? ` × ${n.replicas}` : ''}`)
    if (!svc || svc === 'no public equivalent' || svc === 'no equivalent') {
      L.push(`# (no ${cloud.toUpperCase()} equivalent — self-host or substitute)`)
      L.push('')
      continue
    }
    L.push(`module "${name}" {`)
    L.push(`  source   = "./modules/${slug(n.type)}"`)
    L.push(`  name     = "${slug(n.label)}"`)
    L.push(`  service  = "${svc}"`)
    if ((n.replicas || 1) > 1) L.push(`  replicas = ${n.replicas}`)
    L.push('}')
    L.push('')
  }
  return L.join('\n')
}

// One OpenAPI document covering the service tiers: each service node becomes
// a tagged path group, each downstream store it talks to becomes a resource.
const SERVICE_TYPES = new Set(['web', 'app', 'micro', 'grpc', 'bff', 'ws', 'gateway'])
const STORE_TYPES = new Set(['sql', 'nosql', 'cache', 'search', 'vector', 'blob'])

export function generateOpenAPI(nodes, edges) {
  const services = nodes.filter(n => SERVICE_TYPES.has(n.type))
  if (!services.length) {
    return '# Add a service tier (Web, App, Microservice, Gateway...) to the canvas\n# and its API contract will appear here.\n'
  }
  const byId = Object.fromEntries(nodes.map(n => [n.id, n]))
  const L = ['openapi: 3.0.3',
    'info:',
    '  title: Generated from the ArchSim canvas',
    '  description: One path group per service tier; resources inferred from the stores each service talks to.',
    '  version: 1.0.0',
    'paths:']
  for (const s of services) {
    const stores = edges.filter(e => e.from === s.id && STORE_TYPES.has(byId[e.to]?.type)).map(e => byId[e.to])
    const resources = stores.length ? stores : [{ label: 'items' }]
    for (const st of resources) {
      const r = slug(st.label)
      L.push(`  /${slug(s.label)}/${r}:`)
      L.push('    get:')
      L.push(`      tags: ["${s.label}"]`)
      L.push(`      summary: List ${r} (backed by ${st.type ? CATALOG[st.type]?.name || st.type : 'the service'})`)
      L.push('      responses: { "200": { description: OK } }')
      L.push('    post:')
      L.push(`      tags: ["${s.label}"]`)
      L.push(`      summary: Create in ${r}`)
      L.push('      responses: { "201": { description: Created } }')
    }
  }
  return L.join('\n') + '\n'
}

export const CODE_VIEWS = [
  { id: 'compose', label: 'docker-compose', file: 'docker-compose.yml', hint: 'Run the whole design locally — replicas and dependencies come from the canvas.' },
  { id: 'terraform', label: 'Terraform', file: 'main.tf', hint: 'The deployment shape on the selected cloud, one module per component.' },
  { id: 'openapi', label: 'OpenAPI', file: 'openapi.yaml', hint: 'API contract for the service tiers, resources inferred from their stores.' },
  { id: 'mermaid', label: 'Mermaid', file: 'architecture.mmd', hint: 'Diagram-as-code for READMEs — GitHub, Notion and Obsidian render it natively. Async edges are dashed; paste it back to simulate.' },
  { id: 'excalidraw', label: 'Excalidraw', file: 'architecture.excalidraw', hint: 'The interview whiteboard, pre-drawn: open the file at excalidraw.com and keep sketching.' },
  { id: 'json', label: 'ArchSim JSON', file: 'design.json', hint: 'The machine interface: a small, documented, versioned document an agent or script can read and write. Paste one back to simulate it.' },
  { id: 'k8s', label: 'Kubernetes', file: 'k8s.yaml', hint: 'Deployments, Services and an HPA for the service tiers - requests the scheduler reserves, limits the kernel enforces, probes so restarts are honest. Pairs with the k8s-resources drill.' },
]

export function generateCode(view, nodes, edges, cloud, rps = 100) {
  if (view === 'k8s') return generateK8s(nodes)
  if (view === 'json') return toDesignJSON(nodes, edges, rps)
  if (view === 'mermaid') return toMermaid(nodes, edges)
  if (view === 'excalidraw') return toExcalidraw(nodes, edges)
  if (view === 'terraform') return generateTerraform(nodes, cloud)
  if (view === 'openapi') return generateOpenAPI(nodes, edges)
  return generateCompose(nodes, edges)
}

const K8S_TYPES = new Set(['app', 'micro', 'gateway', 'fastapi', 'worker', 'ws', 'llmworker', 'embed', 'agentgraph', 'guard', 'grpc'])
export function generateK8s(nodes) {
  const svcs = nodes.filter(n => K8S_TYPES.has(n.type))
  if (!svcs.length) return '# No service tiers on the canvas - add an app, service, gateway or worker first.\n'
  const out = ['# Generated by ArchSim - the resource philosophy is the k8s-resources drill:',
    '# requests = what the scheduler RESERVES; limits = where the kernel KILLS (memory) or THROTTLES (CPU).',
    '# HPA scales on requests, so honest requests are the autoscaling contract.', '']
  const name = (n) => String(n.label || n.id).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || n.id
  for (const n of svcs) {
    const nm = name(n); const r = Math.max(1, n.replicas || 1)
    out.push(`---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${nm}
  labels: { app: ${nm}, archsim-type: ${n.type} }
spec:
  replicas: ${r}
  selector: { matchLabels: { app: ${nm} } }
  template:
    metadata: { labels: { app: ${nm} } }
    spec:
      containers:
        - name: ${nm}
          image: registry.example.com/${nm}:latest
          ports: [{ containerPort: 8080 }]
          resources:
            requests: { cpu: 250m, memory: 256Mi }   # measure the working set, then raise - the scheduler packs on THESE
            limits: { cpu: "1", memory: 512Mi }      # memory limit is a kill line, not a suggestion
          readinessProbe: { httpGet: { path: /healthz, port: 8080 }, periodSeconds: 5 }
          livenessProbe: { httpGet: { path: /healthz, port: 8080 }, initialDelaySeconds: 10, periodSeconds: 10 }
---
apiVersion: v1
kind: Service
metadata: { name: ${nm} }
spec:
  selector: { app: ${nm} }
  ports: [{ port: 80, targetPort: 8080 }]`)
  }
  const big = svcs.reduce((a, b) => ((b.replicas || 1) > (a.replicas || 1) ? b : a))
  out.push(`---
# HPA on the widest tier - scaling math runs on REQUESTS, which is why they must be honest
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: ${name(big)} }
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: ${name(big)} }
  minReplicas: ${Math.max(1, big.replicas || 1)}
  maxReplicas: ${Math.max(2, (big.replicas || 1) * 3)}
  metrics: [{ type: Resource, resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } } }]`)
  return out.join('\n') + '\n'
}
