// The thirty questions that recur in system design interviews.
//
// The questions themselves are the industry's common stock — every prep site
// lists roughly this set, and no one owns them. Every answer here is written
// for this tool. Where a question corresponds to a design in the library, it
// says so, because the thing ArchSim can do that a list of answers cannot is
// let you build the thing, push traffic through it and watch it break.

export const QUESTION_BANK = [
  { level: 'Foundations', q: 'What is consistent hashing, and why is it useful?',
    a: 'Servers are placed at points on a ring and a key lives on the first server clockwise from its own hash. Adding or removing a server moves only the keys between it and its neighbour, rather than remapping everything — which is the whole point, because a naive modulo of the server count reshuffles nearly all keys the moment the count changes. Virtual nodes fix the second problem: without them a handful of servers land unevenly on the ring and one takes far more than its share.',
    build: 'Set a store to hash partitioning and raise the key skew — the hotspot the advisor predicts is what consistent hashing does not solve.' },
  { level: 'Foundations', q: 'Vertical versus horizontal scaling?',
    a: 'Vertical means a bigger machine, horizontal means more of them. Vertical is far simpler and should not be dismissed — it has no coordination cost and one machine now holds an amount of RAM that would have been a cluster a decade ago. It ends at the largest instance available, and that machine is a single failure domain. Horizontal is unbounded and buys fault tolerance, and everything hard about distributed systems arrives with it.',
    build: 'Raise replicas on any tier in the inspector and watch capacity move, then note which findings only appear once there is more than one copy.' },
  { level: 'Foundations', q: 'What do load balancers do, and why?',
    a: 'They spread requests across a pool so no instance is the bottleneck, and remove failed instances from rotation. Round-robin is the default; least-connections is better when request cost varies widely. The thing worth saying in an interview is that a load balancer is itself a component that can fail, so it needs redundancy or a managed one — otherwise you have moved your single point of failure rather than removed it.',
    build: 'Every template has one. Kill it under Chaos and watch what the advisor says about single points of failure.' },
  { level: 'Foundations', q: 'Explain the CAP theorem.',
    a: 'During a network partition you must choose between refusing requests and serving possibly stale data. That is the whole theorem, and the common misreading is treating it as a menu of three from which you pick two — partition tolerance is not optional on a network, so the real choice is C or A, and only while partitioned. Most systems are neither purely CP nor AP but pick per operation: a payment refuses, a feed serves what it has.',
    build: 'Chaos → Split Brain on any multi-region design. Both halves stay up and cannot see each other; the design decides which one stops.' },
  { level: 'Foundations', q: 'What is caching, and where does a cache go?',
    a: 'Keeping a copy of something expensive somewhere cheap to reach. Browser, CDN, application memory, a shared cache, the database buffer pool — each is closer and smaller than the last. The interesting question is never where to put it but how it is invalidated, because a cache is a second copy of the truth and the design decides how long it may disagree.',
    build: 'Add a cache in front of a store and the advisor asks the invalidation question rather than congratulating you.' },
  { level: 'Foundations', q: 'What is a CDN, and when is one worth it?',
    a: 'Copies of static content held near users so a request travels tens of milliseconds instead of hundreds. Worth it for anything large and cacheable served to a geographically spread audience. Not a fix for a slow API — a CDN removes distance, not computation.',
    build: 'The Map tab shows why: a cross-region link carries a round-trip floor imposed by the speed of light, and no cache changes that for uncacheable work.' },
  { level: 'Foundations', q: 'What is sharding, and how does it help?',
    a: 'Splitting one dataset across several machines so each holds a slice. It buys write capacity, which replication does not. The whole design rests on the shard key: a good one keeps every query inside one shard, a bad one makes every query ask every shard and you have built a slower single machine.',
    build: 'Set a store to key-range partitioning and raise the skew — the predicted hotspot is what a bad shard key does.' },
  { level: 'Foundations', q: 'When would you choose SQL over NoSQL?',
    a: 'Ask what shape the queries are, not what shape the data is. Relational earns its place when you need joins across entities and transactions spanning rows. Document and wide-column stores earn theirs when access is by a known key at a scale one machine cannot hold. "NoSQL scales better" is too crude — a well-sharded relational store scales fine, and the real difference is what the database will do for you versus what you must do yourself.',
    build: 'Compare a template using a relational store with one using wide-column, and read both Breakdowns on why.' },
  { level: 'Foundations', q: 'Explain replication and its topologies.',
    a: 'Single-leader takes all writes in one place and streams them to followers: no conflicts, and followers can serve stale reads. Multi-leader accepts writes in several places and guarantees conflicts you must resolve. Leaderless writes to a quorum and is correct only when w + r > n. Single-leader is the default for good reason; the others buy availability and pay in conflict handling.',
    build: 'Set the mode on any datastore — the tool prices each one in throughput and latency, and flags what it costs you.' },
  { level: 'Foundations', q: 'Strong versus eventual consistency?',
    a: 'Strong means a read reflects every completed write, at the cost of coordination on the critical path — and during a partition, availability. Eventual means replicas converge at some unstated point. The useful framing is per operation: a balance check is strong, a follower count is eventual, and pretending one setting fits a whole system is how designs go wrong.',
    build: 'Set a store to linearizable and watch capacity drop and latency rise in the simulation. That is the cost, not a caveat.' },

  { level: 'Intermediate', q: 'How would you design a rate limiter?',
    a: 'Token bucket is the usual answer: tokens refill at a fixed rate, each request spends one, an empty bucket returns 429. It allows a controlled burst, which fixed windows do not. Distributed is where it gets interesting — a counter per instance is not a limit, so state goes in a shared store, and you must decide whether a brief overshoot during a race is acceptable. It almost always is.',
    build: 'Load the Rate Limiter template.' },
  { level: 'Intermediate', q: 'How do message queues help?',
    a: 'They decouple producer from consumer in time. The producer stops waiting, and a slow or dead consumer becomes a growing backlog rather than a failed request. That is also the trap: the queue absorbs the problem until it cannot, and an unbounded queue converts a fast failure into a slow one nobody notices until it is very large.',
    build: 'Set a queue role and delivery mode; the advisor asks whether the consumer is idempotent, which is where at-least-once actually lives.' },
  { level: 'Intermediate', q: 'How does a distributed lock work?',
    a: 'One holder at a time across many processes, usually a key with a TTL that only one writer can create. The hard part is not acquisition but the lease: a process that pauses for longer than its TTL wakes still believing it holds the lock, into a world that moved on. Anything that must be exclusive should re-check inside the transaction rather than trusting the lock alone.',
    build: 'Chaos → Process Pause on the lock holder in Ticketmaster. The node stays up the whole time, which is exactly why it is hard.' },
  { level: 'Intermediate', q: 'How do you prevent a cache stampede?',
    a: 'A popular key expires and every request that wanted it hits the database at once. Fixes: let one request rebuild while others serve the stale value, refresh early rather than on expiry, or take a short lock per key. The related failure is an avalanche, where many keys expire together — jitter the TTLs so they never line up.',
    build: 'Chaos → Cache Wipe. Every read falls through at once and you can see what that does to the store behind it.' },
  { level: 'Intermediate', q: 'Synchronous or asynchronous between services?',
    a: 'Synchronous is simple and couples availability: your caller is down whenever you are. Asynchronous is resilient and costs you the ability to answer "did it work" in the same breath. The rule that holds up: synchronous when the caller genuinely cannot proceed without the answer, asynchronous for everything else — and most things people make synchronous are not the former.',
    build: 'The flow filter separates the async path from the request path, so you can see how much of the design is off the critical path.' },
  { level: 'Intermediate', q: 'How do you migrate a schema without downtime?',
    a: 'Expand, migrate, contract. Add the new column, write both, backfill, move reads, then remove the old one — several deploys, each backward-compatible, because during a rolling deploy both versions run at once. Never rename in place. The discipline is that every intermediate state must be one both old and new code can live with.',
    build: 'Load the Strangler Migration template.' },
  { level: 'Intermediate', q: 'How would you design an API gateway?',
    a: 'One entry point handling authentication, rate limiting, routing and request shaping so services do not each reimplement them. The risks are that it becomes a single point of failure, and that it accretes business logic until it is a distributed monolith with a routing table. Keep it about cross-cutting concerns and nothing else.',
    build: 'Most templates have one. Give it an authentication method and the advisor stops asking who the users are.' },
  { level: 'Intermediate', q: 'What is a reverse proxy for?',
    a: 'It fronts your servers: terminating TLS, caching, compressing, load balancing, and hiding what is behind it. A forward proxy acts for the client, a reverse proxy for the server — that distinction is the question being asked.' },
  { level: 'Intermediate', q: 'How would you design logging and monitoring for microservices?',
    a: 'Structured logs shipped to one place, metrics separate from logs because they answer different questions, and traces to connect a request across services. The part people miss is cardinality: a label per user id will cost more than the system it monitors. Alert on symptoms users feel — error rate, latency — not on CPU.',
    build: 'Load the Observability: Golden Signals template.' },
  { level: 'Intermediate', q: 'How would you design a notification system?',
    a: 'Accept events on a queue so a slow provider never blocks the caller, then a worker per channel with its own retry and rate limits. Two things decide whether it is any good: idempotency, since retries will duplicate, and user preferences, since the fastest way to be marked spam is ignoring them.',
    build: 'Load the Notification System template.' },

  { level: 'Advanced', q: 'How would you design collaborative editing?',
    a: 'Two edits arriving in different orders must converge to the same document. Operational transformation rewrites operations against concurrent ones; CRDTs design the data type so order stops mattering. CRDTs are easier to reason about and cost more metadata. Transport is a persistent connection, and the server is mostly a broadcaster and a durable log.',
    build: 'Load the Collab Docs template.' },
  { level: 'Advanced', q: 'How would you design a URL shortener?',
    a: 'Base62 of a counter gives short, unique, dense keys and leaks how many links exist; a hash avoids that and needs collision handling. It is read-dominated by roughly a hundred to one, so it is really a cache design. The trade-off worth raising unprompted: 301 caches in the browser and loses your analytics, 302 keeps them and costs you a round trip every time.',
    build: 'Load the URL Shortener template.' },
  { level: 'Advanced', q: 'How would you design a social feed?',
    a: 'Fan-out on write precomputes each follower\'s timeline: fast reads, and unworkable for an account with fifty million followers. Fan-out on read assembles at request time: cheap writes, expensive reads. Every real system does both — precompute for ordinary accounts, merge celebrity posts at read time.',
    build: 'Load the News Feed templates — Twitter/X and Instagram take different sides of this.' },
  { level: 'Advanced', q: 'How would you design search autocomplete?',
    a: 'A trie over prefixes with the top completions precomputed at each node, so a keystroke is a lookup rather than a search. Serve from memory, rebuild offline from query logs, and debounce on the client. Typo tolerance is a separate problem and worth saying you would defer.',
    build: 'Load the Search Autocomplete template.' },
  { level: 'Advanced', q: 'How would you design payments?',
    a: 'Idempotency keys on every mutating call, because the network will make a client retry a charge that already succeeded. Money moves through explicit states with an append-only ledger rather than a mutable balance. Never hold a payment provider call inside a database transaction. And say plainly which parts are in PCI scope, since that shapes the architecture more than throughput does.',
    build: 'Load the Payment System template, and Razorpay or BHIM for the Indian rails.' },
  { level: 'Advanced', q: 'How would you design e-commerce checkout?',
    a: 'Reserve stock before payment with a short expiry, so a lingering cart cannot hold inventory forever. Across services this is a saga with explicit compensation, not a distributed transaction — the compensating action for a captured payment is a refund, and that has to be designed rather than assumed.',
    build: 'Load the E-commerce Saga template.' },
  { level: 'Advanced', q: 'How would you design a chat system?',
    a: 'Persistent connections, a connection registry mapping user to server, and a fan-out path for groups. Ordering is per conversation, not global. Delivery receipts are a second write path people forget to design. At-least-once plus a client-generated message id gives you dedupe without exactly-once.',
    build: 'Load the Chat (WhatsApp) template.' },
  { level: 'Advanced', q: 'How would you design recommendations?',
    a: 'Candidate generation then ranking: cheap retrieval of a few hundred plausible items, then an expensive model over those. Trained offline in batch, served from a feature store with real-time signals layered on. The cold-start answer matters — popularity and content similarity until there is behaviour to learn from.',
    build: 'Load the ML: Recommendation Ranking template.' },
  { level: 'Advanced', q: 'How would you design video streaming?',
    a: 'Transcode once into a ladder of bitrates, segment it, and let the client choose per segment via HLS or DASH. Almost all delivery is CDN; your origin should see very little. Upload and transcode are an async pipeline where jobs fail and retry, and that pipeline is usually the interesting half.',
    build: 'Load the Video Platform (YouTube) or Netflix templates.' },
  { level: 'Advanced', q: 'How would you design ridesharing?',
    a: 'Geospatial index over driver locations — geohash or H3 — updated every few seconds, which is a heavy sustained write load. Matching reads a small cell neighbourhood rather than searching globally. Shard by city, because rides are local and that keeps every query inside one shard.',
    build: 'Load the Ride Sharing (Uber) template, or Rapido for the Indian market.' },
]

export const QUESTION_LEVELS = ['Foundations', 'Intermediate', 'Advanced']
export const questionsAt = level => QUESTION_BANK.filter(q => q.level === level)
