// Full system code, generated from the canvas graph. Not descriptors — actual
// runnable Node.js services: an Express server per service tier, whose routes,
// data access and messaging are derived from what that node is wired to.
//
// The derivations are the point:
//   service → sql only            = direct queries
//   service → cache AND → sql     = cache-aside reads, invalidate on write
//   service → queue/kafka         = a producer endpoint
//   queue/kafka → worker          = a consumer loop in that worker
//   service → (embed) → vector → llm = a RAG /ask endpoint
//   ws service                    = a WebSocket server
//
// Apply an Improve suggestion that splices a cache in front of the database
// and the data layer in the generated code switches from direct queries to
// cache-aside — the same edit, expressed as code.
import { CATALOG } from './catalog.js'

const slug = s => String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'svc'
const varName = s => slug(s).replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())

const SERVICE_TYPES = new Set(['web', 'app', 'micro', 'grpc', 'bff', 'gateway', 'ws'])
const LLM_TYPES = new Set(['llm', 'gemini3', 'gemini2', 'gemmaos', 'aiagent'])
const QUEUE_TYPES = new Set(['queue', 'mq'])

function wiring(nodes, edges) {
  const byId = Object.fromEntries(nodes.map(n => [n.id, n]))
  const out = id => edges.filter(e => e.from === id).map(e => byId[e.to]).filter(Boolean)
  const into = id => edges.filter(e => e.to === id).map(e => byId[e.from]).filter(Boolean)
  return { byId, out, into }
}

// ── per-service server ─────────────────────────────────────────────────────
function serverFile(svc, w) {
  const targets = w.out(svc.id)
  const cache = targets.find(t => t.type === 'cache')
  const sql = targets.find(t => t.type === 'sql')
  const nosql = targets.find(t => t.type === 'nosql')
  const queue = targets.find(t => QUEUE_TYPES.has(t.type))
  const kafka = targets.find(t => t.type === 'kafka')
  const vector = targets.find(t => t.type === 'vector')
  const llm = targets.find(t => LLM_TYPES.has(t.type))
  const isWs = svc.type === 'ws'
  const resource = sql ? slug(sql.label) : nosql ? slug(nosql.label) : 'items'
  const table = varName(resource)

  const L = []
  L.push(`// ${svc.label} — generated by ArchSim from the canvas.`)
  L.push(`// Wired to: ${targets.map(t => `${t.label} (${t.type})`).join(', ') || 'nothing downstream'}.`)
  L.push(`import express from 'express'`)
  if (isWs) L.push(`import { WebSocketServer } from 'ws'`)
  if (cache) L.push(`import { createClient } from 'redis'`)
  if (sql) L.push(`import pg from 'pg'`)
  if (nosql) L.push(`import { MongoClient } from 'mongodb'`)
  if (queue) L.push(`import amqp from 'amqplib'`)
  if (kafka) L.push(`import { Kafka } from 'kafkajs'`)
  L.push('')
  L.push(`const app = express()`)
  L.push(`app.use(express.json())`)
  L.push('')
  if (cache) {
    L.push(`// ${cache.label}: cache-aside — reads try the cache first, misses fall`)
    L.push(`// through to the store and populate; writes invalidate.`)
    L.push(`const cache = createClient({ url: process.env.REDIS_URL || 'redis://${slug(cache.label)}:6379' })`)
    L.push(`await cache.connect()`)
    L.push(`const TTL = 300 // seconds — tune against your staleness budget`)
    L.push('')
  }
  if (sql) {
    L.push(`const db = new pg.Pool({ connectionString: process.env.DATABASE_URL || 'postgres://postgres:change-me@${slug(sql.label)}:5432/postgres' })`)
    L.push('')
  }
  if (nosql) {
    L.push(`const mongo = await MongoClient.connect(process.env.MONGO_URL || 'mongodb://${slug(nosql.label)}:27017')`)
    L.push(`const col = mongo.db('app').collection('${resource}')`)
    L.push('')
  }
  if (queue) {
    L.push(`// ${queue.label}: work leaves the request path here — the caller gets 202`)
    L.push(`// and a consumer (see the worker service) does the rest.`)
    L.push(`const mq = await amqp.connect(process.env.AMQP_URL || 'amqp://${slug(queue.label)}:5672')`)
    L.push(`const ch = await mq.createChannel()`)
    L.push(`await ch.assertQueue('jobs', { durable: true })`)
    L.push('')
  }
  if (kafka) {
    L.push(`const kafka = new Kafka({ brokers: [process.env.KAFKA_BROKER || '${slug(kafka.label)}:9092'] })`)
    L.push(`const producer = kafka.producer()`)
    L.push(`await producer.connect()`)
    L.push('')
  }

  L.push(`app.get('/health', (_req, res) => res.json({ ok: true, service: '${slug(svc.label)}' }))`)
  L.push('')

  if (sql || nosql) {
    L.push(`app.get('/${resource}/:id', async (req, res) => {`)
    if (cache) {
      L.push(`  const key = '${resource}:' + req.params.id`)
      L.push(`  const hit = await cache.get(key)`)
      L.push(`  if (hit) return res.json(JSON.parse(hit))          // cache hit — the store never sees this read`)
    }
    if (sql) {
      L.push(`  const { rows } = await db.query('SELECT * FROM ${table} WHERE id = $1', [req.params.id])`)
      L.push(`  if (!rows.length) return res.status(404).json({ error: 'not found' })`)
      L.push(`  const item = rows[0]`)
    } else {
      L.push(`  const item = await col.findOne({ _id: req.params.id })`)
      L.push(`  if (!item) return res.status(404).json({ error: 'not found' })`)
    }
    if (cache) L.push(`  await cache.set(key, JSON.stringify(item), { EX: TTL })  // populate on miss`)
    L.push(`  res.json(item)`)
    L.push(`})`)
    L.push('')
    L.push(`app.post('/${resource}', async (req, res) => {`)
    if (sql) {
      L.push(`  const { rows } = await db.query(`)
      L.push(`    'INSERT INTO ${table} (data) VALUES ($1) RETURNING *', [req.body])`)
      L.push(`  const item = rows[0]`)
    } else {
      L.push(`  const item = { _id: crypto.randomUUID(), ...req.body }`)
      L.push(`  await col.insertOne(item)`)
    }
    if (cache) L.push(`  await cache.del('${resource}:' + item.id)  // invalidate — never write stale data around the store`)
    L.push(`  res.status(201).json(item)`)
    L.push(`})`)
    L.push('')
  }

  if (queue) {
    L.push(`app.post('/jobs', async (req, res) => {`)
    L.push(`  ch.sendToQueue('jobs', Buffer.from(JSON.stringify(req.body)), { persistent: true })`)
    L.push(`  res.status(202).json({ queued: true })   // accepted, not done — that is the contract`)
    L.push(`})`)
    L.push('')
  }
  if (kafka) {
    L.push(`app.post('/events', async (req, res) => {`)
    L.push(`  await producer.send({ topic: 'events', messages: [{ value: JSON.stringify(req.body) }] })`)
    L.push(`  res.status(202).json({ published: true })`)
    L.push(`})`)
    L.push('')
  }

  if (llm) {
    L.push(`// ${llm.label}${vector ? ` with ${vector.label}` : ''}: ${vector ? 'retrieval-augmented generation — embed the question, fetch the nearest chunks, ground the prompt' : 'direct inference'}.`)
    L.push(`app.post('/ask', async (req, res) => {`)
    L.push(`  const question = String(req.body.question || '')`)
    if (vector) {
      L.push(`  const emb = await fetch(process.env.EMBED_URL + '/embed', {`)
      L.push(`    method: 'POST', headers: { 'content-type': 'application/json' },`)
      L.push(`    body: JSON.stringify({ text: question }) }).then(r => r.json())`)
      L.push(`  const near = await fetch((process.env.VECTOR_URL || 'http://${slug(vector.label)}:6333') + '/collections/docs/points/search', {`)
      L.push(`    method: 'POST', headers: { 'content-type': 'application/json' },`)
      L.push(`    body: JSON.stringify({ vector: emb.vector, limit: 5 }) }).then(r => r.json())`)
      L.push(`  const context = (near.result || []).map(p => p.payload?.text).join('\\n')`)
    }
    L.push(`  const answer = await fetch(process.env.LLM_URL || 'http://${slug(llm.label)}:11434/api/generate', {`)
    L.push(`    method: 'POST', headers: { 'content-type': 'application/json' },`)
    L.push(`    body: JSON.stringify({ model: process.env.LLM_MODEL || 'gemma:7b',`)
    L.push(`      prompt: ${vector ? '`Answer from this context only:\\n${context}\\n\\nQ: ${question}`' : 'question'}, stream: false }) }).then(r => r.json())`)
    L.push(`  res.json({ answer: answer.response })`)
    L.push(`})`)
    L.push('')
  }

  if (isWs) {
    L.push(`const server = app.listen(process.env.PORT || 8080, () =>`)
    L.push(`  console.log('${svc.label} listening (http + ws)'))`)
    L.push(`const wss = new WebSocketServer({ server })`)
    L.push(`wss.on('connection', ws => {`)
    L.push(`  ws.on('message', msg => {`)
    L.push(`    // Frames travel both directions for the socket's lifetime —`)
    L.push(`    // the two-way arrow on the canvas is this loop.`)
    L.push(`    for (const client of wss.clients) if (client.readyState === 1) client.send(msg.toString())`)
    L.push(`  })`)
    L.push(`})`)
  } else {
    L.push(`app.listen(process.env.PORT || 3000, () =>`)
    L.push(`  console.log('${svc.label} listening on ' + (process.env.PORT || 3000)))`)
  }
  return L.join('\n') + '\n'
}

// ── worker: consumes whatever feeds it ─────────────────────────────────────
function workerFile(wk, w) {
  const feeds = w.into(wk.id)
  const queue = feeds.find(t => QUEUE_TYPES.has(t.type))
  const kafka = feeds.find(t => t.type === 'kafka')
  const targets = w.out(wk.id)
  const sql = targets.find(t => t.type === 'sql')
  const L = []
  L.push(`// ${wk.label} — generated by ArchSim from the canvas.`)
  L.push(`// Consumes: ${[queue, kafka].filter(Boolean).map(t => t.label).join(', ') || 'nothing — wire a queue or stream into this worker'}.`)
  if (queue) {
    L.push(`import amqp from 'amqplib'`)
    if (sql) L.push(`import pg from 'pg'`)
    L.push('')
    if (sql) L.push(`const db = new pg.Pool({ connectionString: process.env.DATABASE_URL || 'postgres://postgres:change-me@${slug(sql.label)}:5432/postgres' })`)
    L.push(`const mq = await amqp.connect(process.env.AMQP_URL || 'amqp://${slug(queue.label)}:5672')`)
    L.push(`const ch = await mq.createChannel()`)
    L.push(`await ch.assertQueue('jobs', { durable: true })`)
    L.push(`ch.prefetch(10)   // at most 10 unacked jobs in flight per worker`)
    L.push('')
    L.push(`ch.consume('jobs', async msg => {`)
    L.push(`  if (!msg) return`)
    L.push(`  try {`)
    L.push(`    const job = JSON.parse(msg.content.toString())`)
    if (sql) L.push(`    await db.query('INSERT INTO results (data) VALUES ($1)', [job])`)
    else L.push(`    console.log('processing', job)`)
    L.push(`    ch.ack(msg)                      // ack only after the work is durable`)
    L.push(`  } catch (err) {`)
    L.push(`    console.error('job failed', err)`)
    L.push(`    ch.nack(msg, false, false)       // dead-letter, do not requeue a poison pill`)
    L.push(`  }`)
    L.push(`})`)
  } else if (kafka) {
    L.push(`import { Kafka } from 'kafkajs'`)
    L.push('')
    L.push(`const kafka = new Kafka({ brokers: [process.env.KAFKA_BROKER || '${slug(kafka.label)}:9092'] })`)
    L.push(`const consumer = kafka.consumer({ groupId: '${slug(wk.label)}' })`)
    L.push(`await consumer.connect()`)
    L.push(`await consumer.subscribe({ topic: 'events', fromBeginning: false })`)
    L.push(`await consumer.run({`)
    L.push(`  eachMessage: async ({ message }) => {`)
    L.push(`    console.log('event', JSON.parse(message.value.toString()))`)
    L.push(`  },`)
    L.push(`})`)
  } else {
    L.push('')
    L.push(`console.log('${wk.label}: nothing feeds this worker yet — draw an edge from a queue or stream to it.')`)
  }
  return L.join('\n') + '\n'
}

// ── the whole project ──────────────────────────────────────────────────────
export function generateProject(nodes, edges) {
  const w = wiring(nodes, edges)
  const services = nodes.filter(n => SERVICE_TYPES.has(n.type))
  const workers = nodes.filter(n => n.type === 'worker')
  const sqls = nodes.filter(n => n.type === 'sql')
  const files = []

  if (!services.length && !workers.length) {
    return [{ path: 'README.md', content: '# Nothing to generate yet\n\nAdd a service tier (Web, App, Microservice, WebSocket...) or a worker to the canvas and the full system code will appear here.\n' }]
  }

  // Which npm packages this design actually needs — derived, like everything.
  const deps = { express: '^4.19.0' }
  for (const s of [...services, ...workers]) {
    const t = [...w.out(s.id), ...w.into(s.id)]
    if (t.some(x => x.type === 'cache')) deps.redis = '^4.6.0'
    if (t.some(x => x.type === 'sql')) deps.pg = '^8.11.0'
    if (t.some(x => x.type === 'nosql')) deps.mongodb = '^6.5.0'
    if (t.some(x => QUEUE_TYPES.has(x.type))) deps.amqplib = '^0.10.0'
    if (t.some(x => x.type === 'kafka')) deps.kafkajs = '^2.2.0'
    if (s.type === 'ws') deps.ws = '^8.16.0'
  }

  files.push({
    path: 'package.json',
    content: JSON.stringify({
      name: 'archsim-generated-system',
      private: true,
      type: 'module',
      scripts: Object.fromEntries([
        ...services.map(s => [`start:${slug(s.label)}`, `node services/${slug(s.label)}/server.js`]),
        ...workers.map(k => [`start:${slug(k.label)}`, `node services/${slug(k.label)}/worker.js`]),
      ]),
      dependencies: deps,
    }, null, 2) + '\n',
  })

  files.push({
    path: 'README.md',
    content: [
      '# Generated system — ArchSim',
      '',
      'Every file here is derived from the canvas: routes from the edges, cache-aside',
      'from a cache in front of a store, producers and consumers from the queues,',
      'replica counts in docker-compose from the Capacity tab. Change the diagram',
      '(or apply an ✨ Improve suggestion) and regenerate — the code follows.',
      '',
      '## Run it',
      '```bash',
      'docker compose up -d     # infrastructure (see the docker-compose tab)',
      'npm install',
      ...services.map(s => `npm run start:${slug(s.label)}`),
      ...workers.map(k => `npm run start:${slug(k.label)}`),
      '```',
      '',
      '## Services',
      ...services.map(s => `- **${s.label}** (\`services/${slug(s.label)}/server.js\`) → ${w.out(s.id).map(t => t.label).join(', ') || 'no downstream'}`),
      ...workers.map(k => `- **${k.label}** (\`services/${slug(k.label)}/worker.js\`) ← ${w.into(k.id).map(t => t.label).join(', ') || 'nothing yet'}`),
      '',
    ].join('\n') + '\n',
  })

  const envLines = ['# Connection strings — hostnames match the docker-compose service names.']
  for (const n of nodes) {
    if (n.type === 'cache') envLines.push(`REDIS_URL=redis://${slug(n.label)}:6379`)
    if (n.type === 'sql') envLines.push(`DATABASE_URL=postgres://postgres:change-me@${slug(n.label)}:5432/postgres`)
    if (n.type === 'nosql') envLines.push(`MONGO_URL=mongodb://${slug(n.label)}:27017`)
    if (QUEUE_TYPES.has(n.type)) envLines.push(`AMQP_URL=amqp://${slug(n.label)}:5672`)
    if (n.type === 'kafka') envLines.push(`KAFKA_BROKER=${slug(n.label)}:9092`)
    if (n.type === 'vector') envLines.push(`VECTOR_URL=http://${slug(n.label)}:6333`)
    if (LLM_TYPES.has(n.type)) envLines.push(`LLM_URL=http://${slug(n.label)}:11434/api/generate`)
  }
  files.push({ path: '.env.example', content: envLines.join('\n') + '\n' })

  if (sqls.length) {
    files.push({
      path: 'db/schema.sql',
      content: sqls.map(s => {
        const t = varName(slug(s.label))
        return [`-- ${s.label}`,
          `CREATE TABLE IF NOT EXISTS ${t} (`,
          `  id BIGSERIAL PRIMARY KEY,`,
          `  data JSONB NOT NULL,`,
          `  created_at TIMESTAMPTZ NOT NULL DEFAULT now()`,
          `);`,
          `CREATE INDEX IF NOT EXISTS ${t}_created_idx ON ${t} (created_at);`, ''].join('\n')
      }).join('\n') + 'CREATE TABLE IF NOT EXISTS results (\n  id BIGSERIAL PRIMARY KEY,\n  data JSONB NOT NULL\n);\n',
    })
  }

  for (const s of services) files.push({ path: `services/${slug(s.label)}/server.js`, content: serverFile(s, w) })
  for (const k of workers) files.push({ path: `services/${slug(k.label)}/worker.js`, content: workerFile(k, w) })

  return files
}
