// Full system code, generated from the canvas graph. Not descriptors — actual
// runnable Node.js services: an Express server per service tier, whose routes,
// data access and messaging are derived from what that node is wired to.
//
// The derivations are the point:
//   service → sql only            = direct queries
//   service → cache AND → sql     = cache-aside reads, invalidate on write
//   service → queue/kafka         = a producer endpoint
//   queue/kafka → worker          = a consumer loop in that worker
//   service → (embed) → vector → llm = a RAG /ask endpoint
//   ws service                    = a WebSocket server
//
// Apply an Improve suggestion that splices a cache in front of the database
// and the data layer in the generated code switches from direct queries to
// cache-aside — the same edit, expressed as code.
import { CATALOG } from './catalog.js'

const slug = s => String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'svc'
const varName = s => slug(s).replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())

const SERVICE_TYPES = new Set(['web', 'app', 'micro', 'grpc', 'bff', 'gateway', 'ws'])
const LLM_TYPES = new Set(['llm', 'gemini3', 'gemini2', 'gemmaos', 'aiagent'])
const QUEUE_TYPES = new Set(['queue', 'mq'])

function wiring(nodes, edges) {
  const byId = Object.fromEntries(nodes.map(n => [n.id, n]))
  const out = id => edges.filter(e => e.from === id).map(e => byId[e.to]).filter(Boolean)
  const into = id => edges.filter(e => e.to === id).map(e => byId[e.from]).filter(Boolean)
  return { byId, out, into }
}

// ── per-service server ─────────────────────────────────────────────────────
function serverFile(svc, w) {
  const targets = w.out(svc.id)
  const cache = targets.find(t => t.type === 'cache')
  const sql = targets.find(t => t.type === 'sql')
  const nosql = targets.find(t => t.type === 'nosql')
  const queue = targets.find(t => QUEUE_TYPES.has(t.type))
  const kafka = targets.find(t => t.type === 'kafka')
  const vector = targets.find(t => t.type === 'vector')
  const llm = targets.find(t => LLM_TYPES.has(t.type))
  const isWs = svc.type === 'ws'
  const resource = sql ? slug(sql.label) : nosql ? slug(nosql.label) : 'items'
  const table = varName(resource)
  const name = slug(svc.label)

  const L = []
  L.push(`// ${svc.label} — generated by ArchSim from the canvas.`)
  L.push(`// Wired to: ${targets.map(t => `${t.label} (${t.type})`).join(', ') || 'nothing downstream'}.`)
  L.push(`import express from 'express'`)
  if (isWs) L.push(`import { WebSocketServer } from 'ws'`)
  if (cache) L.push(`import { createClient } from 'redis'`)
  if (sql) L.push(`import pg from 'pg'`)
  if (nosql) L.push(`import { MongoClient } from 'mongodb'`)
  if (queue) L.push(`import amqp from 'amqplib'`)
  if (kafka) L.push(`import { Kafka } from 'kafkajs'`)
  L.push('')
  L.push(`// Structured JSON logs — one line per event, no logging dependency.`)
  L.push(`const log = (level, msg, extra = {}) =>`)
  L.push(`  console.log(JSON.stringify({ ts: new Date().toISOString(), level, service: '${name}', msg, ...extra }))`)
  L.push('')
  L.push(`// Dependencies come up in their own time — retry with backoff instead of`)
  L.push(`// crash-looping the container while postgres finishes its first boot.`)
  L.push(`async function withRetry(what, fn, attempts = 8) {`)
  L.push(`  for (let i = 1; ; i++) {`)
  L.push(`    try { return await fn() } catch (err) {`)
  L.push(`      if (i >= attempts) throw err`)
  L.push(`      const wait = Math.min(15000, 250 * 2 ** i)`)
  L.push(`      log('warn', what + ' not ready, retrying', { attempt: i, wait, err: err.message })`)
  L.push(`      await new Promise(r => setTimeout(r, wait))`)
  L.push(`    }`)
  L.push(`  }`)
  L.push(`}`)
  L.push('')
  L.push(`const app = express()`)
  L.push(`app.disable('x-powered-by')`)
  L.push(`app.use(express.json({ limit: '1mb' }))   // bound the request body — an unbounded parser is a DoS invitation`)
  L.push(`app.use((req, res, next) => {              // access log with latency`)
  L.push(`  const t0 = Date.now()`)
  L.push(`  res.on('finish', () => log('info', 'req', { m: req.method, p: req.path, s: res.statusCode, ms: Date.now() - t0 }))`)
  L.push(`  next()`)
  L.push(`})`)
  L.push(`// Route bodies are async — one wrapper routes every rejection to the`)
  L.push(`// error middleware instead of leaving an unhandled rejection to kill us.`)
  L.push(`const h = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next)`)
  L.push(`const ID = /^[\\w-]{1,64}$/                 // ids are opaque tokens, not free text`)
  L.push('')
  if (cache) {
    L.push(`// ${cache.label}: cache-aside — reads try the cache first, misses fall`)
    L.push(`// through to the store and populate; writes invalidate.`)
    L.push(`const cache = createClient({ url: process.env.REDIS_URL || 'redis://${slug(cache.label)}:6379' })`)
    L.push(`cache.on('error', err => log('error', 'redis', { err: err.message }))  // without this listener one blip kills the process`)
    L.push(`await withRetry('redis', () => cache.connect())`)
    L.push(`const TTL = 300`)
    L.push(`const jitteredTTL = () => TTL + Math.floor(Math.random() * 60)  // spread expiries so hot keys don't stampede the store together`)
    L.push('')
  }
  if (sql) {
    L.push(`const db = new pg.Pool({`)
    L.push(`  connectionString: process.env.DATABASE_URL || 'postgres://postgres:change-me@${slug(sql.label)}:5432/postgres',`)
    L.push(`  max: Number(process.env.PG_POOL_MAX || 10),`)
    L.push(`  statement_timeout: 5000,                 // a query that runs forever holds a connection forever`)
    L.push(`  connectionTimeoutMillis: 5000,`)
    L.push(`})`)
    L.push(`db.on('error', err => log('error', 'pg pool', { err: err.message }))`)
    L.push(`await withRetry('postgres', () => db.query('SELECT 1'))`)
    L.push('')
  }
  if (nosql) {
    L.push(`const mongo = await withRetry('mongo', () => MongoClient.connect(process.env.MONGO_URL || 'mongodb://${slug(nosql.label)}:27017', { serverSelectionTimeoutMS: 5000 }))`)
    L.push(`const col = mongo.db('app').collection('${resource}')`)
    L.push('')
  }
  if (queue) {
    L.push(`// ${queue.label}: work leaves the request path here — the caller gets 202`)
    L.push(`// and a consumer (see the worker service) does the rest.`)
    L.push(`const mq = await withRetry('rabbitmq', () => amqp.connect(process.env.AMQP_URL || 'amqp://${slug(queue.label)}:5672'))`)
    L.push(`mq.on('error', err => log('error', 'amqp', { err: err.message }))`)
    L.push(`const ch = await mq.createChannel()`)
    L.push(`await ch.assertQueue('jobs', { durable: true })`)
    L.push('')
  }
  if (kafka) {
    L.push(`const kafka = new Kafka({ brokers: [process.env.KAFKA_BROKER || '${slug(kafka.label)}:9092'] })`)
    L.push(`const producer = kafka.producer()`)
    L.push(`await withRetry('kafka', () => producer.connect())`)
    L.push('')
  }

  L.push(`app.get('/health', (_req, res) => res.json({ ok: true, service: '${name}' }))  // liveness: the process is up`)
  L.push(`app.get('/ready', h(async (_req, res) => {   // readiness: the dependencies answer — route traffic on this, not on /health`)
  const readyChecks = []
  if (cache) readyChecks.push(`cache.ping()`)
  if (sql) readyChecks.push(`db.query('SELECT 1')`)
  if (nosql) readyChecks.push(`col.estimatedDocumentCount()`)
  if (queue) readyChecks.push(`ch.checkQueue('jobs')`)
  if (readyChecks.length) {
    L.push(`  try { await Promise.all([${readyChecks.join(', ')}]) }`)
    L.push(`  catch (err) { return res.status(503).json({ ready: false, err: err.message }) }`)
  }
  L.push(`  res.json({ ready: true })`)
  L.push(`}))`)
  L.push('')

  if (sql || nosql) {
    L.push(`app.get('/${resource}/:id', h(async (req, res) => {`)
    L.push(`  if (!ID.test(req.params.id)) return res.status(400).json({ error: 'invalid id' })`)
    if (cache) {
      L.push(`  const key = '${resource}:' + req.params.id`)
      L.push(`  try {`)
      L.push(`    const hit = await cache.get(key)`)
      L.push(`    if (hit) return res.json(JSON.parse(hit))   // cache hit — the store never sees this read`)
      L.push(`  } catch (err) { log('warn', 'cache read failed, falling through', { err: err.message }) }  // a broken cache degrades, never breaks, reads`)
    }
    if (sql) {
      L.push(`  const { rows } = await db.query('SELECT * FROM ${table} WHERE id = $1', [req.params.id])`)
      L.push(`  if (!rows.length) return res.status(404).json({ error: 'not found' })`)
      L.push(`  const item = rows[0]`)
    } else {
      L.push(`  const item = await col.findOne({ _id: req.params.id })`)
      L.push(`  if (!item) return res.status(404).json({ error: 'not found' })`)
    }
    if (cache) L.push(`  cache.set(key, JSON.stringify(item), { EX: jitteredTTL() }).catch(() => {})  // populate on miss, best-effort`)
    L.push(`  res.json(item)`)
    L.push(`}))`)
    L.push('')
    L.push(`app.post('/${resource}', h(async (req, res) => {`)
    L.push(`  if (!req.body || typeof req.body !== 'object' || Array.isArray(req.body) || !Object.keys(req.body).length)`)
    L.push(`    return res.status(400).json({ error: 'body must be a non-empty JSON object' })`)
    if (sql) {
      L.push(`  const { rows } = await db.query(`)
      L.push(`    'INSERT INTO ${table} (data) VALUES ($1) RETURNING *', [req.body])`)
      L.push(`  const item = rows[0]`)
    } else {
      L.push(`  const item = { _id: crypto.randomUUID(), ...req.body }`)
      L.push(`  await col.insertOne(item)`)
    }
    if (cache) L.push(`  await cache.del('${resource}:' + item.id).catch(() => {})  // invalidate — never leave stale data in front of the store`)
    L.push(`  res.status(201).json(item)`)
    L.push(`}))`)
    L.push('')
  }

  if (queue) {
    L.push(`app.post('/jobs', h(async (req, res) => {`)
    L.push(`  if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'body must be JSON' })`)
    L.push(`  ch.sendToQueue('jobs', Buffer.from(JSON.stringify(req.body)), { persistent: true })`)
    L.push(`  res.status(202).json({ queued: true })   // accepted, not done — that is the contract`)
    L.push(`}))`)
    L.push('')
  }
  if (kafka) {
    L.push(`app.post('/events', h(async (req, res) => {`)
    L.push(`  await producer.send({ topic: 'events', messages: [{ value: JSON.stringify(req.body) }] })`)
    L.push(`  res.status(202).json({ published: true })`)
    L.push(`}))`)
    L.push('')
  }

  if (llm) {
    L.push(`// ${llm.label}${vector ? ` with ${vector.label}` : ''}: ${vector ? 'retrieval-augmented generation — embed the question, fetch the nearest chunks, ground the prompt' : 'direct inference'}.`)
    L.push(`// Every upstream call carries a deadline: a model that never answers must`)
    L.push(`// become a 502 here, not a request that hangs until the client gives up.`)
    L.push(`app.post('/ask', h(async (req, res) => {`)
    L.push(`  const question = String(req.body?.question || '').trim()`)
    L.push(`  if (!question || question.length > 4000) return res.status(400).json({ error: 'question must be 1-4000 chars' })`)
    L.push(`  try {`)
    if (vector) {
      L.push(`    const emb = await fetch(process.env.EMBED_URL + '/embed', {`)
      L.push(`      method: 'POST', headers: { 'content-type': 'application/json' },`)
      L.push(`      body: JSON.stringify({ text: question }), signal: AbortSignal.timeout(5000) }).then(r => r.json())`)
      L.push(`    const near = await fetch((process.env.VECTOR_URL || 'http://${slug(vector.label)}:6333') + '/collections/docs/points/search', {`)
      L.push(`      method: 'POST', headers: { 'content-type': 'application/json' },`)
      L.push(`      body: JSON.stringify({ vector: emb.vector, limit: 5 }), signal: AbortSignal.timeout(5000) }).then(r => r.json())`)
      L.push(`    const context = (near.result || []).map(p => p.payload?.text).join('\\n')`)
    }
    L.push(`    const answer = await fetch(process.env.LLM_URL || 'http://${slug(llm.label)}:11434/api/generate', {`)
    L.push(`      method: 'POST', headers: { 'content-type': 'application/json' },`)
    L.push(`      body: JSON.stringify({ model: process.env.LLM_MODEL || 'gemma:7b',`)
    L.push(`        prompt: ${vector ? '`Answer from this context only:\\n${context}\\n\\nQ: ${question}`' : 'question'}, stream: false }),`)
    L.push(`      signal: AbortSignal.timeout(30000) }).then(r => r.json())`)
    L.push(`    res.json({ answer: answer.response })`)
    L.push(`  } catch (err) {`)
    L.push(`    log('error', 'inference failed', { err: err.message })`)
    L.push(`    res.status(502).json({ error: 'model upstream unavailable' })`)
    L.push(`  }`)
    L.push(`}))`)
    L.push('')
  }

  L.push(`app.use((_req, res) => res.status(404).json({ error: 'not found' }))`)
  L.push(`app.use((err, _req, res, _next) => {         // last resort: log the detail, never leak it`)
  L.push(`  log('error', 'unhandled', { err: err.message, stack: err.stack?.split('\\n')[1]?.trim() })`)
  L.push(`  res.status(500).json({ error: 'internal error' })`)
  L.push(`})`)
  L.push('')
  L.push(`const server = app.listen(process.env.PORT || ${isWs ? 8080 : 3000}, () =>`)
  L.push(`  log('info', 'listening', { port: Number(process.env.PORT || ${isWs ? 8080 : 3000}) }))`)
  if (isWs) {
    L.push(`const wss = new WebSocketServer({ server })`)
    L.push(`wss.on('connection', ws => {`)
    L.push(`  ws.on('message', msg => {`)
    L.push(`    // Frames travel both directions for the socket's lifetime —`)
    L.push(`    // the two-way arrow on the canvas is this loop.`)
    L.push(`    for (const client of wss.clients) if (client.readyState === 1) client.send(msg.toString())`)
    L.push(`  })`)
    L.push(`})`)
  }
  L.push('')
  L.push(`// Graceful shutdown: stop taking traffic, drain, close every client, and`)
  L.push(`// force-exit if draining hangs — the orchestrator's SIGKILL should be a`)
  L.push(`// formality, never the mechanism.`)
  L.push(`async function shutdown(signal) {`)
  L.push(`  log('info', 'shutdown', { signal })`)
  L.push(`  setTimeout(() => { log('error', 'shutdown timed out, forcing exit'); process.exit(1) }, 10000).unref()`)
  L.push(`  await new Promise(r => server.close(r))`)
  const closers = []
  if (cache) closers.push(`cache.quit().catch(() => {})`)
  if (sql) closers.push(`db.end().catch(() => {})`)
  if (nosql) closers.push(`mongo.close().catch(() => {})`)
  if (queue) closers.push(`mq.close().catch(() => {})`)
  if (kafka) closers.push(`producer.disconnect().catch(() => {})`)
  if (closers.length) L.push(`  await Promise.all([${closers.join(', ')}])`)
  L.push(`  process.exit(0)`)
  L.push(`}`)
  L.push(`process.on('SIGTERM', () => shutdown('SIGTERM'))`)
  L.push(`process.on('SIGINT', () => shutdown('SIGINT'))`)
  return L.join('\n') + '\n'
}

// ── worker: consumes whatever feeds it ─────────────────────────────────────
function workerFile(wk, w) {
  const feeds = w.into(wk.id)
  const queue = feeds.find(t => QUEUE_TYPES.has(t.type))
  const kafka = feeds.find(t => t.type === 'kafka')
  const targets = w.out(wk.id)
  const sql = targets.find(t => t.type === 'sql')
  const name = slug(wk.label)
  const L = []
  L.push(`// ${wk.label} — generated by ArchSim from the canvas.`)
  L.push(`// Consumes: ${[queue, kafka].filter(Boolean).map(t => t.label).join(', ') || 'nothing — wire a queue or stream into this worker'}.`)
  if (queue || kafka) {
    L.push(queue ? `import amqp from 'amqplib'` : `import { Kafka } from 'kafkajs'`)
    if (sql) L.push(`import pg from 'pg'`)
    L.push('')
    L.push(`const log = (level, msg, extra = {}) =>`)
    L.push(`  console.log(JSON.stringify({ ts: new Date().toISOString(), level, service: '${name}', msg, ...extra }))`)
    L.push(`async function withRetry(what, fn, attempts = 8) {`)
    L.push(`  for (let i = 1; ; i++) {`)
    L.push(`    try { return await fn() } catch (err) {`)
    L.push(`      if (i >= attempts) throw err`)
    L.push(`      const wait = Math.min(15000, 250 * 2 ** i)`)
    L.push(`      log('warn', what + ' not ready, retrying', { attempt: i, wait, err: err.message })`)
    L.push(`      await new Promise(r => setTimeout(r, wait))`)
    L.push(`    }`)
    L.push(`  }`)
    L.push(`}`)
    L.push('')
  }
  if (queue) {
    if (sql) {
      L.push(`const db = new pg.Pool({ connectionString: process.env.DATABASE_URL || 'postgres://postgres:change-me@${slug(sql.label)}:5432/postgres', max: 5, statement_timeout: 5000 })`)
      L.push(`db.on('error', err => log('error', 'pg pool', { err: err.message }))`)
    }
    L.push(`const mq = await withRetry('rabbitmq', () => amqp.connect(process.env.AMQP_URL || 'amqp://${slug(queue.label)}:5672'))`)
    L.push(`mq.on('error', err => log('error', 'amqp', { err: err.message }))`)
    L.push(`const ch = await mq.createChannel()`)
    L.push(`await ch.assertQueue('jobs', { durable: true })`)
    L.push(`ch.prefetch(10)   // at most 10 unacked jobs in flight per worker`)
    L.push('')
    L.push(`let inFlight = 0`)
    L.push(`ch.consume('jobs', async msg => {`)
    L.push(`  if (!msg) return`)
    L.push(`  inFlight++`)
    L.push(`  try {`)
    L.push(`    const job = JSON.parse(msg.content.toString())`)
    if (sql) L.push(`    await db.query('INSERT INTO results (data) VALUES ($1)', [job])`)
    else L.push(`    log('info', 'processing', { job })`)
    L.push(`    ch.ack(msg)                      // ack only after the work is durable`)
    L.push(`  } catch (err) {`)
    L.push(`    log('error', 'job failed', { err: err.message })`)
    L.push(`    ch.nack(msg, false, false)       // dead-letter, do not requeue a poison pill`)
    L.push(`  } finally { inFlight-- }`)
    L.push(`})`)
    L.push('')
    L.push(`// Graceful shutdown: stop consuming, let in-flight jobs finish, then close.`)
    L.push(`async function shutdown(signal) {`)
    L.push(`  log('info', 'shutdown', { signal, inFlight })`)
    L.push(`  setTimeout(() => { log('error', 'shutdown timed out, forcing exit'); process.exit(1) }, 10000).unref()`)
    L.push(`  await ch.close().catch(() => {})   // no new deliveries; unacked jobs will be redelivered elsewhere`)
    L.push(`  while (inFlight > 0) await new Promise(r => setTimeout(r, 100))`)
    L.push(`  await mq.close().catch(() => {})`)
    if (sql) L.push(`  await db.end().catch(() => {})`)
    L.push(`  process.exit(0)`)
    L.push(`}`)
    L.push(`process.on('SIGTERM', () => shutdown('SIGTERM'))`)
    L.push(`process.on('SIGINT', () => shutdown('SIGINT'))`)
  } else if (kafka) {
    L.push(`const kafka = new Kafka({ brokers: [process.env.KAFKA_BROKER || '${slug(kafka.label)}:9092'] })`)
    L.push(`const consumer = kafka.consumer({ groupId: '${name}' })`)
    L.push(`await withRetry('kafka', () => consumer.connect())`)
    L.push(`await consumer.subscribe({ topic: 'events', fromBeginning: false })`)
    L.push(`await consumer.run({`)
    L.push(`  eachMessage: async ({ message }) => {`)
    L.push(`    log('info', 'event', { value: JSON.parse(message.value.toString()) })`)
    L.push(`  },`)
    L.push(`})`)
    L.push(`process.on('SIGTERM', async () => { await consumer.disconnect().catch(() => {}); process.exit(0) })`)
    L.push(`process.on('SIGINT', async () => { await consumer.disconnect().catch(() => {}); process.exit(0) })`)
  } else {
    L.push('')
    L.push(`console.log('${wk.label}: nothing feeds this worker yet — draw an edge from a queue or stream to it.')`)
  }
  return L.join('\n') + '\n'
}

// ── the whole project ──────────────────────────────────────────────────────
export function generateProject(nodes, edges) {
  const w = wiring(nodes, edges)
  const services = nodes.filter(n => SERVICE_TYPES.has(n.type))
  const workers = nodes.filter(n => n.type === 'worker')
  const sqls = nodes.filter(n => n.type === 'sql')
  const files = []

  if (!services.length && !workers.length) {
    return [{ path: 'README.md', content: '# Nothing to generate yet\n\nAdd a service tier (Web, App, Microservice, WebSocket...) or a worker to the canvas and the full system code will appear here.\n' }]
  }

  // Which npm packages this design actually needs — derived, like everything.
  const deps = { express: '^4.19.0' }
  for (const s of [...services, ...workers]) {
    const t = [...w.out(s.id), ...w.into(s.id)]
    if (t.some(x => x.type === 'cache')) deps.redis = '^4.6.0'
    if (t.some(x => x.type === 'sql')) deps.pg = '^8.11.0'
    if (t.some(x => x.type === 'nosql')) deps.mongodb = '^6.5.0'
    if (t.some(x => QUEUE_TYPES.has(x.type))) deps.amqplib = '^0.10.0'
    if (t.some(x => x.type === 'kafka')) deps.kafkajs = '^2.2.0'
    if (s.type === 'ws') deps.ws = '^8.16.0'
  }

  files.push({
    path: 'package.json',
    content: JSON.stringify({
      name: 'archsim-generated-system',
      private: true,
      type: 'module',
      scripts: Object.fromEntries([
        ...services.map(s => [`start:${slug(s.label)}`, `node services/${slug(s.label)}/server.js`]),
        ...workers.map(k => [`start:${slug(k.label)}`, `node services/${slug(k.label)}/worker.js`]),
      ]),
      dependencies: deps,
    }, null, 2) + '\n',
  })

  files.push({
    path: 'README.md',
    content: [
      '# Generated system — ArchSim',
      '',
      'Every file here is derived from the canvas: routes from the edges, cache-aside',
      'from a cache in front of a store, producers and consumers from the queues,',
      'replica counts in docker-compose from the Capacity tab. Change the diagram',
      '(or apply an ✨ Improve suggestion) and regenerate — the code follows.',
      '',
      '## Run it',
      '```bash',
      'docker compose up -d     # infrastructure (see the docker-compose tab)',
      'npm install',
      ...services.map(s => `npm run start:${slug(s.label)}`),
      ...workers.map(k => `npm run start:${slug(k.label)}`),
      '```',
      '',
      '## Services',
      ...services.map(s => `- **${s.label}** (\`services/${slug(s.label)}/server.js\`) → ${w.out(s.id).map(t => t.label).join(', ') || 'no downstream'}`),
      ...workers.map(k => `- **${k.label}** (\`services/${slug(k.label)}/worker.js\`) ← ${w.into(k.id).map(t => t.label).join(', ') || 'nothing yet'}`),
      '',
    ].join('\n') + '\n',
  })

  const envLines = ['# Connection strings — hostnames match the docker-compose service names.']
  for (const n of nodes) {
    if (n.type === 'cache') envLines.push(`REDIS_URL=redis://${slug(n.label)}:6379`)
    if (n.type === 'sql') envLines.push(`DATABASE_URL=postgres://postgres:change-me@${slug(n.label)}:5432/postgres`)
    if (n.type === 'nosql') envLines.push(`MONGO_URL=mongodb://${slug(n.label)}:27017`)
    if (QUEUE_TYPES.has(n.type)) envLines.push(`AMQP_URL=amqp://${slug(n.label)}:5672`)
    if (n.type === 'kafka') envLines.push(`KAFKA_BROKER=${slug(n.label)}:9092`)
    if (n.type === 'vector') envLines.push(`VECTOR_URL=http://${slug(n.label)}:6333`)
    if (LLM_TYPES.has(n.type)) envLines.push(`LLM_URL=http://${slug(n.label)}:11434/api/generate`)
  }
  files.push({ path: '.env.example', content: envLines.join('\n') + '\n' })

  if (sqls.length) {
    files.push({
      path: 'db/schema.sql',
      content: sqls.map(s => {
        const t = varName(slug(s.label))
        return [`-- ${s.label}`,
          `CREATE TABLE IF NOT EXISTS ${t} (`,
          `  id BIGSERIAL PRIMARY KEY,`,
          `  data JSONB NOT NULL,`,
          `  created_at TIMESTAMPTZ NOT NULL DEFAULT now()`,
          `);`,
          `CREATE INDEX IF NOT EXISTS ${t}_created_idx ON ${t} (created_at);`, ''].join('\n')
      }).join('\n') + 'CREATE TABLE IF NOT EXISTS results (\n  id BIGSERIAL PRIMARY KEY,\n  data JSONB NOT NULL\n);\n',
    })
  }

  for (const s of services) files.push({ path: `services/${slug(s.label)}/server.js`, content: serverFile(s, w) })
  for (const k of workers) files.push({ path: `services/${slug(k.label)}/worker.js`, content: workerFile(k, w) })

  return files
}
