// Pre-wired classic system designs. Node: [id, type, label, x, y, replicas, weight]
// weight = share of total traffic for source (client) nodes.
// group drives the optgroup in the template picker.
const T = (name, tagline, rps, nodes, edges, checklist, group = 'Product designs') => ({
  name, tagline, rps, group,
  nodes: nodes.map(([id, type, label, x, y, replicas = 1, weight, region, siteRole]) => ({ id, type, label, x, y, replicas, ...(weight !== undefined ? { weight } : {}), ...(region ? { region } : {}), ...(siteRole ? { siteRole } : {}) })),
  edges: edges.map(([from, to, label = '']) => ({ id: `${from}->${to}`, from, to, label })),
  checklist,
})

export const TEMPLATES = [
  T('URL Shortener (Bitly)', 'Read-heavy redirect service', 12000, [
    ['c', 'client', 'Users', 60, 220], ['cdn', 'cdn', 'CDN', 200, 220],
    ['lb', 'lb', 'LB', 340, 220], ['app', 'app', 'Read/Write API', 480, 220, 4],
    ['cache', 'cache', 'Hot URLs', 640, 120], ['db', 'nosql', 'URL Table', 640, 320, 3],
  ], [['c','cdn'],['cdn','lb'],['lb','app'],['app','cache'],['app','db']], [
    'Short code generation: base62 of counter vs hash — collision handling?',
    'Read:write ratio ~100:1 → cache the redirects aggressively',
    '301 vs 302 redirect trade-off (caching vs analytics)',
    'Counter service or KGS to avoid duplicate codes',
    'Estimate: 100M new URLs/month ≈ 40 writes/s, 4k reads/s',
  ]),
  T('Ticketmaster', 'Concurrency control for seat booking', 8000, [
    ['c', 'client', 'Fans', 40, 240], ['cdn', 'cdn', 'CDN', 170, 240],
    ['lb', 'lb', 'LB', 300, 240], ['gw', 'gateway', 'API GW', 420, 240, 2],
    ['search', 'search', 'Event Search', 570, 100, 2], ['book', 'app', 'Booking Svc', 570, 240, 6],
    ['lock', 'cache', 'Seat Locks TTL', 730, 160], ['sql', 'sql', 'Bookings ACID', 730, 320, 2],
    ['q', 'queue', 'Waiting Queue', 570, 400],
  ], [['c','cdn'],['cdn','lb'],['lb','gw'],['gw','search'],['gw','book'],['book','lock'],['book','sql'],['gw','q'],['q','book']], [
    'Reserve seat with distributed lock (Redis TTL) before payment',
    'ACID transaction on final booking — no double sell',
    'Virtual waiting queue absorbs 100x flash-sale spikes',
    'Search events via Elasticsearch, not the booking DB',
    'Optimistic vs pessimistic locking trade-off',
  ]),
  T('Ride Sharing (Uber)', 'Realtime geo matching', 15000, [
    ['r', 'client', 'Riders', 40, 160, 1, 0.5], ['d', 'client', 'Drivers', 40, 340, 1, 0.5],
    ['lb', 'lb', 'LB', 190, 250], ['gw', 'gateway', 'API GW', 320, 250, 3],
    ['loc', 'ws', 'Location WS', 470, 350, 4], ['geo', 'cache', 'Geo Index (H3)', 640, 350, 3],
    ['match', 'app', 'Matching Svc', 470, 160, 6], ['trip', 'sql', 'Trips DB', 640, 100, 2],
    ['k', 'kafka', 'Location Stream', 640, 250], ['surge', 'analytics', 'Surge Pricing', 800, 250, 3],
  ], [['r','lb'],['d','lb'],['lb','gw'],['gw','loc'],['loc','geo'],['gw','match'],['match','geo'],['match','trip'],['loc','k'],['k','surge']], [
    'Drivers push GPS every 4s over WebSocket — do the math on write QPS',
    'Geo-index (H3/geohash) in memory, not in SQL',
    'Matching: nearest-driver query on the geo index + ETA ranking',
    'Kafka stream feeds surge pricing & analytics',
    'Trip state machine: requested → matched → in-ride → completed',
  ]),
  T('Video Platform (YouTube)', 'Upload pipeline + massive read fan-out', 50000, [
    ['c', 'client', 'Viewers', 40, 140, 1, 0.95], ['up', 'client', 'Uploaders', 40, 380, 1, 0.05],
    ['cdn', 'cdn', 'Video CDN', 200, 140], ['lb', 'lb', 'LB', 200, 300],
    ['app', 'app', 'Watch API', 360, 220, 6], ['meta', 'nosql', 'Metadata', 520, 140, 3],
    ['upsvc', 'app', 'Upload Svc', 360, 380, 3], ['blob', 'blob', 'Raw Storage', 520, 460],
    ['q', 'queue', 'Transcode Q', 520, 380], ['w', 'worker', 'Transcoders', 680, 380, 10],
    ['out', 'blob', 'Encoded (HLS)', 680, 240], ['ml', 'ml', 'Recommendations', 520, 240, 8],
  ], [['c','cdn'],['cdn','app'],['app','meta'],['app','ml'],['up','lb'],['lb','upsvc'],['upsvc','blob'],['upsvc','q'],['q','w'],['w','out'],['out','cdn']], [
    'Chunked resumable uploads straight to object storage',
    'Async transcode pipeline: queue + worker pool, multiple bitrates (HLS/DASH)',
    'CDN serves ~all watch traffic; origin only on miss',
    'Metadata (views, titles) in partitioned NoSQL',
    'View-count: approximate counting / batched increments',
  ]),
  T('Chat (WhatsApp)', 'Persistent connections & delivery guarantees', 30000, [
    ['a', 'client', 'User A', 40, 160], ['b', 'client', 'User B', 40, 340],
    ['lb', 'lb', 'LB (sticky)', 190, 250], ['ws', 'ws', 'Chat Servers', 340, 250, 6],
    ['sess', 'cache', 'Session Registry', 500, 130], ['q', 'kafka', 'Msg Log', 500, 250],
    ['inbox', 'nosql', 'Inbox Store', 500, 380, 3], ['push', 'micro', 'Push Notif', 660, 250, 3],
    ['media', 'blob', 'Media Store', 660, 380],
  ], [['a','lb'],['b','lb'],['lb','ws'],['ws','sess'],['ws','q'],['q','inbox'],['q','push'],['ws','media']], [
    'One WebSocket per online user; session registry maps user → server',
    'Message IDs monotonic per conversation; at-least-once + dedupe',
    'Offline users: persist to inbox, deliver on reconnect + push notif',
    'Sent/delivered/read receipts as tiny state events',
    'E2E encryption means server stores ciphertext only',
  ]),
  T('Web Crawler', 'Politeness + dedup at scale', 2000, [
    ['seed', 'client', 'Seed URLs', 40, 240], ['front', 'queue', 'URL Frontier', 190, 240],
    ['sched', 'scheduler', 'Politeness Sched', 340, 140, 4], ['f', 'worker', 'Fetchers', 340, 320, 8],
    ['dns', 'dns', 'DNS Cache', 500, 420], ['parse', 'worker', 'Parsers', 500, 320, 4],
    ['dedup', 'cache', 'Seen? (Bloom)', 500, 140], ['store', 'blob', 'Page Store', 660, 320],
    ['idx', 'search', 'Index', 660, 180],
  ], [['seed','front'],['front','sched'],['sched','f'],['f','dns'],['f','parse'],['parse','dedup'],['dedup','front'],['parse','store'],['store','idx']], [
    'Frontier with per-domain queues → politeness (1 req/domain/sec)',
    'Bloom filter for URL-seen test at billions scale',
    'DNS caching — resolution is a real bottleneck',
    'Content dedup via simhash, trap/spider-web detection',
    'Estimate: 1B pages / 30 days ≈ 400 fetches/s sustained',
  ]),
  T('Collab Docs (Google Docs)', 'Realtime co-editing & OT/CRDT', 10000, [
    ['c', 'client', 'Editors', 40, 240], ['lb', 'lb', 'LB', 190, 240],
    ['ws', 'ws', 'Doc Sessions', 340, 240, 4], ['ot', 'app', 'OT/CRDT Engine', 500, 160, 5],
    ['cache', 'cache', 'Live Doc State', 660, 160], ['log', 'kafka', 'Op Log', 500, 320],
    ['db', 'nosql', 'Snapshots', 660, 320, 2], ['pres', 'micro', 'Presence', 340, 400, 3],
  ], [['c','lb'],['lb','ws'],['ws','ot'],['ot','cache'],['ot','log'],['log','db'],['ws','pres']], [
    'OT vs CRDT for concurrent edits — why you picked one',
    'One authoritative session per doc (sticky routing / doc-sharded)',
    'Op log + periodic snapshots → fast load and full history',
    'Presence & cursors are ephemeral, skip durable storage',
    'Offline edits reconcile through same transform pipeline',
  ]),
  T('News Feed (Twitter/X)', 'Fan-out on write vs read', 12000, [
    ['c', 'client', 'Users', 40, 240], ['lb', 'lb', 'LB', 180, 240],
    ['gw', 'gateway', 'API GW', 310, 240, 3], ['tw', 'app', 'Tweet Write', 460, 350, 6],
    ['tl', 'app', 'Timeline Read', 460, 130, 6], ['fan', 'worker', 'Fanout Workers', 620, 350, 8],
    ['tlc', 'cache', 'Timeline Cache', 620, 130, 4], ['soc', 'cache', 'Social Graph', 780, 350],
    ['db', 'nosql', 'Tweet Store', 780, 240, 3], ['rank', 'ml', 'Ranker', 620, 240, 10],
  ], [['c','lb'],['lb','gw'],['gw','tw'],['gw','tl'],['tw','db'],['tw','fan'],['fan','soc'],['fan','tlc'],['tl','tlc'],['tl','rank']], [
    'Fan-out on write for normal users; on read for celebrities (hybrid)',
    'Timeline cache = list of tweet IDs per user, hydrate on read',
    'Social graph lookups must be O(1) — cache it',
    'Ranking layer between cache and response',
    'Estimate: 500M tweets/day ≈ 6k writes/s, reads 100x that',
  ]),
  T('File Sync (Dropbox)', 'Chunking, dedup, delta sync', 6000, [
    ['c', 'client', 'Desktop Clients', 40, 240], ['lb', 'lb', 'LB', 190, 240],
    ['meta', 'app', 'Metadata Svc', 340, 150, 4], ['db', 'sql', 'Meta DB', 500, 90, 2],
    ['blockp', 'app', 'Block Svc', 340, 330, 4], ['blob', 'blob', 'Block Store', 500, 330],
    ['notif', 'ws', 'Notify (long-poll)', 340, 450], ['q', 'queue', 'Sync Events', 500, 450],
    ['cache', 'cache', 'Meta Cache', 500, 210],
  ], [['c','lb'],['lb','meta'],['meta','cache'],['meta','db'],['lb','blockp'],['blockp','blob'],['q','notif'],['meta','q'],['notif','c']], [
    'Files split into 4MB chunks; content-hash dedup across users',
    'Delta sync — only changed blocks travel',
    'Metadata (namespace, versions) separate from block storage',
    'Notification channel wakes other devices on change',
    'Conflict copy on concurrent edit, never silent overwrite',
  ]),
  T('Rate Limiter (as a system)', 'Shared counters, low latency', 24000, [
    ['c', 'client', 'API Callers', 40, 240], ['lb', 'lb', 'LB', 190, 240],
    ['rl', 'ratelimiter', 'Limiter Nodes', 340, 240, 4], ['redis', 'cache', 'Counters (Redis)', 500, 160, 3],
    ['rules', 'sql', 'Rules DB', 500, 330, 2], ['api', 'app', 'Protected API', 660, 240, 5],
    ['k', 'kafka', 'Decisions Log', 340, 400], ['an', 'analytics', 'Abuse Analytics', 500, 450, 5],
  ], [['c','lb'],['lb','rl'],['rl','redis'],['rl','rules'],['rl','api'],['rl','k'],['k','an']], [
    'Sliding-window counter in Redis (INCR + EXPIRE, Lua for atomicity)',
    'Local in-memory cache of rules; sync from DB',
    'Fail-open or fail-closed when Redis is down — decide!',
    '429 with Retry-After; expose headers X-RateLimit-*',
    'Hot-key problem: shard counters for giant tenants',
  ]),
  T('Local Search (Yelp)', 'Geo queries + reviews', 9000, [
    ['c', 'client', 'Users', 40, 240], ['cdn', 'cdn', 'CDN', 180, 240],
    ['lb', 'lb', 'LB', 320, 240], ['app', 'app', 'Search API', 460, 240, 4],
    ['geo', 'search', 'Geo Index', 620, 150, 3], ['biz', 'sql', 'Business DB', 620, 330, 2],
    ['cache', 'cache', 'Hot Areas', 620, 240], ['rev', 'micro', 'Reviews Svc', 460, 400, 2],
  ], [['c','cdn'],['cdn','lb'],['lb','app'],['app','cache'],['app','geo'],['app','biz'],['lb','rev'],['rev','biz']], [
    'Geohash/quadtree index for "restaurants near me"',
    'Search radius expansion when sparse results',
    'Reviews write path separate from search read path',
    'Cache popular city/category combos',
    'Ranking: distance + rating + open-now filters',
  ]),
  T('Leaderboard (Top-K)', 'Sorted sets & windows', 12000, [
    ['c', 'client', 'Game Clients', 40, 240], ['gw', 'gateway', 'API GW', 190, 240, 2],
    ['ing', 'micro', 'Score Ingest', 340, 320, 3], ['k', 'kafka', 'Score Stream', 500, 320],
    ['agg', 'worker', 'Aggregators', 660, 320, 8], ['z', 'cache', 'Redis ZSET', 660, 160, 3],
    ['read', 'micro', 'Leaderboard API', 340, 160, 3], ['db', 'nosql', 'History', 800, 320],
  ], [['c','gw'],['gw','ing'],['ing','k'],['k','agg'],['agg','z'],['agg','db'],['gw','read'],['read','z']], [
    'Redis sorted set gives O(log n) rank updates and top-K reads',
    'Windowed boards (daily/weekly) = separate keys with TTL',
    'Stream + aggregator absorbs write bursts',
    'Around-me query: ZRANK ± N',
    'Persist history for offline analytics/anti-cheat',
  ]),
  T('Notification System', 'Multi-channel fan-out', 8000, [
    ['svc', 'client', 'Producer Services', 40, 240], ['gw', 'gateway', 'Notif API', 190, 240, 2],
    ['q', 'kafka', 'Notif Topics', 340, 240], ['pref', 'nosql', 'Prefs/Devices', 340, 400, 2],
    ['w', 'worker', 'Channel Workers', 500, 240, 10], ['push', 'micro', 'APNs/FCM', 660, 140],
    ['email', 'micro', 'Email (SES)', 660, 240], ['sms', 'micro', 'SMS', 660, 340],
    ['dedup', 'cache', 'Dedup/Rate', 500, 400],
  ], [['svc','gw'],['gw','q'],['q','w'],['w','pref'],['w','dedup'],['w','push'],['w','email'],['w','sms']], [
    'Queue between producers and channels — absorb bursts, retry safely',
    'Idempotency key per notification, dedup cache',
    'User prefs + quiet hours checked at send time',
    'Per-channel rate limits & provider failover',
    'Track delivery receipts for retries/analytics',
  ]),
  T('Payment System (Stripe-lite)', 'Exactly-once money movement', 4000, [
    ['c', 'client', 'Merchants', 40, 240], ['gw', 'gateway', 'API GW', 180, 240, 2],
    ['pay', 'app', 'Payment Svc', 330, 240, 4], ['idem', 'cache', 'Idempotency Keys', 330, 100],
    ['led', 'sql', 'Ledger (ACID)', 490, 160, 2], ['q', 'queue', 'Outbox', 490, 320],
    ['w', 'worker', 'PSP Connector', 650, 320, 3], ['psp', 'micro', 'Card Networks', 800, 320],
    ['rec', 'scheduler', 'Reconciliation', 650, 450],
  ], [['c','gw'],['gw','pay'],['pay','idem'],['pay','led'],['pay','q'],['q','w'],['w','psp'],['rec','led']], [
    'Idempotency keys on every mutation — retries must be safe',
    'Double-entry ledger, append-only, ACID',
    'Outbox pattern: DB commit + async PSP call, never dual-write',
    'State machine: created → authorized → captured → settled',
    'Daily reconciliation against PSP reports',
  ]),
  T('Search Autocomplete', 'Prefix trees at the edge', 45000, [
    ['c', 'client', 'Typers', 40, 240], ['cdn', 'cdn', 'Edge Cache', 180, 240],
    ['lb', 'lb', 'LB', 320, 240], ['ac', 'micro', 'Suggest Svc', 460, 240, 6],
    ['trie', 'cache', 'Trie Shards', 620, 160, 4], ['k', 'kafka', 'Query Log', 460, 380],
    ['agg', 'analytics', 'Trending Agg', 620, 380, 2], ['store', 'nosql', 'Trie Builder Out', 780, 380],
  ], [['c','cdn'],['cdn','lb'],['lb','ac'],['ac','trie'],['ac','k'],['k','agg'],['agg','store'],['store','trie']], [
    'Trie/weighted prefix index fully in memory, sharded by prefix',
    'Sub-100ms budget → cache top prefixes at CDN',
    'Offline pipeline rebuilds tries from query logs hourly',
    'Debounce client-side; only 2+ chars hit servers',
    'Personalization & trending merged at ranking time',
  ]),

  // ─────────────── microservice architecture patterns ───────────────
  T('µsvc: E-commerce (Saga)', 'Service-per-domain + distributed transaction', 6000, [
    ['c', 'client', 'Storefront', 40, 250], ['gw', 'gateway', 'API Gateway', 175, 250, 2],
    ['mesh', 'mesh', 'Service Mesh', 175, 400, 2], ['reg', 'registry', 'Discovery', 40, 400],
    ['saga', 'saga', 'Order Saga', 330, 250, 3],
    ['order', 'micro', 'Order Svc', 490, 120, 2], ['odb', 'sql', 'Orders DB', 650, 120],
    ['inv', 'micro', 'Inventory Svc', 490, 250, 2], ['idb', 'sql', 'Inventory DB', 650, 250],
    ['pay', 'micro', 'Payment Svc', 490, 380, 2], ['pdb', 'sql', 'Payments DB', 650, 380],
    ['ship', 'micro', 'Shipping Svc', 490, 500, 2], ['bus', 'kafka', 'Event Bus', 330, 500],
  ], [['c','gw'],['gw','mesh'],['mesh','reg'],['gw','saga'],['saga','order'],['order','odb'],
      ['saga','inv'],['inv','idb'],['saga','pay'],['pay','pdb'],['saga','bus'],['bus','ship']], [
    'Database-per-service — no cross-service joins or shared schema',
    'Saga with compensating transactions (cancel order, release stock, refund)',
    'Orchestration (central saga) vs choreography (services react to events)',
    'Outbox pattern so DB commit and event publish cannot diverge',
    'Idempotent handlers — every event may be delivered twice',
  ], 'Microservice patterns'),
  T('µsvc: CQRS + Event Sourcing', 'Split write model from read models', 9000, [
    ['c', 'client', 'Clients', 40, 250], ['gw', 'gateway', 'API Gateway', 175, 250, 2],
    ['cmd', 'micro', 'Command Side', 320, 150, 3], ['es', 'kafka', 'Event Store (log)', 480, 150],
    ['proj', 'worker', 'Projectors', 640, 150, 4],
    ['rd1', 'nosql', 'Read Model A', 800, 90, 2], ['rd2', 'search', 'Read Model B', 800, 220, 2],
    ['qry', 'micro', 'Query Side', 320, 340, 4], ['qc', 'cache', 'Query Cache', 480, 340, 2],
    ['snap', 'blob', 'Snapshots', 640, 340],
  ], [['c','gw'],['gw','cmd'],['cmd','es'],['es','proj'],['proj','rd1'],['proj','rd2'],
      ['gw','qry'],['qry','qc'],['qc','rd1'],['es','snap']], [
    'Commands mutate via events only; state is a fold over the log',
    'Read models are disposable — rebuild by replaying the event store',
    'Eventual consistency window between write and read side: how do you hide it?',
    'Snapshots to bound replay time for long-lived aggregates',
    'Event versioning / schema evolution (upcasting)',
  ], 'Microservice patterns'),
  T('µsvc: BFF + Mesh Platform', 'Per-client edge, sidecar-managed east-west', 14000, [
    ['web', 'client', 'Web', 40, 130], ['mob', 'client', 'Mobile', 40, 300],
    ['bffw', 'bff', 'Web BFF', 200, 130, 3], ['bffm', 'bff', 'Mobile BFF', 200, 300, 3],
    ['mesh', 'mesh', 'Sidecar Mesh', 360, 215, 4],
    ['a', 'micro', 'Catalog Svc', 520, 90, 3], ['b', 'micro', 'Profile Svc', 520, 215, 3],
    ['d', 'micro', 'Pricing Svc', 520, 340, 3],
    ['cfg', 'config', 'Config/Flags', 360, 430], ['reg', 'registry', 'Discovery', 360, 520],
    ['tr', 'tracing', 'Tracing', 680, 430], ['cache', 'cache', 'Shared Cache', 680, 215, 2],
  ], [['web','bffw'],['mob','bffm'],['bffw','mesh'],['bffm','mesh'],['mesh','a'],['mesh','b'],
      ['mesh','d'],['b','cache'],['mesh','cfg'],['cfg','reg'],['mesh','tr']], [
    'One BFF per client type — mobile needs fewer fields than web',
    'Sidecar handles mTLS, retries with jitter, circuit breaking, canary splits',
    'Fan-out per request: N downstream calls means N× tail-latency risk',
    'Timeout budget must shrink at every hop, never grow',
    'Discovery + centralised config so services stay stateless',
  ], 'Microservice patterns'),
  T('µsvc: Event-Driven Orders', 'Choreography, no central coordinator', 8000, [
    ['c', 'client', 'Clients', 40, 250], ['gw', 'gateway', 'API Gateway', 175, 250, 2],
    ['ord', 'micro', 'Order Svc', 320, 250, 5], ['bus', 'kafka', 'Kafka Topics', 470, 250],
    ['pay', 'micro', 'Payment Consumer', 620, 110, 2],
    ['inv', 'micro', 'Stock Consumer', 620, 250, 2],
    ['notif', 'worker', 'Notify Consumer', 620, 390, 3],
    ['dlq', 'queue', 'DLQ', 470, 400], ['proj', 'nosql', 'Order View', 780, 250, 2],
    ['an', 'analytics', 'Stream Analytics', 780, 110, 2],
  ], [['c','gw'],['gw','ord'],['ord','bus'],['bus','pay'],['bus','inv'],['bus','notif'],
      ['bus','dlq'],['pay','proj'],['an','proj'],['pay','an']], [
    'Services react to events — no service calls another synchronously',
    'Consumer groups + partition key (orderId) preserve per-order ordering',
    'Dead-letter queue with retry/backoff for poison messages',
    'Exactly-once is really at-least-once + idempotent consumers',
    'Trade-off: loose coupling, but the end-to-end flow is hard to see',
  ], 'Microservice patterns'),
  T('µsvc: Strangler Migration', 'Carving services out of a monolith', 7000, [
    ['c', 'client', 'Clients', 40, 250], ['lb', 'lb', 'Router / LB', 180, 250],
    ['gw', 'gateway', 'Strangler Facade', 320, 250, 3],
    ['mono', 'app', 'Legacy Monolith', 480, 380, 4], ['mdb', 'sql', 'Legacy DB', 640, 460, 2],
    ['new1', 'micro', 'Users Svc (new)', 480, 130, 3], ['ndb1', 'nosql', 'Users DB', 640, 80, 2],
    ['new2', 'micro', 'Search Svc (new)', 480, 240, 3], ['ndb2', 'search', 'Search Index', 640, 200, 2],
    ['cdc', 'kafka', 'CDC Stream', 640, 330], ['sync', 'worker', 'Sync Workers', 800, 330, 3],
  ], [['c','lb'],['lb','gw'],['gw','new1'],['new1','ndb1'],['gw','new2'],['new2','ndb2'],
      ['gw','mono'],['mono','mdb'],['mdb','cdc'],['cdc','sync'],['sync','ndb1']], [
    'Facade routes per-endpoint: new service or monolith, flip gradually',
    'CDC keeps extracted data in sync during dual-write period',
    'Migrate by bounded context, never by database table',
    'Every extraction needs a rollback path (route back to monolith)',
    'Retire monolith code only once traffic is 0% for a full cycle',
  ], 'Microservice patterns'),

  // ─────────────── data platform ───────────────
  T('Data Platform (Lakehouse)', 'Ingest → lake → warehouse → BI', 3000, [
    ['app', 'client', 'Product Services', 40, 200], ['ops', 'client', 'Ops/3rd-party', 40, 380],
    ['oltp', 'sql', 'Prod OLTP DB', 200, 470, 2], ['cdc', 'cdc', 'CDC (Debezium)', 340, 470, 2],
    ['bus', 'kafka', 'Ingest Stream', 210, 290],
    ['raw', 'lake', 'Lake — raw/bronze', 380, 200, 2],
    ['etl', 'etl', 'ELT Transform', 540, 290, 6],
    ['cur', 'lake', 'Lake — curated/silver', 380, 380, 2],
    ['wh', 'warehouse', 'Warehouse (gold)', 700, 290, 4],
    ['bi', 'bi', 'BI / Dashboards', 860, 200, 4],
    ['ml', 'ml', 'Feature/ML Jobs', 860, 380, 6],
    ['sch', 'scheduler', 'Orchestrator (DAGs)', 540, 470, 2],
  ], [['app','bus'],['app','oltp'],['ops','bus'],['bus','raw'],['oltp','cdc'],['cdc','bus'],['raw','etl'],
      ['etl','cur'],['cur','wh'],['etl','wh'],['wh','bi'],['wh','ml'],['sch','etl']], [
    'Medallion layout: raw/bronze is immutable, curated/silver is conformed, warehouse/gold is modelled',
    'Lake vs warehouse: schema-on-read + cheap PB storage vs modelled columnar SQL performance',
    'ELT (transform inside the warehouse) vs ETL (transform before load)',
    'CDC off the OLTP replica — analytics must never query the production primary',
    'Partitioning + file compaction; small-files problem kills lake query performance',
    'Orchestrator owns DAG dependencies, retries, backfills and data-freshness SLAs',
    'Idempotent loads keyed on batch/watermark so replays do not double-count',
  ], 'Data platform'),

  // ─────────────── AI / ML system design ───────────────
  T('GenAI: RAG Assistant', 'Retrieval-augmented chat over your own docs', 400, [
    ['c', 'client', 'Users', 40, 250], ['gw', 'gateway', 'API Gateway', 180, 250, 2],
    ['rl', 'ratelimiter', 'Token Budget', 180, 400, 2],
    ['orch', 'app', 'Orchestrator', 330, 250, 4],
    ['gin', 'guard', 'Input Guardrails', 330, 110, 2],
    ['qemb', 'embed', 'Query Embedder', 480, 340, 3],
    ['vec', 'vector', 'Vector DB', 630, 340, 3],
    ['sem', 'cache', 'Semantic Cache', 480, 180, 2],
    ['llm', 'llm', 'LLM Inference', 630, 180, 12],
    ['gout', 'guard', 'Output Guardrails', 790, 180, 2],
    ['ing', 'worker', 'Doc Ingest', 330, 520, 3], ['blob', 'blob', 'Doc Store', 480, 520],
    ['iemb', 'embed', 'Index Embedder', 630, 520, 3],
    ['obs', 'analytics', 'Eval + Traces', 790, 340, 2],
  ], [['c','gw'],['gw','rl'],['gw','orch'],['orch','gin'],['orch','sem'],['sem','llm'],
      ['orch','qemb'],['qemb','vec'],['llm','gout'],['ing','blob'],['ing','iemb'],['iemb','vec'],['llm','obs']], [
    'Retrieval first, generation second — chunking strategy and chunk size drive answer quality',
    'Semantic cache on embeddings: identical-intent questions skip the LLM entirely (huge cost lever)',
    'LLM is the bottleneck by orders of magnitude — batch requests, stream tokens, cap max output',
    'Cost/latency budget per request: embed + ANN search + prompt tokens + generated tokens',
    'Guardrails on both sides: prompt injection and PII in, hallucination and unsafe content out',
    'Index pipeline is separate from the serving path; re-embed when the model version changes',
    'Evaluation is a first-class component — log traces, ground-truth sets, offline scoring',
  ], 'AI / ML'),
  T('ML: Recommendation Ranking', 'Candidate generation → ranking → serving', 20000, [
    ['c', 'client', 'Users', 40, 250], ['cdn', 'cdn', 'CDN', 170, 250],
    ['gw', 'gateway', 'API Gateway', 300, 250, 3],
    ['rec', 'micro', 'Recs Service', 440, 250, 6],
    ['cand', 'cache', 'Candidate Store', 590, 120, 3],
    ['feat', 'cache', 'Feature Store', 590, 250, 4],
    ['rank', 'ml', 'Ranker (GBDT/NN)', 740, 250, 20],
    ['fb', 'kafka', 'Click/Impression Log', 440, 400],
    ['train', 'worker', 'Training Jobs', 590, 400, 4],
    ['lake', 'lake', 'Feature Lake', 740, 400, 2],
    ['ab', 'config', 'A/B + Model Registry', 300, 400, 2],
  ], [['c','cdn'],['cdn','gw'],['gw','rec'],['rec','cand'],['rec','feat'],['rec','rank'],
      ['rec','fb'],['fb','train'],['train','lake'],['lake','feat'],['gw','ab']], [
    'Two stages: cheap candidate generation (thousands) then expensive ranking (hundreds)',
    'Feature store must serve online reads with the same values training saw — beware skew',
    'Latency budget ~100ms end to end, so the ranker gets a hard cap on candidates',
    'Feedback loop: impressions and clicks streamed back, and position bias corrected for',
    'Model registry + A/B assignment so a bad model is one flag flip away from rollback',
    'Cold start for new users and new items; fall back to popularity',
  ], 'AI / ML'),

  // ─────────────── enterprise & observability ───────────────
  T('Enterprise: Zero-Trust Platform', 'Regulated multi-tenant SaaS over legacy cores', 9000, [
    ['c', 'client', 'Customers', 40, 250], ['probe', 'synthetic', 'Synthetic Probes', 40, 560],
    ['gslb', 'gslb', 'Global Traffic Mgr', 175, 250], ['waf', 'waf', 'WAF / DDoS', 310, 250, 2],
    ['cdn', 'cdn', 'CDN', 310, 120],
    ['gw', 'gateway', 'API Gateway', 445, 250, 4], ['iam', 'iam', 'Identity (SSO)', 445, 400, 3],
    ['ten', 'tenant', 'Tenant Router', 580, 250, 2],
    ['k8s', 'k8s', 'Container Platform', 580, 120, 2],
    ['svc', 'micro', 'Domain Services', 715, 250, 6],
    ['sec', 'secrets', 'Secrets / KMS', 715, 400, 2], ['pii', 'pii', 'Tokenization Vault', 850, 400, 2],
    ['db', 'sql', 'Tenant DB (sharded)', 850, 250, 4], ['bk', 'backup', 'Backup & Archive', 985, 250, 2],
    ['mq', 'mq', 'Enterprise MQ', 715, 560, 3], ['esb', 'esb', 'Integration Bus', 850, 560, 3],
    ['core', 'mainframe', 'Mainframe Core', 985, 500, 2], ['erp', 'erp', 'ERP (SAP)', 985, 620, 2],
    ['aud', 'audit', 'Audit Log', 580, 560, 2],
  ], [['c','gslb'],['gslb','waf'],['waf','cdn'],['waf','gw'],['gw','iam'],['gw','ten'],['ten','svc'],
      ['k8s','svc'],['svc','sec'],['svc','pii'],['svc','db'],['db','bk'],['svc','mq'],['mq','esb'],
      ['esb','core'],['esb','erp'],['svc','aud'],['probe','gslb']], [
    'Zero trust: authenticate and authorise at every hop, never rely on network position',
    'Tenant isolation — shared schema vs schema-per-tenant vs silo, and the noisy-neighbour blast radius',
    'Systems of record (mainframe, ERP) cap out at ~1k rps and cannot scale out — always async behind MQ/ESB',
    'Tokenize PII/PAN early so downstream systems fall out of PCI/GDPR scope',
    'Secrets from KMS with rotation; nothing long-lived in config',
    'Audit log is append-only and tamper-evident, with a retention period set by regulation',
    'Backups are not replicas: prove the restore path with a timed drill',
    'Active-active regions behind GSLB, with an explicit RPO/RTO target',
  ], 'Enterprise'),
  T('Observability: Golden Signals', 'Instrument, aggregate, alert, and prove SLOs', 12000, [
    ['c', 'client', 'Users', 40, 260], ['probe', 'synthetic', 'Synthetic Probes', 40, 430],
    ['rum', 'apm', 'RUM / Client APM', 40, 100, 2],
    ['lb', 'lb', 'LB', 180, 260], ['gw', 'gateway', 'API Gateway', 310, 260, 3],
    ['svc', 'micro', 'Services', 445, 260, 8], ['k8s', 'k8s', 'Container Platform', 445, 110, 2],
    ['db', 'sql', 'Database', 445, 410, 3],
    ['otel', 'otel', 'OTel Collector', 600, 260, 3],
    ['met', 'monitor', 'Metrics & Alerts', 745, 130, 2],
    ['log', 'logs', 'Log Pipeline', 745, 260, 3],
    ['tr', 'tracing', 'Tracing', 745, 390, 2],
    ['slo', 'slo', 'SLO / Error Budget', 890, 130, 2],
    ['siem', 'siem', 'SIEM', 890, 260, 2],
    ['page', 'alert', 'On-call / Paging', 1035, 190, 2],
  ], [['c','lb'],['probe','lb'],['rum','otel'],['lb','gw'],['gw','svc'],['k8s','svc'],['svc','db'],
      ['svc','otel'],['gw','otel'],['k8s','otel'],['otel','met'],['otel','log'],['otel','tr'],
      ['met','slo'],['log','siem'],['slo','page'],['met','page'],['siem','page']], [
    'Four golden signals: latency, traffic, errors, saturation — per service, not just per host',
    'One OTel collector pipeline: batching, tail sampling, PII redaction in one place',
    'Correlate the three pillars with a shared trace id, or debugging stays guesswork',
    'Alert on symptoms and SLO burn rate, never on every individual cause — page fatigue is real',
    'Cardinality is the metrics cost driver; never label with user or request ids',
    'RUM shows what users actually experience; server p50 can look fine while the page is slow',
    'Synthetic probes from outside catch DNS, TLS and edge failures your internal metrics cannot see',
    'Log retention tiers: hot for days, warm for weeks, archive for compliance',
  ], 'Observability'),

  // ─────────────── India · consumer & fintech ───────────────
  T('Rapido', 'Two-wheeler ride hailing with captain matching', 12000, [
    ['r', 'client', 'Riders', 40, 170, 1, 0.35], ['cap', 'client', 'Captains', 40, 360, 1, 0.65],
    ['lb', 'lb', 'LB', 180, 265], ['gw', 'gateway', 'API Gateway', 310, 265, 3],
    ['loc', 'ws', 'Captain Location WS', 450, 380, 4],
    ['geo', 'cache', 'Geo Index (H3)', 600, 380, 3],
    ['match', 'app', 'Allocation Engine', 450, 170, 6],
    ['otp', 'micro', 'OTP / Ride Start', 600, 90, 3],
    ['trip', 'sql', 'Trips DB', 750, 170, 3],
    ['k', 'kafka', 'Ride Events', 600, 265],
    ['surge', 'analytics', 'Surge Pricing', 750, 265, 3],
    ['pay', 'micro', 'Payments', 450, 500, 3],
    ['upi', 'partner', 'UPI / PG', 600, 500, 4],
  ], [['r','lb'],['cap','lb'],['lb','gw'],['gw','loc'],['loc','geo'],['gw','match'],['match','geo'],
      ['match','trip'],['match','otp'],['loc','k'],['k','surge'],['gw','pay'],['pay','upi']], [
    'Captains ping location every few seconds — do the write-QPS math, it dwarfs ride requests',
    'Allocation: nearest captain by H3 cell, then rank on acceptance rate and ETA, not distance alone',
    'Two-wheelers move through traffic differently — ETA model must not reuse the car model',
    'OTP at ride start prevents wrong-rider pickups; store hashed, short TTL',
    'Surge from the live supply/demand ratio per cell, computed on the event stream',
    'UPI is the dominant payment rail — it is a partner API, so queue and retry, never block the ride on it',
    'Cash rides still exist: settlement and captain wallet reconciliation is a real subsystem',
  ], 'India · consumer'),

  T('Ola', 'Multi-category ride hailing with EV fleet and in-app wallet', 16000, [
    ['r', 'client', 'Riders', 40, 170, 1, 0.55], ['d', 'client', 'Driver Fleet', 40, 380, 1, 0.45],
    ['lb', 'lb', 'LB', 180, 265], ['gw', 'gateway', 'API Gateway', 310, 265, 3],
    ['fare', 'micro', 'Fare Engine', 450, 90, 3],
    ['loc', 'ws', 'Driver Location WS', 450, 380, 4],
    ['geo', 'cache', 'Geo Index (H3)', 600, 380, 3],
    ['match', 'app', 'Allocation Engine', 450, 230, 6],
    ['ev', 'micro', 'EV Range & Charging Svc', 600, 230, 2],
    ['trip', 'sql', 'Trips DB', 750, 170, 3],
    ['k', 'kafka', 'Ride Events', 600, 90],
    ['surge', 'analytics', 'Surge Pricing', 750, 90, 3],
    ['wallet', 'micro', 'Ola Money Wallet', 450, 500, 3],
    ['ledger', 'sql', 'Wallet Ledger', 600, 500, 3],
    ['upi', 'partner', 'UPI / PG', 750, 500, 4],
  ], [['r','lb'],['d','lb'],['lb','gw'],['gw','fare'],['gw','loc'],['loc','geo'],['gw','match'],
      ['match','geo'],['match','ev'],['match','trip'],['loc','k'],['k','surge'],
      ['gw','wallet'],['wallet','ledger'],['wallet','upi']], [
    'Fare is quoted per category (Mini, Sedan, Auto, electric) before a driver is even searched for — pricing and allocation are separate concerns',
    'Allocation filters the fleet by category first, then ranks on distance and acceptance rate only inside that slice',
    'Electric rides need range, not just distance: the allocation engine checks battery and nearby charging stations before offering the ride, not after',
    'Driver location pings dominate write QPS just like any ride-hailing design — now every ping also carries battery state for the electric subset',
    'Wallet balance is checked and debited before UPI is even attempted — a local ledger write is faster and fully within your control',
    'UPI is the fallback and top-up rail: a rate-limited partner API, so top-ups queue and retry rather than blocking a ride',
    'Trips DB and Wallet Ledger are separate systems of record — a ride can complete while a debit is still settling, so reconcile asynchronously, never inline',
  ], 'India · consumer'),

  T('Zomato', 'Discovery, ordering and delivery', 20000, [
    ['u', 'client', 'Users', 40, 260], ['cdn', 'cdn', 'CDN (images)', 170, 150],
    ['lb', 'lb', 'LB', 170, 340], ['gw', 'gateway', 'API Gateway', 300, 260, 4],
    ['disc', 'search', 'Discovery / Search', 440, 120, 4],
    ['menu', 'cache', 'Menu & Catalog Cache', 440, 240, 3],
    ['cat', 'nosql', 'Restaurant Catalog', 590, 240, 3],
    ['ord', 'app', 'Order Service', 440, 360, 6],
    ['odb', 'sql', 'Orders DB', 590, 360, 3],
    ['k', 'kafka', 'Order Events', 590, 470],
    ['assign', 'worker', 'Rider Assignment', 740, 470, 6],
    ['track', 'ws', 'Live Tracking', 440, 480, 4],
    ['eta', 'ml', 'ETA Model', 740, 360, 10],
    ['pay', 'micro', 'Payments', 300, 470, 3],
    ['pg', 'partner', 'Payment Gateway', 170, 470, 5],
  ], [['u','cdn'],['u','lb'],['cdn','gw'],['lb','gw'],['gw','disc'],['gw','menu'],['menu','cat'],
      ['gw','ord'],['ord','odb'],['ord','k'],['k','assign'],['gw','track'],['assign','eta'],['gw','pay'],['pay','pg']], [
    'Discovery is read-heavy and personalised; ordering is write-heavy and transactional — separate them',
    'Menus change constantly but are read enormously: cache aggressively with per-restaurant invalidation',
    'Order state machine: placed → accepted → prepared → picked → delivered, each transition an event',
    'Rider assignment is a matching problem over a moving fleet, run off the event stream',
    'ETA must combine prep time, rider travel and traffic — surface a range, not false precision',
    'Peak is brutally spiky: lunch and dinner IST, plus IPL and festival surges',
    'Images dominate bandwidth — CDN with aggressive resizing at the edge',
  ], 'India · consumer'),

  T('Swiggy + Instamart', 'Food delivery plus 10-minute dark stores', 25000, [
    ['u', 'client', 'Users', 40, 270], ['cdn', 'cdn', 'CDN', 170, 150],
    ['lb', 'lb', 'LB', 170, 380], ['gw', 'gateway', 'API Gateway', 300, 270, 5],
    ['srch', 'search', 'Search', 440, 120, 4],
    ['inv', 'cache', 'Dark Store Inventory', 440, 250, 4],
    ['invdb', 'sql', 'Inventory DB (per store)', 590, 250, 4],
    ['ord', 'app', 'Order Service', 440, 380, 8],
    ['odb', 'nosql', 'Orders Store', 590, 380, 4],
    ['k', 'kafka', 'Events', 590, 500],
    ['disp', 'worker', 'Dispatch Engine', 740, 500, 8],
    ['geo', 'cache', 'Rider Geo Index', 890, 500, 3],
    ['track', 'ws', 'Live Tracking', 440, 500, 5],
    ['eta', 'ml', 'ETA / Routing', 740, 380, 12],
    ['pg', 'partner', 'Payments / UPI', 300, 500, 6],
  ], [['u','cdn'],['u','lb'],['cdn','gw'],['lb','gw'],['gw','srch'],['gw','inv'],['inv','invdb'],
      ['gw','ord'],['ord','odb'],['ord','k'],['k','disp'],['disp','geo'],['gw','track'],['disp','eta'],['ord','pg']], [
    'Instamart inventory is per dark store and must be reserved atomically — oversell is a refund and a lost customer',
    'Serviceability check first: is this pincode/store open and in range, before anything else renders',
    '10-minute promise means dispatch decides before the order is even picked',
    'Batching: one rider carries multiple orders — the assignment problem is combinatorial, solve greedily with constraints',
    'Store-level sharding keeps a hot store from taking down the region',
    'Separate read models for browse vs the transactional order path',
    'Refunds and cancellations are as much of the system as the happy path',
  ], 'India · consumer'),

  T('Razorpay', 'Payment gateway with smart routing and settlement', 4000, [
    ['m', 'client', 'Merchants', 40, 270], ['waf', 'waf', 'WAF', 170, 270, 2],
    ['gw', 'gateway', 'API Gateway', 300, 270, 3],
    ['rl', 'ratelimiter', 'Rate Limiter', 300, 150, 2],
    ['co', 'micro', 'Checkout Service', 440, 150, 4],
    ['pay', 'app', 'Payment Service', 440, 270, 6],
    ['idem', 'cache', 'Idempotency Keys', 590, 150, 3],
    ['led', 'sql', 'Double-entry Ledger', 590, 270, 4],
    ['out', 'queue', 'Outbox', 440, 400],
    ['rout', 'worker', 'Smart Routing', 590, 400, 4],
    ['acq', 'partner', 'Acquirers / Banks / UPI', 740, 400, 8],
    ['hook', 'worker', 'Webhook Delivery', 590, 520, 4],
    ['sett', 'scheduler', 'Settlement Jobs', 300, 400, 2],
    ['aud', 'audit', 'Audit Log', 740, 270, 2],
  ], [['m','waf'],['waf','gw'],['gw','rl'],['rl','co'],['gw','pay'],['pay','idem'],['pay','led'],
      ['pay','out'],['out','rout'],['rout','acq'],['out','hook'],['sett','led'],['pay','aud']], [
    'Idempotency key on every mutating call — merchants retry, and a double charge is unforgivable',
    'Double-entry ledger, append-only: every paisa debited has a matching credit',
    'Outbox pattern so the DB commit and the bank call can never diverge',
    'Smart routing across acquirers on success rate and cost — banks degrade constantly in India',
    'Webhooks need signed payloads, exponential backoff and a replay endpoint',
    'T+1 settlement with reconciliation against bank files; mismatches are a daily operational reality',
    'PCI scope: tokenize card data so most services never touch a PAN',
    'Bank APIs are the least reliable component — circuit break and degrade, never queue user-visibly',
  ], 'India · fintech'),

  T('BHIM (UPI)', 'UPI payments through the NPCI switch', 6000, [
    ['u', 'client', 'Users', 40, 270], ['lb', 'lb', 'LB', 170, 270],
    ['gw', 'gateway', 'API Gateway', 300, 270, 3],
    ['iam', 'iam', 'Device Binding / SIM', 300, 140, 3],
    ['upi', 'micro', 'UPI Transaction Svc', 440, 270, 6],
    ['vpa', 'cache', 'VPA Directory Cache', 440, 140, 3],
    ['hsm', 'hsm', 'HSM (UPI PIN)', 590, 140, 2],
    ['npci', 'partner', 'NPCI Switch', 740, 270, 8],
    ['bank', 'partner', 'Remitter / Beneficiary Bank', 890, 270, 8],
    ['led', 'sql', 'Transaction Ledger', 590, 400, 3],
    ['k', 'kafka', 'Txn Events', 440, 400],
    ['notif', 'micro', 'Notifications', 590, 520, 3],
    ['aud', 'audit', 'Audit / Dispute Trail', 740, 400, 2],
  ], [['u','lb'],['lb','gw'],['gw','iam'],['gw','upi'],['upi','vpa'],['upi','hsm'],['upi','npci'],
      ['npci','bank'],['upi','led'],['upi','k'],['k','notif'],['upi','aud']], [
    'UPI PIN never leaves the HSM boundary — the app captures an encrypted PIN block only',
    'Device binding to the SIM is the first factor; re-bind on SIM change',
    'Every leg is a partner call: PSP → NPCI → remitter bank → beneficiary bank. Latency is theirs, not yours',
    'Deemed-approved and pending states are normal — build reversal and refund flows, not just success',
    'Idempotency on the RRN; the same transaction may be retried by the switch',
    'NPCI enforces TPS caps and success-rate thresholds — throttle yourself before they do',
    'Chargeback/dispute (URCS) handling needs an immutable audit trail',
  ], 'India · fintech'),

  T('Google Pay (UPI, India)', 'UPI at national scale with fraud and rewards', 30000, [
    ['u', 'client', 'Users', 40, 280], ['gslb', 'gslb', 'Global Traffic Mgr', 170, 280],
    ['cdn', 'cdn', 'CDN', 300, 150], ['lb', 'lb', 'LB', 300, 400, 2],
    ['gw', 'gateway', 'API Gateway', 440, 280, 6],
    ['iam', 'iam', 'Identity / Device', 440, 150, 4],
    ['upi', 'micro', 'UPI Core', 590, 280, 10],
    ['hsm', 'hsm', 'HSM', 590, 150, 3],
    ['tok', 'pii', 'Tokenization Vault', 740, 150, 3],
    ['psp', 'micro', 'PSP Bank Router', 740, 280, 6],
    ['npci', 'partner', 'NPCI Switch', 890, 280, 20],
    ['k', 'kafka', 'Txn Stream', 590, 420],
    ['fraud', 'ml', 'Fraud Scoring', 740, 420, 20],
    ['txn', 'nosql', 'Txn Store', 890, 420, 4],
    ['rew', 'micro', 'Rewards / Scratch Cards', 440, 530, 4],
    ['notif', 'micro', 'Notifications', 300, 530, 4],
  ], [['u','gslb'],['gslb','cdn'],['gslb','lb'],['cdn','gw'],['lb','gw'],['gw','iam'],['gw','upi'],
      ['upi','hsm'],['upi','psp'],['psp','npci'],['upi','k'],['k','fraud'],['k','txn'],['k','rew'],['k','notif'],['psp','tok']], [
    'Multiple PSP banks behind one app — route on live bank health, failover mid-session',
    'Peak is national and correlated: festival and salary-day spikes hit every bank at once',
    'Fraud scoring must run inline for risky flows and async for the rest — you cannot afford 20ms everywhere',
    'Rewards are eventually consistent and must never delay or block the payment',
    'Collect requests and mandates (autopay) are a separate, abuse-prone flow',
    'NPCI publishes bank-wise success rates — routing on them is a real competitive advantage',
    'Every rupee movement is reconciled daily against the switch; unreconciled is an incident',
  ], 'India · fintech'),


  T('Video Surveillance (VMS)', 'Continuous camera ingest, retention and search', 6000, [
    ['cam', 'client', 'Cameras', 40, 250, 1, 0.9],
    ['op', 'client', 'Operators', 40, 430, 1, 0.1],
    ['edge', 'app', 'Edge Recorder', 190, 250, 12],
    ['gw', 'gateway', 'Ingest Gateway', 350, 250, 6],
    ['iam', 'app', 'Access Control', 350, 430, 3],
    ['seg', 'worker', 'Segmenter', 510, 160, 10],
    ['blob', 'blob', 'Segment Store', 690, 160, 3],
    ['life', 'scheduler', 'Retention Job', 850, 160, 6],
    ['det', 'ml', 'Motion / Object Detect', 510, 330, 8],
    ['ev', 'kafka', 'Event Stream', 690, 330, 4],
    ['meta', 'nosql', 'Event Index', 850, 330, 4],
    ['view', 'app', 'Review & Export', 510, 470, 4],
    ['audit', 'audit', 'Access Audit Log', 690, 470, 3],
  ], [['cam','edge'],['edge','gw'],['gw','seg'],['seg','blob'],['blob','life'],
      ['gw','det'],['det','ev'],['ev','meta'],
      ['op','iam'],['iam','view'],['view','meta'],['view','blob'],['view','audit']], [
    'Cameras never stop — ingest is a constant write load, not a request/response workload',
    'Segment the stream into short chunks so storage, retention and export all operate on the same unit',
    'Run detection on the stream, not on stored video: re-scanning the archive costs orders of magnitude more',
    'Retention is the design. Storage grows linearly forever unless something deletes on a schedule',
    'Index events, not frames — searching "person, camera 12, Tuesday" must never scan video',
    'Every operator view of footage is itself an event worth logging',
  ], 'Product designs'),

  T('Job Scheduler (Airflow-like)', 'Cron, DAGs and exactly-once-ish execution', 3000, [
    ['c', 'client', 'Authors / Triggers', 40, 260, 1, 1],
    ['api', 'gateway', 'Scheduler API', 190, 260, 3],
    ['meta', 'sql', 'DAG & Run State', 350, 380, 3],
    ['sched', 'scheduler', 'Scheduler Loop', 350, 180, 3],
    ['lock', 'zk', 'Leader Election', 510, 90, 3],
    ['q', 'kafka', 'Task Queue', 510, 260, 6],
    ['w', 'worker', 'Workers', 690, 260, 20],
    ['res', 'blob', 'Task Logs & Artifacts', 850, 260, 3],
    ['ev', 'queue', 'Run Events', 690, 400, 4],
    ['obs', 'analytics', 'Run History', 850, 400, 3],
  ], [['c','api'],['api','meta'],['sched','meta'],['sched','lock'],['sched','q'],
      ['q','w'],['w','res'],['w','meta'],['w','ev'],['ev','obs']], [
    'One scheduler decides what is due — several deciding at once double-runs every task',
    'A task must be safe to run twice: the queue guarantees at-least-once, never exactly-once',
    'A DAG is a dependency graph, so a task runs only when every upstream run has succeeded',
    'Workers die mid-task, so a run needs a lease and a heartbeat rather than an assumption',
    'Backfilling a year of missed runs must not starve today\'s work',
    'Retries need backoff and a cap, or one broken task becomes a queue full of itself',
  ], 'Product designs'),

  T('OS Update Delivery (OTA)', 'Shipping a new OS to a billion devices without bricking any', 120000, [
    ['dev', 'client', 'Devices', 40, 260, 1, 1],
    ['gslb', 'gslb', 'Global Traffic Mgr', 180, 260, 1],
    ['chk', 'gateway', 'Update Check API', 330, 260, 12],
    ['cohort', 'app', 'Rollout Controller', 330, 420, 60],
    ['flag', 'featureflag', 'Staged Rollout Rules', 490, 420, 3],
    ['man', 'cache', 'Manifest Cache', 490, 150, 8],
    ['meta', 'nosql', 'Device & Version State', 490, 300, 6],
    ['cdn', 'cdn', 'Payload CDN', 660, 150, 1],
    ['blob', 'blob', 'Signed Payloads', 830, 150, 3],
    ['sign', 'sign', 'Release Signing', 830, 300, 2],
    ['tel', 'kafka', 'Install Telemetry', 660, 420, 8],
    ['halt', 'analytics', 'Failure Detector', 830, 420, 44],
  ], [['dev','gslb'],['gslb','chk'],['chk','man'],['chk','meta'],['chk','cohort'],
      ['cohort','flag'],['cohort','meta'],['man','cdn'],['cdn','blob'],['blob','sign'],
      ['dev','tel'],['tel','halt'],['halt','cohort']], [
    'The check-in is the load, not the download — every device asks, few are told yes',
    'Stagger check-ins with jitter or a billion devices ask at the same instant',
    'Ship deltas against the exact installed version, not the full image',
    'Roll out in cohorts: 1%, then 5%, then everyone, and only if telemetry stays clean',
    'The failure detector must be able to halt a rollout automatically, not just alert',
    'Payloads are signed and verified on-device — the CDN is untrusted by design',
    'Every update must be able to roll back, because some will need to',
  ], 'Product designs'),

  // ─────────────── quality & testing ───────────────
  T('Continuous Testing Platform', 'Shift-left pipeline: gates, suites, environments', 500, [
    ['dev', 'client', 'Developers / PRs', 40, 320, 1, 0.8],
    ['sched', 'scheduler', 'Nightly / Scheduled', 40, 500, 1, 0.2],
    ['ci', 'cicd', 'CI/CD Pipeline', 185, 400, 6],
    ['qgate', 'qgate', 'Quality Gate (SAST)', 325, 190, 4],
    ['unit', 'apitest', 'Unit + API Suite', 325, 320, 12],
    ['contract', 'contract', 'Contract Tests', 325, 450, 4],
    ['e2e', 'e2e', 'UI Journeys', 325, 580, 8],
    ['dast', 'dast', 'Security Scan (DAST)', 325, 700, 3],
    ['mock', 'mock', 'Service Virtualization', 465, 250, 6],
    ['data', 'testdata', 'Test Data Mgmt', 465, 380, 6],
    ['env', 'k8s', 'Ephemeral Test Env', 605, 320, 4],
    ['sut', 'micro', 'System Under Test', 745, 320, 8],
    ['sutdb', 'sql', 'Seeded Database', 885, 320, 3],
    ['grid', 'devicefarm', 'Device / Browser Grid', 465, 580, 8],
    ['load', 'load', 'Load & Perf Test', 465, 700, 3],
    ['ops', 'testops', 'Test Reporting', 745, 580, 4],
    ['mon', 'monitor', 'Env Health', 885, 580, 2],
  ], [['dev','ci'],['sched','ci'],['ci','qgate'],['ci','unit'],['ci','contract'],['ci','e2e'],['ci','dast'],
      ['unit','mock'],['unit','data'],['e2e','grid'],['e2e','env'],['unit','env'],['env','sut'],['sut','sutdb'],
      ['load','env'],['e2e','ops'],['unit','ops'],['contract','ops'],['load','ops'],['dast','ops'],['env','mon']], [
    'Test pyramid, not an ice-cream cone: most coverage in fast API and unit tests, a thin layer of UI journeys on top',
    'Every layer must be able to fail the build — a test suite nobody blocks on is documentation',
    'Ephemeral environments per pull request beat one shared staging that is always broken by someone else',
    'Virtualize third parties: a suite that calls a partner sandbox is slow, rate-limited and red for reasons that are not yours',
    'Test data is the top cause of flake — seed it per run, mask production data, never share mutable fixtures',
    'Contract tests catch a breaking API change at build time; without them you find it when the consumer deploys',
    'Track flake rate as a first-class metric and quarantine flaky tests, because a suite people re-run on red is a suite people ignore',
    'Load test against a production-like environment — results from a half-sized environment are worse than no results',
    'Shift left for speed and shift right for truth: synthetic probes and real-user monitoring keep testing after release',
  ], 'Quality & testing'),

  // ─────────────── travel & booking ───────────────
  T('Booking.com', 'Hotel availability, pricing and reservation', 40000, [
    ['u', 'client', 'Travellers', 40, 280], ['gslb', 'gslb', 'Global Traffic Mgr', 170, 280],
    ['cdn', 'cdn', 'CDN', 300, 150], ['lb', 'lb', 'LB', 300, 400, 2],
    ['gw', 'gateway', 'API Gateway', 440, 280, 8],
    ['srch', 'search', 'Availability Search', 590, 150, 8],
    ['rate', 'cache', 'Rate & Availability Cache', 590, 280, 8],
    ['rank', 'ml', 'Ranking / Personalisation', 740, 150, 24],
    ['inv', 'micro', 'Inventory Service', 740, 280, 6],
    ['sup', 'partner', 'Supplier / Channel Manager', 890, 280, 12],
    ['book', 'saga', 'Booking Saga', 590, 420, 6],
    ['bdb', 'sql', 'Reservations DB', 740, 420, 4],
    ['pay', 'partner', 'Payments / PSP', 590, 540, 8],
    ['k', 'kafka', 'Booking Events', 890, 420],
  ], [['u','gslb'],['gslb','cdn'],['gslb','lb'],['cdn','gw'],['lb','gw'],['gw','srch'],['gw','rate'],
      ['srch','rank'],['rate','inv'],['inv','sup'],['gw','book'],['book','bdb'],['book','pay'],['book','k']], [
    'Search:book ratio is enormous (1000:1) — optimise the read path first and hardest',
    'Availability is owned by suppliers: cache with short TTL and reconcile on booking, expect the occasional failure',
    'Never oversell — the booking transaction re-validates against the supplier before confirming',
    'Ranking drives revenue; it is a personalised ML problem sitting on the hot path',
    'Price is currency-, tax- and date-dependent — cache keys are subtler than they look',
    'Cancellation policy and free-cancellation windows are core domain state, not a flag',
    'Supplier APIs are slow and flaky: fan out with timeouts and partial results',
  ], 'Travel & booking'),

  T('Goibibo', 'OTA — flight and hotel search over GDS suppliers', 15000, [
    ['u', 'client', 'Users', 40, 280], ['cdn', 'cdn', 'CDN', 170, 160],
    ['lb', 'lb', 'LB', 170, 400], ['gw', 'gateway', 'API Gateway', 300, 280, 5],
    ['fs', 'micro', 'Flight Search Fan-out', 440, 160, 8],
    ['fare', 'cache', 'Fare Cache', 590, 160, 6],
    ['gds', 'partner', 'GDS / Airline APIs', 740, 160, 12],
    ['hs', 'search', 'Hotel Search', 440, 300, 5],
    ['hsup', 'partner', 'Hotel Suppliers', 590, 300, 8],
    ['book', 'saga', 'Booking Orchestrator', 440, 430, 5],
    ['pnr', 'sql', 'PNR / Bookings DB', 590, 430, 3],
    ['pay', 'partner', 'Payments / UPI', 740, 430, 8],
    ['wal', 'micro', 'goCash Wallet', 300, 430, 3],
    ['k', 'kafka', 'Events', 590, 540],
  ], [['u','cdn'],['u','lb'],['cdn','gw'],['lb','gw'],['gw','fs'],['fs','fare'],['fare','gds'],
      ['gw','hs'],['hs','hsup'],['gw','book'],['book','pnr'],['book','pay'],['book','wal'],['book','k']], [
    'Flight search fans out to many suppliers with hard timeouts — return partial results rather than nothing',
    'Fare cache with very short TTL; airlines reprice constantly and a stale fare means a failed booking',
    'Price-change-on-booking is a first-class UX flow, not an error case',
    'Booking is a saga: hold seat → charge → issue PNR, each step compensatable',
    'Wallet (goCash) plus gateway means split tender — the ledger must balance across both',
    'GDS calls are metered and expensive: every search costs real money, so cache and rate-limit hard',
    'Cancellations and reschedules go back through the supplier and often fail — build for manual reconciliation',
  ], 'Travel & booking'),

  T('IndiGo (goindigo.in)', 'Airline direct booking over a PSS core', 8000, [
    ['u', 'client', 'Passengers', 40, 280], ['waf', 'waf', 'WAF / Bot Defence', 170, 280, 2],
    ['cdn', 'cdn', 'CDN', 300, 150], ['lb', 'lb', 'LB', 300, 400],
    ['gw', 'gateway', 'API Gateway', 440, 280, 4],
    ['avail', 'micro', 'Availability Service', 590, 150, 6],
    ['fare', 'micro', 'Fare / Pricing Engine', 590, 280, 6],
    ['seat', 'cache', 'Seat Map Cache', 740, 150, 3],
    ['book', 'saga', 'Booking / PNR Saga', 590, 400, 4],
    ['pss', 'mainframe', 'PSS Core (inventory)', 890, 280, 2],
    ['mq', 'mq', 'Enterprise MQ', 740, 280, 4],
    ['pnr', 'sql', 'PNR Store', 740, 400, 3],
    ['pay', 'partner', 'Payments / UPI', 590, 520, 6],
    ['anc', 'micro', 'Ancillaries (bags, meals)', 440, 520, 3],
    ['ci', 'micro', 'Web Check-in', 440, 400, 4],
    ['k', 'kafka', 'Ops Events', 890, 400],
  ], [['u','waf'],['waf','cdn'],['waf','lb'],['cdn','gw'],['lb','gw'],['gw','avail'],['avail','seat'],
      ['gw','fare'],['fare','mq'],['mq','pss'],['gw','book'],['book','pnr'],['book','pay'],['gw','anc'],['gw','ci'],['book','k']], [
    'The PSS core is the single source of inventory truth and cannot be scaled out — cache reads, queue writes',
    'Availability and price are read enormously more than they are booked; cache by route+date',
    'Seat maps are per-flight state that changes as people check in — short TTL and optimistic locking',
    'Ancillaries (bags, seats, meals) are a large share of revenue and a separate purchase flow post-booking',
    'Check-in opens on a schedule and creates a predictable thundering herd — pre-warm and queue',
    'Bot traffic scraping fares is a real load problem; WAF and per-IP fare-search budgets',
    'Disruption (delay, cancel, reaccommodation) is an event-driven workflow across the whole fleet',
  ], 'Travel & booking'),

  // ─────────────── big tech ───────────────
  T('Meta (Facebook)', 'Social graph, feed ranking and photo storage', 60000, [
    ['u', 'client', 'Users', 40, 300], ['pop', 'gslb', 'Edge PoP', 170, 300, 2],
    ['cdn', 'cdn', 'Photo CDN', 300, 160, 4], ['lb', 'lb', 'LB', 300, 440, 2],
    ['web', 'web', 'Web Tier (Hack)', 440, 300, 24],
    ['tao', 'cache', 'TAO Graph Cache', 590, 200, 8],
    ['mc', 'cache', 'Memcache Tier', 590, 320, 8],
    ['db', 'sql', 'Sharded MySQL', 740, 260, 20],
    ['feed', 'app', 'Feed Aggregator', 440, 460, 20],
    ['rank', 'ml', 'Feed Ranker', 590, 460, 60],
    ['ads', 'micro', 'Ads Serving', 440, 580, 12],
    ['haystack', 'blob', 'Haystack Photo Store', 740, 120, 4],
    ['msg', 'ws', 'Messaging', 300, 580, 6],
    ['k', 'kafka', 'Scribe / Event Log', 740, 460, 2],
    ['wh', 'warehouse', 'Hive Warehouse', 890, 460, 8],
  ], [['u','pop'],['pop','cdn'],['pop','lb'],['cdn','haystack'],['lb','web'],['web','tao'],['web','mc'],
      ['tao','db'],['mc','db'],['lb','feed'],['feed','rank'],['lb','ads'],['lb','msg'],['feed','k'],['k','wh']], [
    'The social graph is the primitive: TAO is a read-through cache over sharded MySQL, and it absorbs ~99% of reads',
    'Feed is a ranking problem, not a storage problem — thousands of candidates scored per view',
    'Photos are write-once read-forever: Haystack removes per-file metadata overhead, CDN serves the rest',
    'Shard by user id; cross-shard queries are the thing you design around, not with',
    'Cache invalidation across regions is the hard part — accept a stale window and make it small',
    'Every product surface writes to one event log; the warehouse is downstream of it, never inline',
    'Estimate: 3B users, feed views dominate reads by orders of magnitude over writes',
  ], 'Big tech'),

  T('Netflix', 'Streaming, playback and the microservice fleet', 40000, [
    ['u', 'client', 'Devices', 40, 300], ['oc', 'cdn', 'Open Connect CDN', 180, 160, 12],
    ['gslb', 'gslb', 'Global Steering', 180, 440, 2],
    ['zuul', 'gateway', 'Zuul Gateway', 320, 300, 16],
    ['reg', 'registry', 'Eureka Discovery', 320, 160, 3],
    ['api', 'micro', 'API / BFF', 460, 300, 20],
    ['play', 'micro', 'Playback + DRM', 460, 440, 12],
    ['evc', 'cache', 'EVCache', 610, 220, 8],
    ['cass', 'nosql', 'Cassandra', 610, 380, 8],
    ['rec', 'ml', 'Recommendations', 610, 520, 40],
    ['k', 'kafka', 'Keystone Stream', 460, 600, 2],
    ['ing', 'worker', 'Encoding Pipeline', 760, 600, 12],
    ['s3', 'blob', 'Title Assets', 900, 600, 2],
    ['mon', 'monitor', 'Atlas Metrics', 760, 460, 2],
  ], [['u','oc'],['u','gslb'],['gslb','zuul'],['zuul','reg'],['zuul','api'],['zuul','play'],
      ['api','evc'],['api','cass'],['api','rec'],['play','cass'],['api','k'],['k','ing'],['ing','s3'],['s3','oc'],['api','mon']], [
    'Open Connect appliances sit inside ISPs — the video never crosses the public backbone twice',
    'The API tier is stateless and disposable; state lives in Cassandra and EVCache only',
    'Playback authorisation and DRM licensing are separate from browse — different SLOs entirely',
    'Encoding is a huge offline pipeline: every title in dozens of bitrates and codecs',
    'Fail fast and degrade: no recommendations is a worse home page, not an outage',
    'Chaos testing is routine here — instance, zone and region failures are exercised in production',
    'Multi-region active-active with traffic steering; evacuate a region rather than debug it live',
  ], 'Big tech'),

  T('Yahoo', 'Portal, mail, search and ad serving', 30000, [
    ['u', 'client', 'Users', 40, 300], ['cdn', 'cdn', 'CDN', 175, 170, 4],
    ['lb', 'lb', 'LB', 175, 430, 2], ['gw', 'gateway', 'Front Door', 310, 300, 8],
    ['portal', 'web', 'Portal / Content', 450, 160, 12],
    ['cms', 'nosql', 'Content Store', 600, 100, 4],
    ['mail', 'app', 'Mail Service', 450, 300, 16],
    ['mbox', 'nosql', 'Mailbox Store (HBase)', 600, 300, 12],
    ['idx', 'search', 'Search Index', 450, 440, 8],
    ['ads', 'micro', 'Ad Serving', 450, 570, 10],
    ['budget', 'cache', 'Budget / Pacing', 600, 570, 4],
    ['k', 'kafka', 'Event Bus (Pulsar)', 740, 440, 2],
    ['an', 'analytics', 'Clickstream Analytics', 880, 440, 6],
    ['wh', 'warehouse', 'Warehouse', 880, 570, 4],
  ], [['u','cdn'],['u','lb'],['cdn','gw'],['lb','gw'],['gw','portal'],['portal','cms'],
      ['gw','mail'],['mail','mbox'],['gw','idx'],['gw','ads'],['ads','budget'],['ads','k'],['k','an'],['an','wh']], [
    'A portal is many products behind one front door — isolate them so mail cannot take down news',
    'Mailboxes are enormous, per-user and append-heavy: partition by user, never scan across',
    'Ad serving has a hard latency budget (tens of ms) and must never block page render',
    'Budget pacing is shared mutable state — the classic hot-key problem in ad tech',
    'Content is read-mostly and highly cacheable; personalise at the edge, not the origin',
    'Clickstream is the business: every impression and click streams to analytics',
    'Legacy plus acquisitions means many stacks — the front door is where you enforce consistency',
  ], 'Big tech'),

  T('Disney+ Hotstar', 'Record live-cricket concurrency', 200000, [
    ['u', 'client', 'Viewers', 40, 320], ['gslb', 'gslb', 'Multi-CDN Steering', 170, 320, 3],
    ['cdn1', 'cdn', 'CDN A', 310, 170, 8], ['cdn2', 'cdn', 'CDN B', 310, 470, 8],
    ['waf', 'waf', 'WAF / Bot', 450, 320, 6],
    ['gw', 'gateway', 'API Gateway', 590, 320, 40],
    ['play', 'micro', 'Playback / Token', 730, 200, 30],
    ['cache', 'cache', 'Edge Config Cache', 870, 200, 6],
    ['pers', 'micro', 'Personalisation', 730, 440, 20],
    ['prof', 'nosql', 'Profile Store', 870, 440, 8],
    ['ssai', 'micro', 'Ad Insertion (SSAI)', 730, 570, 20],
    ['chat', 'ws', 'Live Chat / Reactions', 590, 570, 12],
    ['k', 'kafka', 'Event Stream', 870, 570, 3],
    ['auto', 'k8s', 'Predictive Autoscaler', 590, 130, 4],
    ['pay', 'partner', 'Payments / UPI', 450, 570, 12],
  ], [['u','gslb'],['gslb','cdn1'],['gslb','cdn2'],['cdn1','waf'],['cdn2','waf'],['waf','gw'],
      ['gw','play'],['play','cache'],['gw','pers'],['pers','prof'],['gw','ssai'],['gw','chat'],
      ['auto','gw'],['ssai','k'],['pay','gw']], [
    'Concurrency, not requests, is the metric — tens of millions of viewers on a single ball',
    'Traffic does not ramp: a wicket adds millions of viewers in seconds, so scale predictively, not reactively',
    'Multi-CDN with live steering — no single CDN has the headroom, and one will degrade mid-match',
    'Graceful degradation ladder: drop personalisation, then recommendations, then chat — never playback',
    'Pre-warm and cache the playback config; a config lookup per viewer is a self-inflicted DDoS',
    'Panic mode: serve a static, cacheable experience when the system is past its limit',
    'Ad insertion is server-side so it cannot be blocked, but it sits on the critical path — budget for it',
    'The tail is brutal: p99 matters more than average when everyone is watching the same second',
  ], 'Big tech'),

  // ─────────────── more product designs ───────────────
  T('News Feed (Instagram)', 'Media-heavy feed with hybrid fan-out', 50000, [
    ['u', 'client', 'Users', 40, 300], ['cdn', 'cdn', 'Media CDN', 175, 160, 8],
    ['lb', 'lb', 'LB', 175, 440, 2], ['gw', 'gateway', 'API Gateway', 310, 300, 12],
    ['feed', 'app', 'Feed Service', 450, 200, 16],
    ['tl', 'cache', 'Timeline Cache', 600, 130, 8],
    ['rank', 'ml', 'Feed Ranker', 600, 250, 40],
    ['graph', 'cache', 'Social Graph', 600, 370, 6],
    ['post', 'app', 'Post / Upload', 450, 430, 14],
    ['meta', 'nosql', 'Post Metadata', 600, 490, 6],
    ['blob', 'blob', 'Media Store', 750, 430, 3],
    ['q', 'queue', 'Transcode Queue', 450, 560],
    ['tw', 'worker', 'Transcoders', 600, 610, 12],
    ['k', 'kafka', 'Engagement Events', 310, 560, 2],
    ['fan', 'worker', 'Fan-out Workers', 175, 610, 12],
  ], [['u','cdn'],['u','lb'],['cdn','gw'],['lb','gw'],['gw','feed'],['feed','tl'],['feed','rank'],
      ['feed','graph'],['gw','post'],['post','meta'],['post','q'],['q','tw'],['tw','blob'],['blob','cdn'],
      ['post','k'],['k','fan'],['fan','tl']], [
    'Hybrid fan-out: push to followers on write, pull for accounts with millions of followers',
    'The timeline cache holds post ids only — hydrate content on read so edits and deletes propagate',
    'Media dominates bytes and cost: transcode to multiple sizes once, serve from CDN forever',
    'Ranking is on the hot path; budget for it and degrade to chronological if it is slow',
    'Stories and reels have a TTL — different storage lifecycle from permanent posts',
    'Engagement events feed the ranker: the loop between serving and training is the product',
    'Estimate: reads outnumber writes ~100:1, and each read fans out to dozens of media objects',
  ]),

  T('Music Streaming (Spotify)', 'Audio delivery, catalogue and recommendations', 40000, [
    ['u', 'client', 'Listeners', 40, 300], ['cdn', 'cdn', 'Audio CDN', 175, 160, 10],
    ['lb', 'lb', 'LB', 175, 440, 2], ['gw', 'gateway', 'API Gateway', 310, 300, 10],
    ['play', 'micro', 'Playback + Licensing', 450, 160, 10],
    ['cat', 'cache', 'Catalogue Cache', 450, 290, 8],
    ['catdb', 'nosql', 'Catalogue Store', 600, 290, 4],
    ['lib', 'sql', 'User Library / Playlists', 600, 400, 6],
    ['srch', 'search', 'Search', 450, 400, 6],
    ['rec', 'ml', 'Recommendations', 600, 520, 30],
    ['k', 'kafka', 'Play Events', 450, 520, 2],
    ['audio', 'blob', 'Encoded Audio', 750, 160, 3],
    ['roy', 'etl', 'Royalty Reporting', 750, 520, 6],
    ['wh', 'warehouse', 'Analytics Warehouse', 890, 520, 6],
  ], [['u','cdn'],['u','lb'],['cdn','gw'],['lb','gw'],['gw','play'],['play','audio'],['audio','cdn'],
      ['gw','cat'],['cat','catdb'],['gw','srch'],['gw','lib'],['gw','rec'],['play','k'],['k','roy'],['roy','wh']], [
    'Licensing gates playback per track, per market — a rights check on every start',
    'Audio is immutable and cacheable forever; the catalogue metadata is what changes',
    'Prefetch the next track and buffer aggressively — rebuffering is the churn metric',
    'Offline downloads mean encrypted local copies and a licence refresh on reconnect',
    'Every play is a royalty event: the reporting pipeline must not lose or double-count one',
    'Recommendations blend collaborative filtering with audio features and editorial curation',
    'Estimate: 100M listeners × 20 tracks/day ≈ 23k plays/s average, far more at peak',
  ]),

  T('Distributed File Storage (Drive)', 'Chunked storage, sharing and sync', 15000, [
    ['u', 'client', 'Clients', 40, 300], ['lb', 'lb', 'LB', 175, 300, 2],
    ['gw', 'gateway', 'API Gateway', 310, 300, 8],
    ['meta', 'app', 'Metadata Service', 450, 180, 10],
    ['mdb', 'sql', 'Metadata DB', 600, 120, 6],
    ['acl', 'micro', 'Permissions / ACL', 450, 300, 8],
    ['aclc', 'cache', 'ACL Cache', 600, 300, 4],
    ['blk', 'app', 'Block Service', 450, 420, 10],
    ['blob', 'blob', 'Chunk Store', 600, 420, 3],
    ['dedup', 'worker', 'Chunk Dedup / Hash', 750, 420, 8],
    ['srch', 'search', 'Content Search', 600, 540, 6],
    ['ws', 'ws', 'Sync Notifications', 310, 540, 6],
    ['k', 'kafka', 'Change Log', 450, 540, 2],
    ['bak', 'backup', 'Versions / Trash', 750, 120, 2],
  ], [['u','lb'],['lb','gw'],['gw','meta'],['meta','mdb'],['gw','acl'],['acl','aclc'],['gw','blk'],
      ['blk','blob'],['blk','dedup'],['meta','k'],['k','ws'],['k','srch'],['mdb','bak']], [
    'Split files into content-hashed chunks — dedup across users and delta-sync only what changed',
    'Metadata and bytes are different systems with different scaling and consistency needs',
    'Permissions are the hard part: inherited folder ACLs, sharing links, and a cache you must invalidate correctly',
    'A change log drives sync fan-out to every device; clients reconcile from a cursor',
    'Conflicts create a copy, never a silent overwrite',
    'Versioning and trash are product features and a storage cost — set retention deliberately',
    'Search must respect ACLs at query time, not filter after the fact',
  ]),

  // ─────────────── workplace & email ───────────────
  T('Slack', 'Real-time messaging across workspaces', 30000, [
    ['u', 'client', 'Users', 40, 300], ['gslb', 'gslb', 'Global Steering', 175, 300, 2],
    ['lb', 'lb', 'LB (sticky)', 310, 420, 2], ['gw', 'gateway', 'API Gateway', 310, 180, 10],
    ['iam', 'iam', 'SSO / SCIM', 450, 90, 3],
    ['ten', 'tenant', 'Workspace Router', 450, 300, 6],
    ['ws', 'ws', 'WebSocket Fleet', 450, 420, 20],
    ['msg', 'micro', 'Channel / Message Svc', 600, 300, 16],
    ['store', 'nosql', 'Message Store', 750, 300, 10],
    ['pres', 'cache', 'Presence / Typing', 600, 420, 6],
    ['srch', 'search', 'Message Search', 750, 180, 8],
    ['files', 'blob', 'File Uploads', 750, 420, 3],
    ['k', 'kafka', 'Event Bus', 600, 540, 2],
    ['hooks', 'worker', 'Apps / Webhooks', 750, 540, 8],
    ['push', 'micro', 'Push Notifications', 890, 540, 6],
  ], [['u','gslb'],['gslb','gw'],['gslb','lb'],['lb','ws'],['gw','iam'],['gw','ten'],['ten','msg'],
      ['ws','pres'],['msg','store'],['msg','srch'],['msg','k'],['gw','files'],['k','hooks'],['k','push']], [
    'One long-lived WebSocket per client; sticky routing and a session registry to find them',
    'Workspace is the tenancy boundary — shard by it and keep the blast radius inside one org',
    'Channel fan-out is the write amplifier: a message in a 10k-member channel is 10k deliveries',
    'Presence and typing are ephemeral and enormous in volume — never persist them',
    'Search must be per-workspace and permission-aware, including private channels and DMs',
    'Apps and webhooks are untrusted third parties: isolate, rate-limit and time them out',
    'Unread state per user per channel is deceptively expensive to keep correct',
  ], 'Workplace & email'),

  T('Microsoft 365', 'Enterprise suite behind one identity and API', 25000, [
    ['u', 'client', 'Org Users', 40, 320], ['gslb', 'gslb', 'Global Traffic Mgr', 175, 320, 2],
    ['waf', 'waf', 'WAF', 310, 320, 4],
    ['entra', 'iam', 'Entra ID', 450, 170, 6],
    ['graph', 'gateway', 'Graph API', 450, 320, 14],
    ['ten', 'tenant', 'Tenant Router', 600, 320, 6],
    ['exch', 'app', 'Exchange / Mail', 750, 180, 12],
    ['mbox', 'nosql', 'Mailbox Store', 890, 180, 10],
    ['spo', 'app', 'SharePoint / OneDrive', 750, 320, 12],
    ['files', 'blob', 'File Store', 890, 320, 3],
    ['teams', 'ws', 'Teams Realtime', 750, 460, 12],
    ['srch', 'search', 'Unified Search', 890, 460, 8],
    ['dlp', 'pii', 'DLP / Purview', 600, 460, 4],
    ['aud', 'audit', 'Compliance / eDiscovery', 600, 570, 4],
    ['k', 'kafka', 'Activity Stream', 750, 570, 2],
  ], [['u','gslb'],['gslb','waf'],['waf','graph'],['graph','entra'],['graph','ten'],['ten','exch'],
      ['exch','mbox'],['ten','spo'],['spo','files'],['ten','teams'],['spo','srch'],['ten','dlp'],
      ['graph','aud'],['spo','k']], [
    'Identity is the platform: every workload authorises through one directory with conditional access',
    'Tenant isolation is contractual, not just technical — noisy-neighbour and data-residency both matter',
    'One API surface (Graph) over many legacy backends is the integration story and the throttling problem',
    'Per-tenant throttling protects the shared fleet; publish the limits so customers can design for them',
    'Compliance is a first-class subsystem: retention, legal hold, eDiscovery and immutable audit',
    'DLP inspects content in motion — it sits on the write path and must not become the bottleneck',
    'Data residency means the same design deployed per geography, not one global cluster',
  ], 'Workplace & email'),

  T('Outlook', 'Mail, calendar and push at enterprise scale', 20000, [
    ['u', 'client', 'Clients', 40, 300, 1, 0.85], ['smtp', 'client', 'Inbound SMTP', 40, 470, 1, 0.15],
    ['lb', 'lb', 'LB', 180, 300, 2], ['mx', 'micro', 'MX / SMTP Ingest', 180, 470, 8],
    ['gw', 'gateway', 'API Gateway', 320, 300, 8],
    ['filter', 'ml', 'Spam / Malware Filter', 320, 470, 14],
    ['mail', 'app', 'Mailbox Service', 460, 300, 12],
    ['mbox', 'nosql', 'Mailbox Store', 610, 240, 10],
    ['idx', 'search', 'Mail Search Index', 610, 360, 8],
    ['att', 'blob', 'Attachment Store', 760, 240, 3],
    ['cal', 'micro', 'Calendar / Scheduling', 460, 420, 8],
    ['push', 'ws', 'Push / ActiveSync', 320, 180, 10],
    ['k', 'kafka', 'Mail Events', 610, 470, 2],
    ['ret', 'backup', 'Retention / Archive', 760, 470, 2],
    ['aud', 'audit', 'Audit Trail', 760, 360, 2],
  ], [['u','lb'],['lb','gw'],['smtp','mx'],['mx','filter'],['filter','mail'],['gw','mail'],
      ['mail','mbox'],['mail','idx'],['mail','att'],['gw','cal'],['gw','push'],['mail','k'],
      ['k','ret'],['mail','aud']], [
    'Inbound mail is untrusted input from the whole internet — filter before it touches a mailbox',
    'Spam and malware filtering is an adversarial ML problem with a hard latency budget',
    'Mailboxes are append-heavy and per-user: shard by mailbox, never scan across',
    'Search must be incremental — reindexing a large mailbox from scratch is not an option',
    'Push keeps clients in sync; falling back to polling multiplies your read load',
    'Calendar is a distributed scheduling problem: free/busy across organisations, recurrence, time zones',
    'Retention, legal hold and immutable archive are compliance requirements, not features',
  ], 'Workplace & email'),

  T('Gmail', 'Massive-scale mail with adversarial filtering', 60000, [
    ['u', 'client', 'Users', 40, 300, 1, 0.8], ['smtp', 'client', 'Inbound SMTP', 40, 480, 1, 0.2],
    ['cdn', 'cdn', 'Static / Web Client', 175, 170, 4],
    ['lb', 'lb', 'LB', 175, 300, 2], ['mx', 'micro', 'MX Frontends', 175, 480, 16],
    ['gw', 'gateway', 'API Gateway', 320, 300, 16],
    ['spam', 'ml', 'Spam / Phishing ML', 320, 480, 48],
    ['mail', 'app', 'Mail Service', 460, 300, 24],
    ['mbox', 'nosql', 'Sharded Mailbox Store', 610, 240, 16],
    ['idx', 'search', 'Search Index', 610, 380, 12],
    ['lbl', 'cache', 'Labels / Threads Cache', 460, 180, 8],
    ['att', 'blob', 'Attachment Store', 760, 240, 3],
    ['push', 'ws', 'Push Channel', 320, 180, 12],
    ['k', 'kafka', 'Mail Event Log', 610, 490, 3],
    ['abuse', 'analytics', 'Abuse Analytics', 760, 490, 8],
  ], [['u','cdn'],['u','lb'],['cdn','gw'],['lb','gw'],['smtp','mx'],['mx','spam'],['spam','mail'],
      ['gw','mail'],['gw','lbl'],['mail','mbox'],['mail','idx'],['mail','att'],['gw','push'],
      ['mail','k'],['k','abuse']], [
    'Threads and labels, not folders: a message belongs to many views, so model the mapping carefully',
    'Filtering is adversarial and continuous — attackers adapt within hours, so models retrain constantly',
    'Search is the primary navigation: the index is as important as the mailbox itself',
    'Storage per user is enormous and mostly cold — tier it and keep the hot window small',
    'Attachments dedup well across recipients of the same message',
    'Every action is an event; abuse analytics runs off that stream, not off the serving path',
    'Estimate: billions of messages a day, and one spam campaign can be a traffic spike by itself',
  ], 'Workplace & email'),

  T('Anthropic Claude', 'LLM API: safety, routing and GPU serving', 300, [
    ['u', 'client', 'API Clients', 40, 300], ['waf', 'waf', 'WAF / Abuse', 170, 300, 3],
    ['gw', 'gateway', 'API Gateway', 300, 300, 6],
    ['keys', 'iam', 'API Keys / Org Auth', 300, 170, 3],
    ['rl', 'ratelimiter', 'Token Rate Limits', 440, 170, 4],
    ['gin', 'guard', 'Input Safety', 440, 300, 6],
    ['cache', 'cache', 'Prompt Cache', 580, 190, 4],
    ['router', 'micro', 'Model Router', 580, 300, 6],
    ['gpu', 'k8s', 'GPU Scheduler', 720, 190, 3],
    ['llm', 'llm', 'Inference Fleet', 720, 300, 24],
    ['gout', 'guard', 'Output Safety', 860, 300, 6],
    ['tools', 'micro', 'Tool Use / MCP', 720, 430, 6],
    ['k', 'kafka', 'Usage Events', 580, 430, 2],
    ['bill', 'billing', 'Metering & Billing', 440, 430, 4],
    ['evals', 'warehouse', 'Evals & Analytics', 860, 430, 4],
  ], [['u','waf'],['waf','gw'],['gw','keys'],['gw','rl'],['gw','gin'],['gin','cache'],['gin','router'],
      ['cache','llm'],['router','llm'],['gpu','llm'],['llm','gout'],['router','tools'],['llm','k'],
      ['k','bill'],['k','evals']], [
    'Inference is the whole bill and the whole latency budget — everything else is rounding',
    'Prompt caching on a shared prefix is the single biggest cost and latency lever',
    'Stream tokens: time-to-first-token is the number users feel, not total completion time',
    'Rate limit on tokens, not requests — one long prompt costs more than a hundred short ones',
    'Safety runs on both sides: input for injection and abuse, output before it reaches the user',
    'Route by model tier: send easy work to a small model and reserve the large one',
    'GPU capacity is finite and slow to add — queue and shed load gracefully rather than timing out',
    'Metering must be exact; usage events are the invoice and cannot be lost or double-counted',
  ], 'AI / ML'),

  // ─────────────── robotics & edge ───────────────
  T('Simbe Tally (shelf-scanning robots)', 'Edge vision on a robot fleet, cloud analytics behind it', 8000, [
    ['tally', 'client', 'Tally Fleet', 40, 330, 1, 0.85],
    ['spot', 'client', 'Tally Spot / RFID', 40, 500, 1, 0.15],
    ['edge', 'edge', 'On-robot Inference', 185, 415, 12],
    ['up', 'gateway', 'Store Uplink', 325, 415, 10],
    ['waf', 'waf', 'WAF / Ingest Edge', 465, 415, 4],
    ['iam', 'iam', 'Device Identity', 465, 270, 3],
    ['fleet', 'config', 'Fleet Mgmt & OTA', 325, 270, 3],
    ['ing', 'app', 'Scan Ingest', 605, 415, 16],
    ['img', 'blob', 'Shelf Image Store', 745, 280, 3],
    ['q', 'queue', 'Vision Queue', 745, 415],
    ['vis', 'ml', 'Simbe Vision Inference', 885, 415, 40],
    ['vec', 'vector', 'Product Embeddings', 1025, 330, 8],
    ['cat', 'nosql', 'Product & Planogram', 1025, 470, 8],
    ['det', 'nosql', 'Detections Store', 885, 560, 8],
    ['k', 'kafka', 'Shelf Event Stream', 745, 560, 2],
    ['task', 'micro', 'Task Engine', 605, 560, 10],
    ['mob', 'bff', 'Mobile App API', 465, 560, 8],
    ['esb', 'esb', 'Retailer Integration', 605, 690, 4],
    ['lake', 'lake', 'Shelf Data Lake', 885, 690, 2],
    ['wh', 'warehouse', 'Brand Insights', 1025, 690, 6],
  ], [['tally','edge'],['spot','edge'],['edge','up'],['up','waf'],['waf','iam'],['waf','ing'],
      ['fleet','edge'],['ing','img'],['ing','q'],['q','vis'],['vis','vec'],['vis','cat'],['vis','det'],
      ['det','k'],['k','task'],['task','mob'],['k','lake'],['lake','wh'],['esb','cat']], [
    'Infer on the robot first — uploading raw video of every aisle over store wifi is not an option, so the edge sends detections plus sampled images',
    'The store uplink is the real constraint: it is shared with the point-of-sale system, so backhaul must be throttled, resumable and happy to run overnight',
    'Shelf images are write-once and enormous (billions of them) — store them cheaply, tier them aggressively, and never put them on the hot path',
    'Product recognition is a matching problem against millions of SKUs: embeddings plus ANN search beat a classifier per product, and new products appear weekly',
    'Ground truth comes from the retailer — planogram, price and POS feeds arrive by integration and are never clean; reconcile rather than trust',
    'Detections are not the product: the output is a prioritised task ("restock aisle 7"), not a dashboard full of raw data',
    'Fleet management is a first-class system — OTA updates, battery and charge cycles, and a robot that fails safe in a public space full of shoppers',
    'Chain-wide scale means per-banner tenancy and data isolation; one retailer must never see another retailer’s shelves',
    'Night scanning shifts the load profile — schedule the heavy analytics for when the stores are closed',
  ], 'Robotics & edge'),

  // ── AI systems ──────────────────────────────────────────────────────────────
  T('ChatGPT (conversational AI)', 'Consumer chat over a GPU fleet', 20000, [
    ['u', 'client', 'Users', 40, 250], ['cdn', 'cdn', 'CDN (static)', 170, 130],
    ['waf', 'waf', 'WAF / abuse', 170, 370], ['gw', 'gateway', 'API Gateway', 300, 250, 4],
    ['iam', 'iam', 'Auth / Session', 300, 110, 2], ['rl', 'ratelimiter', 'Plan Limits', 430, 110, 2],
    ['conv', 'app', 'Conversation Svc', 430, 250, 8], ['hist', 'nosql', 'Message Store', 430, 400, 4],
    ['mem', 'app', 'Memory Service', 560, 110, 3], ['gin', 'guard', 'Input Safety', 560, 250, 4],
    ['files', 'blob', 'Uploads', 560, 400], ['router', 'app', 'Model Router', 690, 250, 3],
    ['cache', 'cache', 'Prompt Cache', 690, 110, 3], ['tools', 'micro', 'Tools / Browsing', 690, 400, 4],
    ['llm', 'llm', 'Inference Fleet', 830, 250, 70], ['gout', 'guard', 'Output Safety', 970, 250, 4],
    ['k', 'kafka', 'Usage Events', 830, 400], ['bill', 'billing', 'Metering', 970, 400, 2],
  ], [
    ['u', 'cdn', 'app shell'], ['u', 'waf'], ['waf', 'gw'], ['gw', 'iam'], ['gw', 'rl'],
    ['rl', 'conv'], ['conv', 'hist', 'persist turn'], ['conv', 'mem', 'recall'], ['conv', 'files'],
    ['conv', 'gin'], ['gin', 'router'], ['router', 'cache', 'prefix hit'], ['router', 'llm'],
    ['llm', 'tools', 'tool call'], ['llm', 'gout'], ['conv', 'k'], ['k', 'bill'],
  ], [
    'Streaming is the product — time to first token matters far more than total generation time',
    'Conversation history grows unbounded; summarise or window it rather than resending everything',
    'Prompt caching on the shared system prefix is the single largest cost lever',
    'Safety runs on both input and output, and both are additional inference you must budget for',
    'Tool calls turn one request into several round trips — the latency budget has to absorb that',
    'Metering must be exact because it is billing, unlike almost everything else here',
  ], 'AI / ML'),

  T('LangChain (agent framework)', 'Tool-calling agents with memory and tracing', 800, [
    ['dev', 'client', 'App / Developer', 40, 250], ['sdk', 'app', 'SDK Runtime', 180, 250, 3],
    ['orch', 'app', 'Agent Orchestrator', 320, 250, 4], ['prompt', 'config', 'Prompt Registry', 320, 110],
    ['cache', 'cache', 'Semantic Cache', 320, 390, 2], ['tools', 'micro', 'Tool Router', 460, 250, 4],
    ['retr', 'vector', 'Vector Retriever', 460, 110, 3], ['mem', 'nosql', 'Agent Memory', 460, 390, 2],
    ['emb', 'embed', 'Embedding Svc', 600, 110, 3], ['llm', 'llm', 'LLM Provider', 600, 250, 8],
    ['sandbox', 'worker', 'Sandboxed Tools', 600, 390, 6], ['trace', 'tracing', 'Run Tracing', 740, 110],
    ['eval', 'worker', 'Eval Harness', 740, 390, 2], ['guard', 'guard', 'Output Guard', 740, 250, 3],
  ], [
    ['dev', 'sdk'], ['sdk', 'orch'], ['orch', 'prompt'], ['orch', 'cache'], ['orch', 'tools'],
    ['tools', 'retr', 'retrieval tool'], ['retr', 'emb'], ['tools', 'llm'], ['tools', 'sandbox', 'code / http'],
    ['orch', 'mem', 'scratchpad'], ['llm', 'guard'], ['orch', 'trace'], ['trace', 'eval'],
  ], [
    'The agent loop is unbounded by nature — cap iterations, wall-clock and token spend or it will not terminate',
    'Every tool is untrusted code or an untrusted endpoint; sandbox execution and set hard timeouts',
    'Memory is the hardest part: what to keep, what to summarise, what to retrieve per step',
    'Tracing is not optional — a failed agent run is incomprehensible without the full step-by-step',
    'Semantic caching on the whole agent input saves far more than caching individual LLM calls',
    'Evals have to run continuously; prompt changes regress silently and no test suite catches it',
  ], 'AI / ML'),

  T('AI Code Assistant (Copilot)', 'Inline completion under a 200ms budget', 30000, [
    ['ide', 'client', 'IDE Plugin', 40, 250], ['edge', 'edge', 'Edge PoP', 170, 250, 6],
    ['gw', 'gateway', 'API Gateway', 300, 250, 6], ['cache', 'cache', 'Completion Cache', 300, 400, 4],
    ['ctx', 'app', 'Context Builder', 440, 250, 10], ['idx', 'search', 'Repo Index', 440, 110, 4],
    ['emb', 'embed', 'Code Embeddings', 580, 110, 8], ['vec', 'vector', 'Vector Store', 720, 110, 4],
    ['router', 'app', 'Model Router', 580, 250, 4], ['llm', 'ml', 'Completion Model', 720, 250, 14],
    ['filt', 'guard', 'Secret / Licence Filter', 860, 250, 4], ['tel', 'kafka', 'Telemetry', 580, 400],
    ['an', 'analytics', 'Acceptance Metrics', 720, 400, 6], ['iam', 'iam', 'Org Policy', 300, 110, 2],
  ], [
    ['ide', 'edge'], ['edge', 'gw'], ['gw', 'iam'], ['gw', 'cache', 'exact prefix'], ['gw', 'ctx'],
    ['ctx', 'idx', 'nearby symbols'], ['idx', 'emb'], ['emb', 'vec'], ['ctx', 'router'],
    ['router', 'llm'], ['llm', 'filt'], ['ctx', 'tel'], ['tel', 'an'],
  ], [
    'The latency budget is brutal — a completion nobody waits for is a completion nobody uses',
    'Cancellation matters as much as speed: the user keeps typing and in-flight requests must be dropped',
    'Context selection beats model size — the right 2k tokens of repo context outperforms a bigger model',
    'Fill-in-the-middle, not just prefix continuation, since the cursor usually has code after it',
    'Never emit a secret or verbatim licensed code; filtering is a hard requirement, not a nicety',
    'Acceptance rate is the only metric that matters, and it must be measured per model version',
  ], 'AI / ML'),

  T('AI Search (Perplexity)', 'Retrieve, rerank, synthesise with citations', 5000, [
    ['u', 'client', 'Users', 40, 250], ['cdn', 'cdn', 'CDN', 170, 120],
    ['gw', 'gateway', 'API Gateway', 300, 250, 4], ['cache', 'cache', 'Answer Cache', 300, 400, 3],
    ['plan', 'app', 'Query Planner', 440, 250, 4], ['srch', 'search', 'Search Index', 440, 110, 4],
    ['prov', 'partner', 'Search Providers', 580, 110], ['vec', 'vector', 'Doc Embeddings', 440, 400, 3],
    ['fetch', 'worker', 'Page Fetchers', 580, 250, 8], ['rank', 'ml', 'Reranker', 720, 250, 4],
    ['llm', 'llm', 'Synthesis LLM', 860, 250, 24], ['cite', 'app', 'Citation Builder', 1000, 250, 3],
    ['k', 'kafka', 'Query Log', 720, 400], ['idx', 'worker', 'Index Refresh', 580, 400, 4],
  ], [
    ['u', 'cdn'], ['u', 'gw'], ['gw', 'cache'], ['gw', 'plan'], ['plan', 'srch'], ['srch', 'prov'],
    ['plan', 'vec'], ['plan', 'fetch', 'live pages'], ['fetch', 'rank'], ['srch', 'rank'],
    ['rank', 'llm', 'top-k passages'], ['llm', 'cite'], ['plan', 'k'], ['k', 'idx'],
  ], [
    'Every claim needs a citation traceable to a retrieved passage, or the product has no defence',
    'Retrieval quality caps answer quality — no model rescues bad passages',
    'Freshness is the differentiator over a static model, so live fetching sits on the hot path',
    'Fan-out to providers needs hard timeouts and partial results; one slow provider must not block',
    'Answer caching is delicate: the same question asked a day later may deserve a different answer',
    'Streaming hides multi-second synthesis, which is the only reason the latency is tolerable',
  ], 'AI / ML'),

  T('Image Generation (Diffusion)', 'Async GPU jobs with moderation', 2000, [
    ['u', 'client', 'Users', 40, 250], ['gw', 'gateway', 'API Gateway', 180, 250, 3],
    ['mod', 'guard', 'Prompt Moderation', 320, 120, 4], ['q', 'queue', 'Job Queue', 320, 250],
    ['ws', 'ws', 'Progress Stream', 320, 400, 4], ['sched', 'scheduler', 'GPU Scheduler', 460, 250, 2],
    ['meta', 'nosql', 'Job Metadata', 460, 400, 3], ['gpu', 'ml', 'Diffusion Workers', 600, 250, 40],
    ['safety', 'guard', 'Image Safety', 740, 250, 4], ['blob', 'blob', 'Image Store', 880, 250],
    ['cdn2', 'cdn', 'Delivery CDN', 1020, 250], ['bill', 'billing', 'Credits', 600, 400, 2],
    ['k', 'kafka', 'Job Events', 740, 400],
  ], [
    ['u', 'gw'], ['gw', 'mod'], ['mod', 'q', 'accepted'], ['gw', 'ws', 'subscribe'], ['q', 'sched'],
    ['sched', 'gpu'], ['sched', 'meta'], ['gpu', 'safety'], ['safety', 'blob'], ['blob', 'cdn2'],
    ['gpu', 'k'], ['k', 'bill'], ['k', 'ws', 'progress'],
  ], [
    'Generation takes tens of seconds, so it is a job, not a request — accept and return an id',
    'Moderate the prompt before spending GPU time, and the image after, because prompts get past you',
    'A GPU is either busy or wasted; batching and a scheduler that packs the fleet is the whole economics',
    'Progress updates are what make a 30-second wait tolerable',
    'Images are immutable and content-addressed — cache them at the edge forever',
    'Credits must be reserved on submit and settled on completion, or users generate for free on failure',
  ], 'AI / ML'),

  T('LLM Fine-tuning Platform', 'Data to trained model to serving', 200, [
    ['u', 'client', 'ML Engineers', 40, 250], ['gw', 'gateway', 'Control API', 180, 250, 2],
    ['data', 'app', 'Dataset Service', 320, 120, 2], ['val', 'worker', 'Data Validation', 320, 380, 4],
    ['lake', 'lake', 'Training Data Lake', 460, 120], ['sched', 'scheduler', 'Job Scheduler', 460, 250, 2],
    ['pii', 'pii', 'PII Scrubber', 460, 380, 3], ['train', 'worker', 'GPU Training Cluster', 620, 250, 48],
    ['ckpt', 'blob', 'Checkpoints', 620, 120], ['mon', 'monitor', 'Training Metrics', 620, 380],
    ['eval', 'worker', 'Eval Harness', 780, 250, 6], ['reg', 'registry', 'Model Registry', 780, 120],
    ['serve', 'llm', 'Serving Fleet', 920, 250, 10], ['audit', 'audit', 'Lineage / Audit', 780, 380],
  ], [
    ['u', 'gw'], ['gw', 'data'], ['data', 'val'], ['val', 'pii'], ['pii', 'lake'], ['data', 'lake'],
    ['gw', 'sched'], ['sched', 'train'], ['train', 'ckpt', 'every N steps'], ['train', 'mon'],
    ['train', 'eval'], ['eval', 'reg', 'promote'], ['reg', 'serve'], ['reg', 'audit'],
  ], [
    'Checkpoint constantly — a multi-day run that dies at 90% without checkpoints has lost everything',
    'Data quality dominates outcome far more than hyperparameters; validate and scrub before training',
    'Evaluation gates promotion, or you will ship a regression that looks fine in the loss curve',
    'GPUs are the budget: queue jobs by priority and preempt, because idle accelerators are pure waste',
    'Full lineage from dataset to deployed model is a compliance requirement in most regulated settings',
    'Rollback has to be as easy as promotion — pin serving to a registry version, never to "latest"',
  ], 'AI / ML'),

  // ── Marketplaces ────────────────────────────────────────────────────────────
  T('Amazon (marketplace)', 'Catalogue, delivery promise, fulfilment', 80000, [
    ['u', 'client', 'Shoppers', 40, 280], ['gslb', 'gslb', 'Global LB', 180, 180],
    ['cdn', 'cdn', 'Media CDN', 180, 380], ['seller', 'app', 'Seller Portal', 320, 80, 3],
    ['gw', 'gateway', 'API Gateway', 320, 280, 10],
    ['srch', 'search', 'Catalogue Search', 460, 80, 10], ['rec', 'ml', 'Recommendations', 460, 180, 32],
    ['prod', 'app', 'Product Service', 460, 280, 14], ['cart', 'app', 'Cart Service', 460, 380, 8],
    ['cat', 'nosql', 'Catalogue Store', 600, 80, 8], ['pcache', 'cache', 'Product Cache', 600, 180, 12],
    ['cartdb', 'nosql', 'Cart Store', 600, 380, 6], ['prom', 'app', 'Delivery Promise', 600, 480, 8],
    ['ord', 'app', 'Order Service', 740, 280, 10],
    ['pay', 'partner', 'Payments', 880, 180], ['odb', 'sql', 'Orders (ACID)', 880, 280, 8],
    ['k', 'kafka', 'Order Events', 880, 380], ['inv', 'sql', 'Inventory (per FC)', 880, 480, 10],
    ['ful', 'micro', 'Fulfilment', 1020, 380, 8],
  ], [
    ['u', 'gslb'], ['u', 'cdn', 'images'], ['gslb', 'gw'], ['seller', 'cat', 'listings'],
    ['gw', 'srch'], ['srch', 'cat'], ['gw', 'rec'], ['rec', 'pcache'], ['gw', 'prod'],
    ['prod', 'pcache'], ['pcache', 'cat', 'miss'], ['gw', 'cart'], ['cart', 'cartdb'],
    ['prod', 'prom', 'deliver by?'], ['prom', 'inv'], ['cart', 'ord', 'checkout'],
    ['ord', 'odb'], ['ord', 'pay'], ['ord', 'inv', 'reserve'], ['ord', 'k'], ['k', 'ful'],
  ], [
    'The delivery promise is the hard read — which warehouse holds it, and can it arrive by Tuesday',
    'Catalogue is read-heavy and near-immutable; inventory is write-heavy and strongly consistent',
    'Third-party sellers mean the catalogue has no single owner and no schema you control',
    'Inventory is per fulfilment centre, so "in stock" is a question about a place, not a product',
    'Checkout is a saga across payment, inventory and fulfilment with real compensations',
    'Recommendations must degrade to a generic row rather than block the page',
  ], 'Big tech'),

  T('Flipkart (Big Billion Days)', 'A marketplace built around a scheduled stampede', 60000, [
    ['u', 'client', 'Shoppers (app)', 40, 280], ['cdn', 'cdn', 'CDN + image opt', 180, 140],
    ['waf', 'waf', 'WAF / bot guard', 180, 400], ['gw', 'gateway', 'API Gateway', 320, 280, 10],
    ['srch', 'search', 'Search + Browse', 460, 140, 8], ['pdp', 'app', 'Product Page Svc', 460, 280, 14],
    ['q', 'queue', 'Sale Waiting Room', 460, 400],
    ['cat', 'nosql', 'Catalogue', 600, 140, 6], ['cache', 'cache', 'PDP Cache', 600, 280, 12],
    ['pin', 'app', 'Pincode Serviceability', 600, 400, 6],
    ['ord', 'app', 'Order Service', 740, 280, 10], ['inv', 'sql', 'Inventory (ACID)', 740, 400, 8],
    ['pay', 'app', 'Payment Router', 880, 140, 6], ['odb', 'nosql', 'Orders', 880, 280, 8],
    ['k', 'kafka', 'Order Events', 880, 400],
    ['upi', 'partner', 'UPI / Cards', 1020, 140, 6], ['cod', 'micro', 'COD Verification', 1020, 280, 4],
    ['ekart', 'micro', 'Logistics (Ekart)', 1020, 400, 8],
  ], [
    ['u', 'cdn'], ['u', 'waf'], ['waf', 'gw'], ['gw', 'srch'], ['srch', 'cat'],
    ['gw', 'pdp'], ['pdp', 'cache'], ['cache', 'cat', 'miss'], ['gw', 'q', 'flash sale'],
    ['q', 'ord', 'admitted'], ['pdp', 'pin', 'deliverable?'], ['pin', 'inv'],
    ['gw', 'ord', 'normal checkout'], ['ord', 'inv', 'reserve'], ['ord', 'odb'],
    ['ord', 'pay'], ['pay', 'upi'], ['pay', 'cod'], ['ord', 'k'], ['k', 'ekart'],
  ], [
    'The peak is on a published date — this is a provisioning problem, not an autoscaling one',
    'A flash sale is 10,000 units against millions of buyers: admission control, not capacity',
    'Cash on delivery changes the order state machine — the money arrives days after the order',
    'Pincode serviceability gates everything; an undeliverable product should never be purchasable',
    'Tier-2/3 networks mean payload size is a product feature, not an optimisation',
    'UPI and card rails are external ceilings — route across PSPs and degrade rather than fail',
  ], 'India · consumer'),

  T('IndiaMART (B2B leads)', 'The product is the lead, not the order', 8000, [
    ['b', 'client', 'Buyers', 40, 180], ['s', 'client', 'Suppliers', 40, 400],
    ['cdn', 'cdn', 'CDN (SEO pages)', 180, 80], ['seo', 'web', 'SEO Page Renderer', 320, 80, 10],
    ['gw', 'gateway', 'API Gateway', 320, 280, 6],
    ['srch', 'search', 'Supplier Search', 460, 180, 8], ['rfq', 'app', 'Buy-Lead (RFQ) Svc', 460, 280, 6],
    ['cat', 'nosql', 'Product Catalogue', 600, 80, 6], ['fraud', 'guard', 'Lead Quality / Fraud', 600, 180, 4],
    ['match', 'ml', 'Lead Matching', 600, 280, 12],
    ['leaddb', 'sql', 'Leads DB', 740, 280, 4], ['k', 'kafka', 'Lead Events', 740, 400],
    ['sub', 'billing', 'Seller Subscriptions', 880, 180, 3], ['cred', 'cache', 'Contact-Reveal Credits', 880, 280, 4],
    ['notif', 'micro', 'SMS / WhatsApp / Email', 880, 400, 8],
    ['crm', 'crm', 'Inside-Sales CRM', 1020, 180], ['wh', 'warehouse', 'Lead Analytics', 1020, 400],
  ], [
    ['b', 'cdn'], ['b', 'gw'], ['s', 'gw', 'listings + responses'], ['cdn', 'seo', 'origin'],
    ['seo', 'cat'], ['gw', 'srch'], ['srch', 'cat'], ['gw', 'rfq'], ['rfq', 'fraud'],
    ['fraud', 'match'], ['match', 'leaddb'], ['match', 'k'], ['k', 'notif'],
    ['leaddb', 'cred', 'reveal contact'], ['cred', 'sub'], ['sub', 'crm'], ['k', 'wh'],
  ], [
    'Buyers are free and suppliers pay — the two sides need completely different SLAs',
    'A lead delivered late is worthless, so matching and notification are the latency-critical path',
    'Lead quality is the whole business: fake enquiries destroy supplier trust faster than downtime',
    'Millions of SEO landing pages are the acquisition channel, so rendering is a scale problem',
    'Contact reveal is metered against a subscription — that counter is billing and must be exact',
    'Distribution is fan-out with a cap: one enquiry to too many suppliers devalues every one of them',
  ], 'India · consumer'),
]
