// Pre-wired classic system designs. Node: [id, type, label, x, y, replicas, weight]
// weight = share of total traffic for source (client) nodes.
const T = (name, tagline, rps, nodes, edges, checklist) => ({
  name, tagline, rps,
  nodes: nodes.map(([id, type, label, x, y, replicas = 1, weight]) => ({ id, type, label, x, y, replicas, ...(weight !== undefined ? { weight } : {}) })),
  edges: edges.map(([from, to, label = '']) => ({ id: `${from}->${to}`, from, to, label })),
  checklist,
})

export const TEMPLATES = [
  T('URL Shortener (Bitly)', 'Read-heavy redirect service', 12000, [
    ['c', 'client', 'Users', 60, 220], ['cdn', 'cdn', 'CDN', 200, 220],
    ['lb', 'lb', 'LB', 340, 220], ['app', 'app', 'Read/Write API', 480, 220, 4],
    ['cache', 'cache', 'Hot URLs', 640, 120], ['db', 'nosql', 'URL Table', 640, 320, 3],
  ], [['c','cdn'],['cdn','lb'],['lb','app'],['app','cache'],['app','db']], [
    'Short code generation: base62 of counter vs hash — collision handling?',
    'Read:write ratio ~100:1 → cache the redirects aggressively',
    '301 vs 302 redirect trade-off (caching vs analytics)',
    'Counter service or KGS to avoid duplicate codes',
    'Estimate: 100M new URLs/month ≈ 40 writes/s, 4k reads/s',
  ]),
  T('Ticketmaster', 'Concurrency control for seat booking', 8000, [
    ['c', 'client', 'Fans', 40, 240], ['cdn', 'cdn', 'CDN', 170, 240],
    ['lb', 'lb', 'LB', 300, 240], ['gw', 'gateway', 'API GW', 420, 240, 2],
    ['search', 'search', 'Event Search', 570, 100, 2], ['book', 'app', 'Booking Svc', 570, 240, 6],
    ['lock', 'cache', 'Seat Locks TTL', 730, 160], ['sql', 'sql', 'Bookings ACID', 730, 320, 2],
    ['q', 'queue', 'Waiting Queue', 570, 400],
  ], [['c','cdn'],['cdn','lb'],['lb','gw'],['gw','search'],['gw','book'],['book','lock'],['book','sql'],['gw','q'],['q','book']], [
    'Reserve seat with distributed lock (Redis TTL) before payment',
    'ACID transaction on final booking — no double sell',
    'Virtual waiting queue absorbs 100x flash-sale spikes',
    'Search events via Elasticsearch, not the booking DB',
    'Optimistic vs pessimistic locking trade-off',
  ]),
  T('Ride Sharing (Uber)', 'Realtime geo matching', 15000, [
    ['r', 'client', 'Riders', 40, 160, 1, 0.5], ['d', 'client', 'Drivers', 40, 340, 1, 0.5],
    ['lb', 'lb', 'LB', 190, 250], ['gw', 'gateway', 'API GW', 320, 250, 3],
    ['loc', 'ws', 'Location WS', 470, 350, 4], ['geo', 'cache', 'Geo Index (H3)', 640, 350, 3],
    ['match', 'app', 'Matching Svc', 470, 160, 6], ['trip', 'sql', 'Trips DB', 640, 100, 2],
    ['k', 'kafka', 'Location Stream', 640, 250], ['surge', 'analytics', 'Surge Pricing', 800, 250, 3],
  ], [['r','lb'],['d','lb'],['lb','gw'],['gw','loc'],['loc','geo'],['gw','match'],['match','geo'],['match','trip'],['loc','k'],['k','surge']], [
    'Drivers push GPS every 4s over WebSocket — do the math on write QPS',
    'Geo-index (H3/geohash) in memory, not in SQL',
    'Matching: nearest-driver query on the geo index + ETA ranking',
    'Kafka stream feeds surge pricing & analytics',
    'Trip state machine: requested → matched → in-ride → completed',
  ]),
  T('Video Platform (YouTube)', 'Upload pipeline + massive read fan-out', 50000, [
    ['c', 'client', 'Viewers', 40, 140, 1, 0.95], ['up', 'client', 'Uploaders', 40, 380, 1, 0.05],
    ['cdn', 'cdn', 'Video CDN', 200, 140], ['lb', 'lb', 'LB', 200, 300],
    ['app', 'app', 'Watch API', 360, 220, 6], ['meta', 'nosql', 'Metadata', 520, 140, 3],
    ['upsvc', 'app', 'Upload Svc', 360, 380, 3], ['blob', 'blob', 'Raw Storage', 520, 460],
    ['q', 'queue', 'Transcode Q', 520, 380], ['w', 'worker', 'Transcoders', 680, 380, 10],
    ['out', 'blob', 'Encoded (HLS)', 680, 240], ['ml', 'ml', 'Recommendations', 520, 240, 8],
  ], [['c','cdn'],['cdn','app'],['app','meta'],['app','ml'],['up','lb'],['lb','upsvc'],['upsvc','blob'],['upsvc','q'],['q','w'],['w','out'],['out','cdn']], [
    'Chunked resumable uploads straight to object storage',
    'Async transcode pipeline: queue + worker pool, multiple bitrates (HLS/DASH)',
    'CDN serves ~all watch traffic; origin only on miss',
    'Metadata (views, titles) in partitioned NoSQL',
    'View-count: approximate counting / batched increments',
  ]),
  T('Chat (WhatsApp)', 'Persistent connections & delivery guarantees', 30000, [
    ['a', 'client', 'User A', 40, 160], ['b', 'client', 'User B', 40, 340],
    ['lb', 'lb', 'LB (sticky)', 190, 250], ['ws', 'ws', 'Chat Servers', 340, 250, 6],
    ['sess', 'cache', 'Session Registry', 500, 130], ['q', 'kafka', 'Msg Log', 500, 250],
    ['inbox', 'nosql', 'Inbox Store', 500, 380, 3], ['push', 'micro', 'Push Notif', 660, 250, 3],
    ['media', 'blob', 'Media Store', 660, 380],
  ], [['a','lb'],['b','lb'],['lb','ws'],['ws','sess'],['ws','q'],['q','inbox'],['q','push'],['ws','media']], [
    'One WebSocket per online user; session registry maps user → server',
    'Message IDs monotonic per conversation; at-least-once + dedupe',
    'Offline users: persist to inbox, deliver on reconnect + push notif',
    'Sent/delivered/read receipts as tiny state events',
    'E2E encryption means server stores ciphertext only',
  ]),
  T('Web Crawler', 'Politeness + dedup at scale', 2000, [
    ['seed', 'client', 'Seed URLs', 40, 240], ['front', 'queue', 'URL Frontier', 190, 240],
    ['sched', 'scheduler', 'Politeness Sched', 340, 140, 4], ['f', 'worker', 'Fetchers', 340, 320, 8],
    ['dns', 'dns', 'DNS Cache', 500, 420], ['parse', 'worker', 'Parsers', 500, 320, 4],
    ['dedup', 'cache', 'Seen? (Bloom)', 500, 140], ['store', 'blob', 'Page Store', 660, 320],
    ['idx', 'search', 'Index', 660, 180],
  ], [['seed','front'],['front','sched'],['sched','f'],['f','dns'],['f','parse'],['parse','dedup'],['dedup','front'],['parse','store'],['store','idx']], [
    'Frontier with per-domain queues → politeness (1 req/domain/sec)',
    'Bloom filter for URL-seen test at billions scale',
    'DNS caching — resolution is a real bottleneck',
    'Content dedup via simhash, trap/spider-web detection',
    'Estimate: 1B pages / 30 days ≈ 400 fetches/s sustained',
  ]),
  T('Collab Docs (Google Docs)', 'Realtime co-editing & OT/CRDT', 10000, [
    ['c', 'client', 'Editors', 40, 240], ['lb', 'lb', 'LB', 190, 240],
    ['ws', 'ws', 'Doc Sessions', 340, 240, 4], ['ot', 'app', 'OT/CRDT Engine', 500, 160, 5],
    ['cache', 'cache', 'Live Doc State', 660, 160], ['log', 'kafka', 'Op Log', 500, 320],
    ['db', 'nosql', 'Snapshots', 660, 320, 2], ['pres', 'micro', 'Presence', 340, 400, 3],
  ], [['c','lb'],['lb','ws'],['ws','ot'],['ot','cache'],['ot','log'],['log','db'],['ws','pres']], [
    'OT vs CRDT for concurrent edits — why you picked one',
    'One authoritative session per doc (sticky routing / doc-sharded)',
    'Op log + periodic snapshots → fast load and full history',
    'Presence & cursors are ephemeral, skip durable storage',
    'Offline edits reconcile through same transform pipeline',
  ]),
  T('News Feed (Twitter/X)', 'Fan-out on write vs read', 12000, [
    ['c', 'client', 'Users', 40, 240], ['lb', 'lb', 'LB', 180, 240],
    ['gw', 'gateway', 'API GW', 310, 240, 3], ['tw', 'app', 'Tweet Write', 460, 350, 6],
    ['tl', 'app', 'Timeline Read', 460, 130, 6], ['fan', 'worker', 'Fanout Workers', 620, 350, 8],
    ['tlc', 'cache', 'Timeline Cache', 620, 130, 4], ['soc', 'cache', 'Social Graph', 780, 350],
    ['db', 'nosql', 'Tweet Store', 780, 240, 3], ['rank', 'ml', 'Ranker', 620, 240, 10],
  ], [['c','lb'],['lb','gw'],['gw','tw'],['gw','tl'],['tw','db'],['tw','fan'],['fan','soc'],['fan','tlc'],['tl','tlc'],['tl','rank']], [
    'Fan-out on write for normal users; on read for celebrities (hybrid)',
    'Timeline cache = list of tweet IDs per user, hydrate on read',
    'Social graph lookups must be O(1) — cache it',
    'Ranking layer between cache and response',
    'Estimate: 500M tweets/day ≈ 6k writes/s, reads 100x that',
  ]),
  T('File Sync (Dropbox)', 'Chunking, dedup, delta sync', 6000, [
    ['c', 'client', 'Desktop Clients', 40, 240], ['lb', 'lb', 'LB', 190, 240],
    ['meta', 'app', 'Metadata Svc', 340, 150, 4], ['db', 'sql', 'Meta DB', 500, 90, 2],
    ['blockp', 'app', 'Block Svc', 340, 330, 4], ['blob', 'blob', 'Block Store', 500, 330],
    ['notif', 'ws', 'Notify (long-poll)', 340, 450], ['q', 'queue', 'Sync Events', 500, 450],
    ['cache', 'cache', 'Meta Cache', 500, 210],
  ], [['c','lb'],['lb','meta'],['meta','cache'],['meta','db'],['lb','blockp'],['blockp','blob'],['q','notif'],['meta','q'],['notif','c']], [
    'Files split into 4MB chunks; content-hash dedup across users',
    'Delta sync — only changed blocks travel',
    'Metadata (namespace, versions) separate from block storage',
    'Notification channel wakes other devices on change',
    'Conflict copy on concurrent edit, never silent overwrite',
  ]),
  T('Rate Limiter (as a system)', 'Shared counters, low latency', 24000, [
    ['c', 'client', 'API Callers', 40, 240], ['lb', 'lb', 'LB', 190, 240],
    ['rl', 'ratelimiter', 'Limiter Nodes', 340, 240, 4], ['redis', 'cache', 'Counters (Redis)', 500, 160, 3],
    ['rules', 'sql', 'Rules DB', 500, 330, 2], ['api', 'app', 'Protected API', 660, 240, 5],
    ['k', 'kafka', 'Decisions Log', 340, 400], ['an', 'analytics', 'Abuse Analytics', 500, 450, 3],
  ], [['c','lb'],['lb','rl'],['rl','redis'],['rl','rules'],['rl','api'],['rl','k'],['k','an']], [
    'Sliding-window counter in Redis (INCR + EXPIRE, Lua for atomicity)',
    'Local in-memory cache of rules; sync from DB',
    'Fail-open or fail-closed when Redis is down — decide!',
    '429 with Retry-After; expose headers X-RateLimit-*',
    'Hot-key problem: shard counters for giant tenants',
  ]),
  T('Local Search (Yelp)', 'Geo queries + reviews', 9000, [
    ['c', 'client', 'Users', 40, 240], ['cdn', 'cdn', 'CDN', 180, 240],
    ['lb', 'lb', 'LB', 320, 240], ['app', 'app', 'Search API', 460, 240, 4],
    ['geo', 'search', 'Geo Index', 620, 150, 3], ['biz', 'sql', 'Business DB', 620, 330, 2],
    ['cache', 'cache', 'Hot Areas', 620, 240], ['rev', 'micro', 'Reviews Svc', 460, 400, 2],
  ], [['c','cdn'],['cdn','lb'],['lb','app'],['app','cache'],['app','geo'],['app','biz'],['lb','rev'],['rev','biz']], [
    'Geohash/quadtree index for "restaurants near me"',
    'Search radius expansion when sparse results',
    'Reviews write path separate from search read path',
    'Cache popular city/category combos',
    'Ranking: distance + rating + open-now filters',
  ]),
  T('Leaderboard (Top-K)', 'Sorted sets & windows', 12000, [
    ['c', 'client', 'Game Clients', 40, 240], ['gw', 'gateway', 'API GW', 190, 240, 2],
    ['ing', 'micro', 'Score Ingest', 340, 320, 3], ['k', 'kafka', 'Score Stream', 500, 320],
    ['agg', 'worker', 'Aggregators', 660, 320, 8], ['z', 'cache', 'Redis ZSET', 660, 160, 3],
    ['read', 'micro', 'Leaderboard API', 340, 160, 3], ['db', 'nosql', 'History', 800, 320],
  ], [['c','gw'],['gw','ing'],['ing','k'],['k','agg'],['agg','z'],['agg','db'],['gw','read'],['read','z']], [
    'Redis sorted set gives O(log n) rank updates and top-K reads',
    'Windowed boards (daily/weekly) = separate keys with TTL',
    'Stream + aggregator absorbs write bursts',
    'Around-me query: ZRANK ± N',
    'Persist history for offline analytics/anti-cheat',
  ]),
  T('Notification System', 'Multi-channel fan-out', 8000, [
    ['svc', 'client', 'Producer Services', 40, 240], ['gw', 'gateway', 'Notif API', 190, 240, 2],
    ['q', 'kafka', 'Notif Topics', 340, 240], ['pref', 'nosql', 'Prefs/Devices', 340, 400, 2],
    ['w', 'worker', 'Channel Workers', 500, 240, 10], ['push', 'micro', 'APNs/FCM', 660, 140],
    ['email', 'micro', 'Email (SES)', 660, 240], ['sms', 'micro', 'SMS', 660, 340],
    ['dedup', 'cache', 'Dedup/Rate', 500, 400],
  ], [['svc','gw'],['gw','q'],['q','w'],['w','pref'],['w','dedup'],['w','push'],['w','email'],['w','sms']], [
    'Queue between producers and channels — absorb bursts, retry safely',
    'Idempotency key per notification, dedup cache',
    'User prefs + quiet hours checked at send time',
    'Per-channel rate limits & provider failover',
    'Track delivery receipts for retries/analytics',
  ]),
  T('Payment System (Stripe-lite)', 'Exactly-once money movement', 4000, [
    ['c', 'client', 'Merchants', 40, 240], ['gw', 'gateway', 'API GW', 180, 240, 2],
    ['pay', 'app', 'Payment Svc', 330, 240, 4], ['idem', 'cache', 'Idempotency Keys', 330, 100],
    ['led', 'sql', 'Ledger (ACID)', 490, 160, 2], ['q', 'queue', 'Outbox', 490, 320],
    ['w', 'worker', 'PSP Connector', 650, 320, 3], ['psp', 'micro', 'Card Networks', 800, 320],
    ['rec', 'scheduler', 'Reconciliation', 650, 450],
  ], [['c','gw'],['gw','pay'],['pay','idem'],['pay','led'],['pay','q'],['q','w'],['w','psp'],['rec','led']], [
    'Idempotency keys on every mutation — retries must be safe',
    'Double-entry ledger, append-only, ACID',
    'Outbox pattern: DB commit + async PSP call, never dual-write',
    'State machine: created → authorized → captured → settled',
    'Daily reconciliation against PSP reports',
  ]),
  T('Search Autocomplete', 'Prefix trees at the edge', 45000, [
    ['c', 'client', 'Typers', 40, 240], ['cdn', 'cdn', 'Edge Cache', 180, 240],
    ['lb', 'lb', 'LB', 320, 240], ['ac', 'micro', 'Suggest Svc', 460, 240, 6],
    ['trie', 'cache', 'Trie Shards', 620, 160, 4], ['k', 'kafka', 'Query Log', 460, 380],
    ['agg', 'analytics', 'Trending Agg', 620, 380, 2], ['store', 'nosql', 'Trie Builder Out', 780, 380],
  ], [['c','cdn'],['cdn','lb'],['lb','ac'],['ac','trie'],['ac','k'],['k','agg'],['agg','store'],['store','trie']], [
    'Trie/weighted prefix index fully in memory, sharded by prefix',
    'Sub-100ms budget → cache top prefixes at CDN',
    'Offline pipeline rebuilds tries from query logs hourly',
    'Debounce client-side; only 2+ chars hit servers',
    'Personalization & trending merged at ranking time',
  ]),
]
