// Pre-wired classic system designs. Node: [id, type, label, x, y, replicas, weight]
// weight = share of total traffic for source (client) nodes.
// group drives the optgroup in the template picker.
const T = (name, tagline, rps, nodes, edges, checklist, group = 'Product designs') => ({
  name, tagline, rps, group,
  nodes: nodes.map(([id, type, label, x, y, replicas = 1, weight]) => ({ id, type, label, x, y, replicas, ...(weight !== undefined ? { weight } : {}) })),
  edges: edges.map(([from, to, label = '']) => ({ id: `${from}->${to}`, from, to, label })),
  checklist,
})

export const TEMPLATES = [
  T('URL Shortener (Bitly)', 'Read-heavy redirect service', 12000, [
    ['c', 'client', 'Users', 60, 220], ['cdn', 'cdn', 'CDN', 200, 220],
    ['lb', 'lb', 'LB', 340, 220], ['app', 'app', 'Read/Write API', 480, 220, 4],
    ['cache', 'cache', 'Hot URLs', 640, 120], ['db', 'nosql', 'URL Table', 640, 320, 3],
  ], [['c','cdn'],['cdn','lb'],['lb','app'],['app','cache'],['app','db']], [
    'Short code generation: base62 of counter vs hash — collision handling?',
    'Read:write ratio ~100:1 → cache the redirects aggressively',
    '301 vs 302 redirect trade-off (caching vs analytics)',
    'Counter service or KGS to avoid duplicate codes',
    'Estimate: 100M new URLs/month ≈ 40 writes/s, 4k reads/s',
  ]),
  T('Ticketmaster', 'Concurrency control for seat booking', 8000, [
    ['c', 'client', 'Fans', 40, 240], ['cdn', 'cdn', 'CDN', 170, 240],
    ['lb', 'lb', 'LB', 300, 240], ['gw', 'gateway', 'API GW', 420, 240, 2],
    ['search', 'search', 'Event Search', 570, 100, 2], ['book', 'app', 'Booking Svc', 570, 240, 6],
    ['lock', 'cache', 'Seat Locks TTL', 730, 160], ['sql', 'sql', 'Bookings ACID', 730, 320, 2],
    ['q', 'queue', 'Waiting Queue', 570, 400],
  ], [['c','cdn'],['cdn','lb'],['lb','gw'],['gw','search'],['gw','book'],['book','lock'],['book','sql'],['gw','q'],['q','book']], [
    'Reserve seat with distributed lock (Redis TTL) before payment',
    'ACID transaction on final booking — no double sell',
    'Virtual waiting queue absorbs 100x flash-sale spikes',
    'Search events via Elasticsearch, not the booking DB',
    'Optimistic vs pessimistic locking trade-off',
  ]),
  T('Ride Sharing (Uber)', 'Realtime geo matching', 15000, [
    ['r', 'client', 'Riders', 40, 160, 1, 0.5], ['d', 'client', 'Drivers', 40, 340, 1, 0.5],
    ['lb', 'lb', 'LB', 190, 250], ['gw', 'gateway', 'API GW', 320, 250, 3],
    ['loc', 'ws', 'Location WS', 470, 350, 4], ['geo', 'cache', 'Geo Index (H3)', 640, 350, 3],
    ['match', 'app', 'Matching Svc', 470, 160, 6], ['trip', 'sql', 'Trips DB', 640, 100, 2],
    ['k', 'kafka', 'Location Stream', 640, 250], ['surge', 'analytics', 'Surge Pricing', 800, 250, 3],
  ], [['r','lb'],['d','lb'],['lb','gw'],['gw','loc'],['loc','geo'],['gw','match'],['match','geo'],['match','trip'],['loc','k'],['k','surge']], [
    'Drivers push GPS every 4s over WebSocket — do the math on write QPS',
    'Geo-index (H3/geohash) in memory, not in SQL',
    'Matching: nearest-driver query on the geo index + ETA ranking',
    'Kafka stream feeds surge pricing & analytics',
    'Trip state machine: requested → matched → in-ride → completed',
  ]),
  T('Video Platform (YouTube)', 'Upload pipeline + massive read fan-out', 50000, [
    ['c', 'client', 'Viewers', 40, 140, 1, 0.95], ['up', 'client', 'Uploaders', 40, 380, 1, 0.05],
    ['cdn', 'cdn', 'Video CDN', 200, 140], ['lb', 'lb', 'LB', 200, 300],
    ['app', 'app', 'Watch API', 360, 220, 6], ['meta', 'nosql', 'Metadata', 520, 140, 3],
    ['upsvc', 'app', 'Upload Svc', 360, 380, 3], ['blob', 'blob', 'Raw Storage', 520, 460],
    ['q', 'queue', 'Transcode Q', 520, 380], ['w', 'worker', 'Transcoders', 680, 380, 10],
    ['out', 'blob', 'Encoded (HLS)', 680, 240], ['ml', 'ml', 'Recommendations', 520, 240, 8],
  ], [['c','cdn'],['cdn','app'],['app','meta'],['app','ml'],['up','lb'],['lb','upsvc'],['upsvc','blob'],['upsvc','q'],['q','w'],['w','out'],['out','cdn']], [
    'Chunked resumable uploads straight to object storage',
    'Async transcode pipeline: queue + worker pool, multiple bitrates (HLS/DASH)',
    'CDN serves ~all watch traffic; origin only on miss',
    'Metadata (views, titles) in partitioned NoSQL',
    'View-count: approximate counting / batched increments',
  ]),
  T('Chat (WhatsApp)', 'Persistent connections & delivery guarantees', 30000, [
    ['a', 'client', 'User A', 40, 160], ['b', 'client', 'User B', 40, 340],
    ['lb', 'lb', 'LB (sticky)', 190, 250], ['ws', 'ws', 'Chat Servers', 340, 250, 6],
    ['sess', 'cache', 'Session Registry', 500, 130], ['q', 'kafka', 'Msg Log', 500, 250],
    ['inbox', 'nosql', 'Inbox Store', 500, 380, 3], ['push', 'micro', 'Push Notif', 660, 250, 3],
    ['media', 'blob', 'Media Store', 660, 380],
  ], [['a','lb'],['b','lb'],['lb','ws'],['ws','sess'],['ws','q'],['q','inbox'],['q','push'],['ws','media']], [
    'One WebSocket per online user; session registry maps user → server',
    'Message IDs monotonic per conversation; at-least-once + dedupe',
    'Offline users: persist to inbox, deliver on reconnect + push notif',
    'Sent/delivered/read receipts as tiny state events',
    'E2E encryption means server stores ciphertext only',
  ]),
  T('Web Crawler', 'Politeness + dedup at scale', 2000, [
    ['seed', 'client', 'Seed URLs', 40, 240], ['front', 'queue', 'URL Frontier', 190, 240],
    ['sched', 'scheduler', 'Politeness Sched', 340, 140, 4], ['f', 'worker', 'Fetchers', 340, 320, 8],
    ['dns', 'dns', 'DNS Cache', 500, 420], ['parse', 'worker', 'Parsers', 500, 320, 4],
    ['dedup', 'cache', 'Seen? (Bloom)', 500, 140], ['store', 'blob', 'Page Store', 660, 320],
    ['idx', 'search', 'Index', 660, 180],
  ], [['seed','front'],['front','sched'],['sched','f'],['f','dns'],['f','parse'],['parse','dedup'],['dedup','front'],['parse','store'],['store','idx']], [
    'Frontier with per-domain queues → politeness (1 req/domain/sec)',
    'Bloom filter for URL-seen test at billions scale',
    'DNS caching — resolution is a real bottleneck',
    'Content dedup via simhash, trap/spider-web detection',
    'Estimate: 1B pages / 30 days ≈ 400 fetches/s sustained',
  ]),
  T('Collab Docs (Google Docs)', 'Realtime co-editing & OT/CRDT', 10000, [
    ['c', 'client', 'Editors', 40, 240], ['lb', 'lb', 'LB', 190, 240],
    ['ws', 'ws', 'Doc Sessions', 340, 240, 4], ['ot', 'app', 'OT/CRDT Engine', 500, 160, 5],
    ['cache', 'cache', 'Live Doc State', 660, 160], ['log', 'kafka', 'Op Log', 500, 320],
    ['db', 'nosql', 'Snapshots', 660, 320, 2], ['pres', 'micro', 'Presence', 340, 400, 3],
  ], [['c','lb'],['lb','ws'],['ws','ot'],['ot','cache'],['ot','log'],['log','db'],['ws','pres']], [
    'OT vs CRDT for concurrent edits — why you picked one',
    'One authoritative session per doc (sticky routing / doc-sharded)',
    'Op log + periodic snapshots → fast load and full history',
    'Presence & cursors are ephemeral, skip durable storage',
    'Offline edits reconcile through same transform pipeline',
  ]),
  T('News Feed (Twitter/X)', 'Fan-out on write vs read', 12000, [
    ['c', 'client', 'Users', 40, 240], ['lb', 'lb', 'LB', 180, 240],
    ['gw', 'gateway', 'API GW', 310, 240, 3], ['tw', 'app', 'Tweet Write', 460, 350, 6],
    ['tl', 'app', 'Timeline Read', 460, 130, 6], ['fan', 'worker', 'Fanout Workers', 620, 350, 8],
    ['tlc', 'cache', 'Timeline Cache', 620, 130, 4], ['soc', 'cache', 'Social Graph', 780, 350],
    ['db', 'nosql', 'Tweet Store', 780, 240, 3], ['rank', 'ml', 'Ranker', 620, 240, 10],
  ], [['c','lb'],['lb','gw'],['gw','tw'],['gw','tl'],['tw','db'],['tw','fan'],['fan','soc'],['fan','tlc'],['tl','tlc'],['tl','rank']], [
    'Fan-out on write for normal users; on read for celebrities (hybrid)',
    'Timeline cache = list of tweet IDs per user, hydrate on read',
    'Social graph lookups must be O(1) — cache it',
    'Ranking layer between cache and response',
    'Estimate: 500M tweets/day ≈ 6k writes/s, reads 100x that',
  ]),
  T('File Sync (Dropbox)', 'Chunking, dedup, delta sync', 6000, [
    ['c', 'client', 'Desktop Clients', 40, 240], ['lb', 'lb', 'LB', 190, 240],
    ['meta', 'app', 'Metadata Svc', 340, 150, 4], ['db', 'sql', 'Meta DB', 500, 90, 2],
    ['blockp', 'app', 'Block Svc', 340, 330, 4], ['blob', 'blob', 'Block Store', 500, 330],
    ['notif', 'ws', 'Notify (long-poll)', 340, 450], ['q', 'queue', 'Sync Events', 500, 450],
    ['cache', 'cache', 'Meta Cache', 500, 210],
  ], [['c','lb'],['lb','meta'],['meta','cache'],['meta','db'],['lb','blockp'],['blockp','blob'],['q','notif'],['meta','q'],['notif','c']], [
    'Files split into 4MB chunks; content-hash dedup across users',
    'Delta sync — only changed blocks travel',
    'Metadata (namespace, versions) separate from block storage',
    'Notification channel wakes other devices on change',
    'Conflict copy on concurrent edit, never silent overwrite',
  ]),
  T('Rate Limiter (as a system)', 'Shared counters, low latency', 24000, [
    ['c', 'client', 'API Callers', 40, 240], ['lb', 'lb', 'LB', 190, 240],
    ['rl', 'ratelimiter', 'Limiter Nodes', 340, 240, 4], ['redis', 'cache', 'Counters (Redis)', 500, 160, 3],
    ['rules', 'sql', 'Rules DB', 500, 330, 2], ['api', 'app', 'Protected API', 660, 240, 5],
    ['k', 'kafka', 'Decisions Log', 340, 400], ['an', 'analytics', 'Abuse Analytics', 500, 450, 5],
  ], [['c','lb'],['lb','rl'],['rl','redis'],['rl','rules'],['rl','api'],['rl','k'],['k','an']], [
    'Sliding-window counter in Redis (INCR + EXPIRE, Lua for atomicity)',
    'Local in-memory cache of rules; sync from DB',
    'Fail-open or fail-closed when Redis is down — decide!',
    '429 with Retry-After; expose headers X-RateLimit-*',
    'Hot-key problem: shard counters for giant tenants',
  ]),
  T('Local Search (Yelp)', 'Geo queries + reviews', 9000, [
    ['c', 'client', 'Users', 40, 240], ['cdn', 'cdn', 'CDN', 180, 240],
    ['lb', 'lb', 'LB', 320, 240], ['app', 'app', 'Search API', 460, 240, 4],
    ['geo', 'search', 'Geo Index', 620, 150, 3], ['biz', 'sql', 'Business DB', 620, 330, 2],
    ['cache', 'cache', 'Hot Areas', 620, 240], ['rev', 'micro', 'Reviews Svc', 460, 400, 2],
  ], [['c','cdn'],['cdn','lb'],['lb','app'],['app','cache'],['app','geo'],['app','biz'],['lb','rev'],['rev','biz']], [
    'Geohash/quadtree index for "restaurants near me"',
    'Search radius expansion when sparse results',
    'Reviews write path separate from search read path',
    'Cache popular city/category combos',
    'Ranking: distance + rating + open-now filters',
  ]),
  T('Leaderboard (Top-K)', 'Sorted sets & windows', 12000, [
    ['c', 'client', 'Game Clients', 40, 240], ['gw', 'gateway', 'API GW', 190, 240, 2],
    ['ing', 'micro', 'Score Ingest', 340, 320, 3], ['k', 'kafka', 'Score Stream', 500, 320],
    ['agg', 'worker', 'Aggregators', 660, 320, 8], ['z', 'cache', 'Redis ZSET', 660, 160, 3],
    ['read', 'micro', 'Leaderboard API', 340, 160, 3], ['db', 'nosql', 'History', 800, 320],
  ], [['c','gw'],['gw','ing'],['ing','k'],['k','agg'],['agg','z'],['agg','db'],['gw','read'],['read','z']], [
    'Redis sorted set gives O(log n) rank updates and top-K reads',
    'Windowed boards (daily/weekly) = separate keys with TTL',
    'Stream + aggregator absorbs write bursts',
    'Around-me query: ZRANK ± N',
    'Persist history for offline analytics/anti-cheat',
  ]),
  T('Notification System', 'Multi-channel fan-out', 8000, [
    ['svc', 'client', 'Producer Services', 40, 240], ['gw', 'gateway', 'Notif API', 190, 240, 2],
    ['q', 'kafka', 'Notif Topics', 340, 240], ['pref', 'nosql', 'Prefs/Devices', 340, 400, 2],
    ['w', 'worker', 'Channel Workers', 500, 240, 10], ['push', 'micro', 'APNs/FCM', 660, 140],
    ['email', 'micro', 'Email (SES)', 660, 240], ['sms', 'micro', 'SMS', 660, 340],
    ['dedup', 'cache', 'Dedup/Rate', 500, 400],
  ], [['svc','gw'],['gw','q'],['q','w'],['w','pref'],['w','dedup'],['w','push'],['w','email'],['w','sms']], [
    'Queue between producers and channels — absorb bursts, retry safely',
    'Idempotency key per notification, dedup cache',
    'User prefs + quiet hours checked at send time',
    'Per-channel rate limits & provider failover',
    'Track delivery receipts for retries/analytics',
  ]),
  T('Payment System (Stripe-lite)', 'Exactly-once money movement', 4000, [
    ['c', 'client', 'Merchants', 40, 240], ['gw', 'gateway', 'API GW', 180, 240, 2],
    ['pay', 'app', 'Payment Svc', 330, 240, 4], ['idem', 'cache', 'Idempotency Keys', 330, 100],
    ['led', 'sql', 'Ledger (ACID)', 490, 160, 2], ['q', 'queue', 'Outbox', 490, 320],
    ['w', 'worker', 'PSP Connector', 650, 320, 3], ['psp', 'micro', 'Card Networks', 800, 320],
    ['rec', 'scheduler', 'Reconciliation', 650, 450],
  ], [['c','gw'],['gw','pay'],['pay','idem'],['pay','led'],['pay','q'],['q','w'],['w','psp'],['rec','led']], [
    'Idempotency keys on every mutation — retries must be safe',
    'Double-entry ledger, append-only, ACID',
    'Outbox pattern: DB commit + async PSP call, never dual-write',
    'State machine: created → authorized → captured → settled',
    'Daily reconciliation against PSP reports',
  ]),
  T('Search Autocomplete', 'Prefix trees at the edge', 45000, [
    ['c', 'client', 'Typers', 40, 240], ['cdn', 'cdn', 'Edge Cache', 180, 240],
    ['lb', 'lb', 'LB', 320, 240], ['ac', 'micro', 'Suggest Svc', 460, 240, 6],
    ['trie', 'cache', 'Trie Shards', 620, 160, 4], ['k', 'kafka', 'Query Log', 460, 380],
    ['agg', 'analytics', 'Trending Agg', 620, 380, 2], ['store', 'nosql', 'Trie Builder Out', 780, 380],
  ], [['c','cdn'],['cdn','lb'],['lb','ac'],['ac','trie'],['ac','k'],['k','agg'],['agg','store'],['store','trie']], [
    'Trie/weighted prefix index fully in memory, sharded by prefix',
    'Sub-100ms budget → cache top prefixes at CDN',
    'Offline pipeline rebuilds tries from query logs hourly',
    'Debounce client-side; only 2+ chars hit servers',
    'Personalization & trending merged at ranking time',
  ]),

  // ─────────────── microservice architecture patterns ───────────────
  T('µsvc: E-commerce (Saga)', 'Service-per-domain + distributed transaction', 6000, [
    ['c', 'client', 'Storefront', 40, 250], ['gw', 'gateway', 'API Gateway', 175, 250, 2],
    ['mesh', 'mesh', 'Service Mesh', 175, 400, 2], ['reg', 'registry', 'Discovery', 40, 400],
    ['saga', 'saga', 'Order Saga', 330, 250, 3],
    ['order', 'micro', 'Order Svc', 490, 120, 2], ['odb', 'sql', 'orders db', 650, 120],
    ['inv', 'micro', 'Inventory Svc', 490, 250, 2], ['idb', 'sql', 'inventory db', 650, 250],
    ['pay', 'micro', 'Payment Svc', 490, 380, 2], ['pdb', 'sql', 'payments db', 650, 380],
    ['ship', 'micro', 'Shipping Svc', 490, 500, 2], ['bus', 'kafka', 'Event Bus', 330, 500],
  ], [['c','gw'],['gw','mesh'],['mesh','reg'],['gw','saga'],['saga','order'],['order','odb'],
      ['saga','inv'],['inv','idb'],['saga','pay'],['pay','pdb'],['saga','bus'],['bus','ship']], [
    'Database-per-service — no cross-service joins or shared schema',
    'Saga with compensating transactions (cancel order, release stock, refund)',
    'Orchestration (central saga) vs choreography (services react to events)',
    'Outbox pattern so DB commit and event publish cannot diverge',
    'Idempotent handlers — every event may be delivered twice',
  ], 'Microservice patterns'),
  T('µsvc: CQRS + Event Sourcing', 'Split write model from read models', 9000, [
    ['c', 'client', 'Clients', 40, 250], ['gw', 'gateway', 'API Gateway', 175, 250, 2],
    ['cmd', 'micro', 'Command Side', 320, 150, 3], ['es', 'kafka', 'Event Store (log)', 480, 150],
    ['proj', 'worker', 'Projectors', 640, 150, 4],
    ['rd1', 'nosql', 'Read Model A', 800, 90, 2], ['rd2', 'search', 'Read Model B', 800, 220, 2],
    ['qry', 'micro', 'Query Side', 320, 340, 4], ['qc', 'cache', 'Query Cache', 480, 340, 2],
    ['snap', 'blob', 'Snapshots', 640, 340],
  ], [['c','gw'],['gw','cmd'],['cmd','es'],['es','proj'],['proj','rd1'],['proj','rd2'],
      ['gw','qry'],['qry','qc'],['qc','rd1'],['es','snap']], [
    'Commands mutate via events only; state is a fold over the log',
    'Read models are disposable — rebuild by replaying the event store',
    'Eventual consistency window between write and read side: how do you hide it?',
    'Snapshots to bound replay time for long-lived aggregates',
    'Event versioning / schema evolution (upcasting)',
  ], 'Microservice patterns'),
  T('µsvc: BFF + Mesh Platform', 'Per-client edge, sidecar-managed east-west', 14000, [
    ['web', 'client', 'Web', 40, 130], ['mob', 'client', 'Mobile', 40, 300],
    ['bffw', 'bff', 'Web BFF', 200, 130, 3], ['bffm', 'bff', 'Mobile BFF', 200, 300, 3],
    ['mesh', 'mesh', 'Sidecar Mesh', 360, 215, 4],
    ['a', 'micro', 'Catalog Svc', 520, 90, 3], ['b', 'micro', 'Profile Svc', 520, 215, 3],
    ['d', 'micro', 'Pricing Svc', 520, 340, 3],
    ['cfg', 'config', 'Config/Flags', 360, 430], ['reg', 'registry', 'Discovery', 360, 520],
    ['tr', 'tracing', 'Tracing', 680, 430], ['cache', 'cache', 'Shared Cache', 680, 215, 2],
  ], [['web','bffw'],['mob','bffm'],['bffw','mesh'],['bffm','mesh'],['mesh','a'],['mesh','b'],
      ['mesh','d'],['b','cache'],['mesh','cfg'],['cfg','reg'],['mesh','tr']], [
    'One BFF per client type — mobile needs fewer fields than web',
    'Sidecar handles mTLS, retries with jitter, circuit breaking, canary splits',
    'Fan-out per request: N downstream calls means N× tail-latency risk',
    'Timeout budget must shrink at every hop, never grow',
    'Discovery + centralised config so services stay stateless',
  ], 'Microservice patterns'),
  T('µsvc: Event-Driven Orders', 'Choreography, no central coordinator', 8000, [
    ['c', 'client', 'Clients', 40, 250], ['gw', 'gateway', 'API Gateway', 175, 250, 2],
    ['ord', 'micro', 'Order Svc', 320, 250, 5], ['bus', 'kafka', 'Kafka Topics', 470, 250],
    ['pay', 'micro', 'Payment Consumer', 620, 110, 2],
    ['inv', 'micro', 'Stock Consumer', 620, 250, 2],
    ['notif', 'worker', 'Notify Consumer', 620, 390, 3],
    ['dlq', 'queue', 'DLQ', 470, 400], ['proj', 'nosql', 'Order View', 780, 250, 2],
    ['an', 'analytics', 'Stream Analytics', 780, 110, 2],
  ], [['c','gw'],['gw','ord'],['ord','bus'],['bus','pay'],['bus','inv'],['bus','notif'],
      ['bus','dlq'],['pay','proj'],['an','proj'],['pay','an']], [
    'Services react to events — no service calls another synchronously',
    'Consumer groups + partition key (orderId) preserve per-order ordering',
    'Dead-letter queue with retry/backoff for poison messages',
    'Exactly-once is really at-least-once + idempotent consumers',
    'Trade-off: loose coupling, but the end-to-end flow is hard to see',
  ], 'Microservice patterns'),
  T('µsvc: Strangler Migration', 'Carving services out of a monolith', 7000, [
    ['c', 'client', 'Clients', 40, 250], ['lb', 'lb', 'Router / LB', 180, 250],
    ['gw', 'gateway', 'Strangler Facade', 320, 250, 3],
    ['mono', 'app', 'Legacy Monolith', 480, 380, 4], ['mdb', 'sql', 'Legacy DB', 640, 460, 2],
    ['new1', 'micro', 'Users Svc (new)', 480, 130, 3], ['ndb1', 'nosql', 'users db', 640, 80, 2],
    ['new2', 'micro', 'Search Svc (new)', 480, 240, 3], ['ndb2', 'search', 'search index', 640, 200, 2],
    ['cdc', 'kafka', 'CDC Stream', 640, 330], ['sync', 'worker', 'Sync Workers', 800, 330, 3],
  ], [['c','lb'],['lb','gw'],['gw','new1'],['new1','ndb1'],['gw','new2'],['new2','ndb2'],
      ['gw','mono'],['mono','mdb'],['mdb','cdc'],['cdc','sync'],['sync','ndb1']], [
    'Facade routes per-endpoint: new service or monolith, flip gradually',
    'CDC keeps extracted data in sync during dual-write period',
    'Migrate by bounded context, never by database table',
    'Every extraction needs a rollback path (route back to monolith)',
    'Retire monolith code only once traffic is 0% for a full cycle',
  ], 'Microservice patterns'),

  // ─────────────── data platform ───────────────
  T('Data Platform (Lakehouse)', 'Ingest → lake → warehouse → BI', 3000, [
    ['app', 'client', 'Product Services', 40, 200], ['ops', 'client', 'Ops/3rd-party', 40, 380],
    ['oltp', 'sql', 'Prod OLTP DB', 200, 470, 2], ['cdc', 'cdc', 'CDC (Debezium)', 340, 470, 2],
    ['bus', 'kafka', 'Ingest Stream', 210, 290],
    ['raw', 'lake', 'Lake — raw/bronze', 380, 200, 2],
    ['etl', 'etl', 'ELT Transform', 540, 290, 6],
    ['cur', 'lake', 'Lake — curated/silver', 380, 380, 2],
    ['wh', 'warehouse', 'Warehouse (gold)', 700, 290, 4],
    ['bi', 'bi', 'BI / Dashboards', 860, 200, 4],
    ['ml', 'ml', 'Feature/ML Jobs', 860, 380, 6],
    ['sch', 'scheduler', 'Orchestrator (DAGs)', 540, 470, 2],
  ], [['app','bus'],['app','oltp'],['ops','bus'],['bus','raw'],['oltp','cdc'],['cdc','bus'],['raw','etl'],
      ['etl','cur'],['cur','wh'],['etl','wh'],['wh','bi'],['wh','ml'],['sch','etl']], [
    'Medallion layout: raw/bronze is immutable, curated/silver is conformed, warehouse/gold is modelled',
    'Lake vs warehouse: schema-on-read + cheap PB storage vs modelled columnar SQL performance',
    'ELT (transform inside the warehouse) vs ETL (transform before load)',
    'CDC off the OLTP replica — analytics must never query the production primary',
    'Partitioning + file compaction; small-files problem kills lake query performance',
    'Orchestrator owns DAG dependencies, retries, backfills and data-freshness SLAs',
    'Idempotent loads keyed on batch/watermark so replays do not double-count',
  ], 'Data platform'),

  // ─────────────── AI / ML system design ───────────────
  T('GenAI: RAG Assistant', 'Retrieval-augmented chat over your own docs', 400, [
    ['c', 'client', 'Users', 40, 250], ['gw', 'gateway', 'API Gateway', 180, 250, 2],
    ['rl', 'ratelimiter', 'Token Budget', 180, 400, 2],
    ['orch', 'app', 'Orchestrator', 330, 250, 4],
    ['gin', 'guard', 'Input Guardrails', 330, 110, 2],
    ['qemb', 'embed', 'Query Embedder', 480, 340, 3],
    ['vec', 'vector', 'Vector DB', 630, 340, 3],
    ['sem', 'cache', 'Semantic Cache', 480, 180, 2],
    ['llm', 'llm', 'LLM Inference', 630, 180, 12],
    ['gout', 'guard', 'Output Guardrails', 790, 180, 2],
    ['ing', 'worker', 'Doc Ingest', 330, 520, 3], ['blob', 'blob', 'Doc Store', 480, 520],
    ['iemb', 'embed', 'Index Embedder', 630, 520, 3],
    ['obs', 'analytics', 'Eval + Traces', 790, 340, 2],
  ], [['c','gw'],['gw','rl'],['gw','orch'],['orch','gin'],['orch','sem'],['sem','llm'],
      ['orch','qemb'],['qemb','vec'],['llm','gout'],['ing','blob'],['ing','iemb'],['iemb','vec'],['llm','obs']], [
    'Retrieval first, generation second — chunking strategy and chunk size drive answer quality',
    'Semantic cache on embeddings: identical-intent questions skip the LLM entirely (huge cost lever)',
    'LLM is the bottleneck by orders of magnitude — batch requests, stream tokens, cap max output',
    'Cost/latency budget per request: embed + ANN search + prompt tokens + generated tokens',
    'Guardrails on both sides: prompt injection and PII in, hallucination and unsafe content out',
    'Index pipeline is separate from the serving path; re-embed when the model version changes',
    'Evaluation is a first-class component — log traces, ground-truth sets, offline scoring',
  ], 'AI / ML'),
  T('ML: Recommendation Ranking', 'Candidate generation → ranking → serving', 20000, [
    ['c', 'client', 'Users', 40, 250], ['cdn', 'cdn', 'CDN', 170, 250],
    ['gw', 'gateway', 'API Gateway', 300, 250, 3],
    ['rec', 'micro', 'Recs Service', 440, 250, 6],
    ['cand', 'cache', 'Candidate Store', 590, 120, 3],
    ['feat', 'cache', 'Feature Store', 590, 250, 4],
    ['rank', 'ml', 'Ranker (GBDT/NN)', 740, 250, 20],
    ['fb', 'kafka', 'Click/Impression Log', 440, 400],
    ['train', 'worker', 'Training Jobs', 590, 400, 4],
    ['lake', 'lake', 'Feature Lake', 740, 400, 2],
    ['ab', 'config', 'A/B + Model Registry', 300, 400, 2],
  ], [['c','cdn'],['cdn','gw'],['gw','rec'],['rec','cand'],['rec','feat'],['rec','rank'],
      ['rec','fb'],['fb','train'],['train','lake'],['lake','feat'],['gw','ab']], [
    'Two stages: cheap candidate generation (thousands) then expensive ranking (hundreds)',
    'Feature store must serve online reads with the same values training saw — beware skew',
    'Latency budget ~100ms end to end, so the ranker gets a hard cap on candidates',
    'Feedback loop: impressions and clicks streamed back, and position bias corrected for',
    'Model registry + A/B assignment so a bad model is one flag flip away from rollback',
    'Cold start for new users and new items; fall back to popularity',
  ], 'AI / ML'),

  // ─────────────── enterprise & observability ───────────────
  T('Enterprise: Zero-Trust Platform', 'Regulated multi-tenant SaaS over legacy cores', 9000, [
    ['c', 'client', 'Customers', 40, 250], ['probe', 'synthetic', 'Synthetic Probes', 40, 560],
    ['gslb', 'gslb', 'Global Traffic Mgr', 175, 250], ['waf', 'waf', 'WAF / DDoS', 310, 250, 2],
    ['cdn', 'cdn', 'CDN', 310, 120],
    ['gw', 'gateway', 'API Gateway', 445, 250, 4], ['iam', 'iam', 'Identity (SSO)', 445, 400, 3],
    ['ten', 'tenant', 'Tenant Router', 580, 250, 2],
    ['k8s', 'k8s', 'Container Platform', 580, 120, 2],
    ['svc', 'micro', 'Domain Services', 715, 250, 6],
    ['sec', 'secrets', 'Secrets / KMS', 715, 400, 2], ['pii', 'pii', 'Tokenization Vault', 850, 400, 2],
    ['db', 'sql', 'Tenant DB (sharded)', 850, 250, 4], ['bk', 'backup', 'Backup & Archive', 985, 250, 2],
    ['mq', 'mq', 'Enterprise MQ', 715, 560, 3], ['esb', 'esb', 'Integration Bus', 850, 560, 3],
    ['core', 'mainframe', 'Mainframe Core', 985, 500, 2], ['erp', 'erp', 'ERP (SAP)', 985, 620, 2],
    ['aud', 'audit', 'Audit Log', 580, 560, 2],
  ], [['c','gslb'],['gslb','waf'],['waf','cdn'],['waf','gw'],['gw','iam'],['gw','ten'],['ten','svc'],
      ['k8s','svc'],['svc','sec'],['svc','pii'],['svc','db'],['db','bk'],['svc','mq'],['mq','esb'],
      ['esb','core'],['esb','erp'],['svc','aud'],['probe','gslb']], [
    'Zero trust: authenticate and authorise at every hop, never rely on network position',
    'Tenant isolation — shared schema vs schema-per-tenant vs silo, and the noisy-neighbour blast radius',
    'Systems of record (mainframe, ERP) cap out at ~1k rps and cannot scale out — always async behind MQ/ESB',
    'Tokenize PII/PAN early so downstream systems fall out of PCI/GDPR scope',
    'Secrets from KMS with rotation; nothing long-lived in config',
    'Audit log is append-only and tamper-evident, with a retention period set by regulation',
    'Backups are not replicas: prove the restore path with a timed drill',
    'Active-active regions behind GSLB, with an explicit RPO/RTO target',
  ], 'Enterprise'),
  T('Observability: Golden Signals', 'Instrument, aggregate, alert, and prove SLOs', 12000, [
    ['c', 'client', 'Users', 40, 260], ['probe', 'synthetic', 'Synthetic Probes', 40, 430],
    ['rum', 'apm', 'RUM / Client APM', 40, 100, 2],
    ['lb', 'lb', 'LB', 180, 260], ['gw', 'gateway', 'API Gateway', 310, 260, 3],
    ['svc', 'micro', 'Services', 445, 260, 8], ['k8s', 'k8s', 'Container Platform', 445, 110, 2],
    ['db', 'sql', 'Database', 445, 410, 3],
    ['otel', 'otel', 'OTel Collector', 600, 260, 3],
    ['met', 'monitor', 'Metrics & Alerts', 745, 130, 2],
    ['log', 'logs', 'Log Pipeline', 745, 260, 3],
    ['tr', 'tracing', 'Tracing', 745, 390, 2],
    ['slo', 'slo', 'SLO / Error Budget', 890, 130, 2],
    ['siem', 'siem', 'SIEM', 890, 260, 2],
    ['page', 'alert', 'On-call / Paging', 1035, 190, 2],
  ], [['c','lb'],['probe','lb'],['rum','otel'],['lb','gw'],['gw','svc'],['k8s','svc'],['svc','db'],
      ['svc','otel'],['gw','otel'],['k8s','otel'],['otel','met'],['otel','log'],['otel','tr'],
      ['met','slo'],['log','siem'],['slo','page'],['met','page'],['siem','page']], [
    'Four golden signals: latency, traffic, errors, saturation — per service, not just per host',
    'One OTel collector pipeline: batching, tail sampling, PII redaction in one place',
    'Correlate the three pillars with a shared trace id, or debugging stays guesswork',
    'Alert on symptoms and SLO burn rate, never on every individual cause — page fatigue is real',
    'Cardinality is the metrics cost driver; never label with user or request ids',
    'RUM shows what users actually experience; server p50 can look fine while the page is slow',
    'Synthetic probes from outside catch DNS, TLS and edge failures your internal metrics cannot see',
    'Log retention tiers: hot for days, warm for weeks, archive for compliance',
  ], 'Observability'),
]
